dotnet/BenchmarkDotNet

BenchmarkDotNet.Samples/Algo_MostSignificantBit.cs
BenchmarkDotNet.Samples/BenchmarkDotNet.Samples.csproj
BenchmarkDotNet.Samples/Jit_BoolToInt.cs
BenchmarkDotNet.Samples/Program.cs
BenchmarkDotNet.sln

It appears that the JIT is quite bad at optimizing Convert.Int32(bool)
// BenchmarkDotNet=v0.7.6.0
// OS=Microsoft Windows NT 6.2.9200.0
// Processor=Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz, ProcessorCount=4
// CLR=MS.NET 4.0.30319.42000, Arch=64-bit  [RyuJIT]
Common:  Type=Jit_BoolToInt  Mode=Throughput  Platform=X64  .NET=Current
Method |       Jit |   AvrTime |   StdDev |       op/s |
-------------- |---------- |---------- |--------- |----------- |
Framework | LegacyJit |   1.16 us | 28.20 ns |  858517.79 |
IfThenElse | LegacyJit |   1.08 us | 44.58 ns |  929458.93 |
UnsafeConvert | LegacyJit | 595.83 ns |  5.79 ns | 1678333.61 |
Framework |    RyuJit |   1.31 us | 18.64 ns |  765539.56 |
IfThenElse |    RyuJit |   1.31 us | 16.05 ns |  761023.73 |
UnsafeConvert |    RyuJit | 896.80 …

Most significant bit and bool-to-int conversions.

---

BenchmarkDotNet/BenchmarkRunner.cs

- use thousands separators for easier viewing;
- use 2 decimal point precision always for aligned printing.
Partially addressed https://github.com/PerfDotNet/BenchmarkDotNet/issues/16

Reporting: better number formats for ops/sec.

---

BenchmarkDotNet/Reports/BenchmarkTimeSpan.cs

- Makes report look much better with everything aligned;
- Four decimals is a good comporomise;
- Implemented using compile-time feature switch.
Sample:
```
Method |    AvrTime |    StdDev |           op/s |
------- |----------- |---------- |--------------- |
Sqrt13 | 60.7802 ns | 0.2933 ns |  16,452,713.42 |
Sqrt14 |  1.6146 ns | 0.0162 ns | 619,364,025.60 |
```

Reporting: use fixed precision for AvrTime and StdDev.

---

BenchmarkDotNet.Samples/BenchmarkDotNet.Samples.csproj
BenchmarkDotNet.Samples/Intro_04_UniformReportingTest.cs
BenchmarkDotNet.Samples/Program.cs
BenchmarkDotNet/BenchmarkRunner.cs
BenchmarkDotNet/Reports/BenchmarkTimeSpan.cs

As per https://github.com/PerfDotNet/BenchmarkDotNet/issues/16
For usability use the same time unit when reporting `AvrTime` and `StdDev`.
Sample output:
```
Method |        AvrTime |      StdDev |       op/s |
-------- |--------------- |------------ |----------- |
Slower1 |      1.8112 us |   0.2015 us | 552,120.14 |
Slower2 |      2.4149 us |   0.2425 us | 414,095.82 |
Slower3 |      9.0558 us |   0.3052 us | 110,426.47 |
Slower4 |     81.2006 us |   1.2585 us |  12,315.18 |
Slower5 |  4,148.1727 us | 740.3897 us |     241.07 |
Slower6 | 15,047.0119 us |  99.5290 us |      66.46 |
```

Reporting: uniform time units across all benchmarks.

---

BenchmarkDotNet/BenchmarkCompetitionSwitch.cs

Lets allow using just <number> as well as #<number> for choosing benchmarks in samples.

Allow just number param in RunCompetitions.

---

BenchmarkDotNet.Samples/Algorithms/Algo_BitCount.cs
BenchmarkDotNet.Samples/BenchmarkDotNet.Samples.csproj
BenchmarkDotNet.Samples/JIT/Jit_RotateBits.cs
BenchmarkDotNet.Samples/Program.cs

Added RotateBits will be interesting when https://github.com/dotnet/coreclr/issues/1619 is included in the Desktop RyuJIT and the CoreCLR runtime benchmarking works properly.
Added alternative implementations of PopCount for reference
* Naive If based implementation
* Parallel PopCount (two operations simultaneously avoiding data hazards).

More examples also couldnt make CoreCLR to work on my machine. Check the example. 

---

BenchmarkDotNet.Samples/JIT/Jit_GenericsMethod.cs

That one reproduces on all platforms. Let's think about more concise repro and figure out what optimizations x64 performs comparing to x86 that the previous one didn't reproduce.

Change Jit_GenericsMethod benchmark to reproduce on x64 both Legacy & RuyJit

---

BenchmarkDotNet.IntegrationTests/BaselineDiffColumnTest.cs
BenchmarkDotNet.IntegrationTests/StatResultExtenderTests.cs
BenchmarkDotNet.Samples/Intro/IntroPercentiles.cs
BenchmarkDotNet.Tests/StatisticsTests.cs
BenchmarkDotNet/Columns/BaselineDiffColumn.cs
BenchmarkDotNet/Columns/StatisticColumn.cs
BenchmarkDotNet/Mathematics/PercentileValues.cs
BenchmarkDotNet/Mathematics/Statistics.cs
README.md

Redo #138.
The text from the original PR:
As I wrote [here](https://github.com/PerfDotNet/BenchmarkDotNet/issues/126#issuecomment-200302063) I begin to do small PR to make it easier to use BenchmarkDotNet as an competition tests runner.
This PR adds Nth percentile and Nth percenile scaled columns. These should be used to rank and to compare competitors if the timings are varying from run to run.
More info on these: 
http://www.goland.org/average_percentile_services/
http://apmblog.dynatrace.com/2012/11/14/why-averages-suck-and-percentiles-are-great/
P.S. I'm not sure that proposed API design is good enough so it's definitely subject to discuss:)

Percentiles added into Statistics, StatisticColumn, BaselineDiffColumn

---

BenchmarkDotNet.Samples/CPU/Cpu_Ilp_Max.cs

The benchmark is improperly testing the Max operation because as all the numbers are 0 only a single path will be exercised.
The side effect is that the microarchitecture is able to branch predict everything and also there are no load-store dependencies (which is not true in the general case).
I modified the test to account for a random array and also added other ways to calculate Math.Max which would showcase the impact on instruction level parallelism in the face of store-load dependencies.

The benchmark is improperly testing ILP

---

BenchmarkDotNet.sln

For some reason the project BenchmarkDotNet was not a 'build dependency'
of BenchmarkDotNet.IntegrationTests.Classic
This was making the build fail

Added missing 'build dependency'

---

BenchmarkDotNet.IntegrationTests/MemoryDiagnoserTests.cs
BenchmarkDotNet.IntegrationTests/MultipleRuntimesTest.cs
BenchmarkDotNet.IntegrationTests/OutputLogger.cs
BenchmarkDotNet.IntegrationTests/PerformanceUnitTest.cs
BenchmarkDotNet.IntegrationTests/ProcessorArchitectureTest.cs
BenchmarkDotNet.IntegrationTests/ValidatorsTest.cs

Wired up OutputLogger to tests that were not using it so that output can
be seen in AppVeyor under the tests tab

Fixed tests not using OutputLogger

---

BenchmarkDotNet/Configs/ConfigParser.cs
BenchmarkDotNet/Exporters/AsciiDocExporter.cs

Support for exporting to [asciidoc format](http://asciidoc.org/userguide.html).
See https://github.com/PerfDotNet/BenchmarkDotNet/pull/165 for original PR.
I'm unable to run tests to check the output at the moment; I've raised issue https://github.com/PerfDotNet/BenchmarkDotNet/issues/168. I've [implemented the exporter here with the same impl](https://github.com/elastic/elasticsearch-net/blob/6e301c6c1350f9c81fb8e310c51dbb988939b0c2/src/Tests/Framework/Benchmarks/AsciiDocExporter.cs)and checked the output.

Support export to asciidoc

---

.gitignore
docs/api/BenchmarkDotNet.shfbproj
docs/api/GenerateHtml.cmd
src/BenchmarkDotNet.Core/project.json
src/BenchmarkDotNet.Diagnostics.Windows/project.json
src/BenchmarkDotNet/project.json

Uses Sandcastle Help File Builder: https://github.com/EWSoftware/SHFB. This has to be installed.
It generates an API reference manual similar to MSDN, including search. This is configurable through the GUI of SHFB, if you want to change anything, or alter the shfbproj file in a text editor. Generation uses msbuild so vsvars32.bat is called to get msbuild into the path. If this isn't needed, remove it from the generatehtml.cmd file It generates output into docs\apihtml which is ignored in the gitignore file.
For #219

Added Api docs generation directives

---

src/BenchmarkDotNet.Core/Running/BenchmarkConverter.cs

If you have a code like this:
```
class A 
{
[Benchmark]
public void Test()
{
var b = 42;
}
}
```
you will get a message
> Benchmark method Test defined within type MyProject.A has incorrect access modifiers.
>Declaring type must be public.
IMO it's confusing as it implies that method, not type has incorrect access modifier.
I think
>MyProject.A containing Benchmark method Test has incorrect access modifiers.
is less confusing.

Better wording for error message

---

src/BenchmarkDotNet.Core/Attributes/BenchmarkAttribute.cs
src/BenchmarkDotNet.Core/Helpers/CodeAnnotations.cs

Added Resharper code annotations to the project, and marked BenchmarkAttribute as implying implicit use. For users of BenchmarkDotNet which have R#, this will remove the "unused method" warning on benchmark methods.
Note that this PR includes the entire R# CodeAnnotations.cs, which makes sense if you intend to use the annotations in BenchmarkDotNet itself (to improve code quality). If not I can amend the PR, removing all annotations except the relevant [MeansImplicitUse].

Mark [Benchmark] as implying implicit use

---

docs/guide/RulesOfBenchmarking.md

Unless there's something about cmd that's preferable over any of the other shells, probably no need to call it out specifically.

Remove unnecessary specific shell reference

---

src/BenchmarkDotNet.Core/Properties/AssemblyInfo.cs
src/BenchmarkDotNet.Diagnostics.Windows/Properties/AssemblyInfo.cs
src/BenchmarkDotNet.Toolchains.Roslyn/Properties/AssemblyInfo.cs
src/BenchmarkDotNet/Properties/AssemblyInfo.cs

By applying CLSCompliant(true) attribute to assemblies library consumers no longer need to mark their public code (methods, constructors) referencing BenchmarkDotNet assets as CLSCompliant(false).

Make shipped assemblies have CLSCompliant(true) applied

---

src/BenchmarkDotNet.Core/Exporters/HtmlExporter.cs

* I made the exported HTML valid, it was missing required container elements.
* Added encoding information
* Added same kind of table styling that GitHub uses, now reading results is easier with alternating row background colors

Make exported HTML valid, add alternating color to table

---

docs/guide/Configs/Configs.md
docs/guide/Configs/Jobs.md
docs/guide/Overview.md

Fix docs: job API changed

---

docs/guide/Configs/Jobs.md
src/BenchmarkDotNet.Core/Characteristics/Characteristic.cs
src/BenchmarkDotNet.Core/Characteristics/CharacteristicHelper.cs
src/BenchmarkDotNet.Core/Characteristics/CharacteristicSet.cs
src/BenchmarkDotNet.Core/Characteristics/CharacteristicSetPresenter.cs
src/BenchmarkDotNet.Core/Characteristics/Characteristic`1.cs
src/BenchmarkDotNet.Core/Characteristics/JobMode.cs
src/BenchmarkDotNet.Core/Environments/EnvResolver.cs
src/BenchmarkDotNet.Core/Jobs/AccuracyMode.cs
src/BenchmarkDotNet.Core/Jobs/GcModeExtensions.cs
src/BenchmarkDotNet.Core/Jobs/JobExtensions.cs
src/BenchmarkDotNet.Core/Running/BenchmarkRunnerCore.cs
tests/BenchmarkDotNet.IntegrationTests/JobTests.cs

As [requested](https://github.com/PerfDotNet/BenchmarkDotNet/pull/286#issuecomment-255080585) by @adamsitnik 
Changelist:
- Jobs: WithXxx() extension methods added back, docs updated.
- Jobs, minor bug fixed: Id was cleared on explicit JobMode assignment + test for it (`Test03IdDoesNotFlow`).
- Jobs.Accuracy, typo: AnaylyzeLaunchVariance => AnalyzeLaunchVariance, docs updated.

Jobs: .With() extension methods.

---

src/BenchmarkDotNet.Core/Configs/ConfigParser.cs
src/BenchmarkDotNet.Core/Exporters/MarkdownExporter.cs
tests/BenchmarkDotNet.IntegrationTests/ValidatorsTest.cs

I made needed tweaks to MarkdownExporter so that it supports a little bit more customization. 
- Supports syntax that is used by JIRA (issue tracker) and Confluence (wiki)
- MarkdownExporter.Atlassian introduced
- Support separate markup for start and end of code blocks
- No table header and content separator can be optional
So Atlassian's format is:
{noformat}
anything
{noformat}
|| header 1 || header 2||
|  value 1 | value 2 |
If this is too vendor specific I'm fine with creating my own exporter too, would be just a copy paste of MarkdownExporter though.

Support Atlassian flavored wiki markup

---

src/BenchmarkDotNet.Core/Environments/BenchmarkEnvironmentInfo.cs
src/BenchmarkDotNet.Core/Environments/HostEnvironmentInfo.cs
src/BenchmarkDotNet.Core/Exporters/AsciiDocExporter.cs
src/BenchmarkDotNet.Core/Exporters/HtmlExporter.cs
src/BenchmarkDotNet.Core/Exporters/MarkdownExporter.cs
src/BenchmarkDotNet.Core/Portability/RuntimeInformation.cs
src/BenchmarkDotNet.Core/Reports/BenchmarkReportExtensions.cs
src/BenchmarkDotNet.Core/Reports/Summary.cs
src/BenchmarkDotNet.Core/Running/BenchmarkRunnerCore.cs
tests/BenchmarkDotNet.IntegrationTests/MultipleRuntimesTest.cs

Many people share benchmark results via simple screenshots which include information about the environment. So, it would be cool to keep the environment info as small as possible but still print all the necessary information. I made some changes; there is the result:
Before (12 lines):
```ini
BenchmarkDotNet=v0.10.0-develop
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-4702MQ CPU 2.20GHz, ProcessorCount=8
Frequency=2143476 Hz, Resolution=466.5319 ns, Timer=TSC
Host Runtime=Clr 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
GC=Concurrent Workstation
JitModules=clrjit-v4.6.1586.0
Job Runtime(s):
.NET Core 4.6.24628.01, Arch=64-bit  [RyuJIT]
Clr 4.0.30319.42000, Arch=64-bit RELEASE
Mono 4.6.2 (Visual Studio built mono), Arch=64-bit RELEASE
Clr 4.0.30319.42000, Arch=64-bit …
```

Improved information about job environments in summary

---

src/BenchmarkDotNet.Core/Exporters/MarkdownExporter.cs
src/BenchmarkDotNet.Core/Reports/SummaryTableExtensions.cs

Atlassian uses single '*'s around text to make it bold where GitHub uses two. This fixes to allow customization of format for bold text which Atlassian exporter then overrides.

fix bold markup for Atlassian exporter

---

docs/guide/Configs/Exporters.md
src/BenchmarkDotNet.Core/Exporters/CompositeExporter.cs
src/BenchmarkDotNet.Core/Exporters/ExporterBase.cs
src/BenchmarkDotNet.Core/Exporters/IExporter.cs
src/BenchmarkDotNet.Core/Exporters/RPlotExporter.cs
src/BenchmarkDotNet.Core/Running/BenchmarkRunnerCore.cs
tests/BenchmarkDotNet.IntegrationTests/BaselineScaledColumnTest.cs
tests/BenchmarkDotNet.Tests/ExporterDependancyTests.cs

Fixes #337.
RPlotExporter now logs an error if Rscript.exe isn't found and aborts. It may not be visible enough (is throwing an exception better?)

Better detection of Rscript in RPlotExporter

---

samples/BenchmarkDotNet.Samples/Intro/IntroBasic.cs

There was a typo in the desription.

Fixed typo in IntroBasic.cs

---

src/BenchmarkDotNet.Diagnostics.Windows/PmcDiagnoser.cs

I was alerted to this by @AmadeusW's most recent comment in #396

fix spelling error: misspredict => mispredict

---

src/BenchmarkDotNet.Toolchains.Roslyn/Builder.cs
src/BenchmarkDotNet.Toolchains.Roslyn/Generator.cs
src/BenchmarkDotNet.Toolchains.Roslyn/RoslynToolchain.cs

I need to extend the Roslyn Generator and Builder with custom build steps for our codebase, so I made the types public. Now they have the same visibility as the dotnet CLI generators and builders.
Also considered more general solutions that would allow API users to extend any toolchain without caring what it is:
1. make the GeneratorBase's protected hook methods public, so I can then decorate a GeneratorBase with my own hook implementations which would call the inner hooks and then do something extra
2. replace GeneratorBases's protected hook methods with public delegates, thus transforming inheritance to composition. API users could then start with some default compositions (roslyn / CLI) and add to the existing delegates.
In the end I went with this implementation since it's small, …

Make RoslynToolchain types public

---

src/BenchmarkDotNet.Core/Toolchains/DotNetCli/DotNetCliGenerator.cs
src/BenchmarkDotNet.Core/Toolchains/GeneratorBase.cs
src/BenchmarkDotNet.Toolchains.Roslyn/Generator.cs

`Cleanup` and `CopyRequiredFiles` did not receive the benchmark. Now they do. Unfortunately this is a breaking change, but I think it's worth it, since now all hook signatures are uniform (these were the only two hooks not receiving the benchmark object).
In my case, I am copying in different versions of a benchmark's dependencies, so I need to move the `BuildArtifactsDirectoryPath` outside of the benchmark's bindir, where the `BuildArtifactsDirectoryPath` defaults to for the Roslyn Generator, and then copy everything from the benchmark bindir there. This means that in my case, both `Cleanup` and `CopyRequiredFiles` hooks need to know where the benchmark type is located.

Propagate benchmark to hooks

---

src/BenchmarkDotNet.Core/Exporters/ExporterBase.cs
tests/BenchmarkDotNet.IntegrationTests/ExporterIOTests.cs

Fixes #414 
When a target file exists and is locked, currently BDN crashes and some of the data is lost.
This PR makes BDN export data under randomly-unique name to a temporary location and print a message to the log:
```
// * Export *
Could not overwrite file C:\src\BenchmarkDotNet\samples\BenchmarkDotNet.Samples\BenchmarkDotNet.Artifacts\results\Algo_BitCount-report.csv. Exporting to C:\Users\amadeusz\AppData\Local\Temp\uvkf5nub-Algo_BitCount-report.csv
C:\Users\amadeusz\AppData\Local\Temp\uvkf5nub-Algo_BitCount-report.csv
BenchmarkDotNet.Artifacts\results\Algo_BitCount-report-github.md
BenchmarkDotNet.Artifacts\results\Algo_BitCount-report.html
```
I'm not fully convinced that this sufficiently notifies user that the report in expected location is out of date, but I think this is …

Exports file to temporary location if target is locked

---

src/BenchmarkDotNet.Core/Columns/BaselineScaledColumn.cs
src/BenchmarkDotNet.Core/Columns/IColumn.cs
src/BenchmarkDotNet.Core/Columns/JobCharacteristicColumn.cs
src/BenchmarkDotNet.Core/Columns/ParamColumn.cs
src/BenchmarkDotNet.Core/Columns/RankColumn.cs
src/BenchmarkDotNet.Core/Columns/StatisticColumn.cs
src/BenchmarkDotNet.Core/Columns/TagColumn.cs
src/BenchmarkDotNet.Core/Columns/TargetMethodColumn.cs
src/BenchmarkDotNet.Core/Diagnosers/MemoryDiagnoser.cs
src/BenchmarkDotNet.Core/Exporters/MarkdownExporter.cs
src/BenchmarkDotNet.Core/Reports/SummaryTable.cs
src/BenchmarkDotNet.Diagnostics.Windows/MemoryDiagnoser.cs
src/BenchmarkDotNet.Diagnostics.Windows/PmcDiagnoser.cs
tests/BenchmarkDotNet.Tests/Reports/SummaryTableTests.cs

Now that #396 is complete, I've made a more complete pass at #398, to right-justify numeric columns in the `MarkdownExporter`, which would resolve #397.
1. `IColumn` has a new `IsNumeric` property, which is set (what I believe to be) appropriately in all its implementations.
1. `SummaryTableColumn` uses `IsNumeric` to set a new `Justify` property to either `Left` or `Right`
1. `MarkdownExporter` uses `Justify` to determine whether to use `:` or ` ` as the justification indicator

MarkdownExporter right-justifies numeric columns

---

tests/BenchmarkDotNet.IntegrationTests/BenchmarkDotNet.IntegrationTests.csproj
tests/BenchmarkDotNet.Tests/BenchmarkDotNet.Tests.csproj

Approval tests doesn't work with preview version — it can't get source path correctly.

Updated Microsoft.Net.Test.Sdk

---

src/BenchmarkDotNet.Core/Engines/Engine.cs

` Host.BeforeMainRun();` should run _before_ gc stats init as some host implementations (in-process, as example) may allocate during notification.
**UPD:** Allocation in InProcessHost is triggered by [WriteLine method](https://github.com/dotnet/BenchmarkDotNet/blob/610f3b72808bd76837facf6cd75acf70a30eb772/src/BenchmarkDotNet.Core/Toolchains/InProcess/InProcessHost.cs#L84):
```cs
case HostSignal.BeforeMainRun:
diagnoser?.BeforeMainRun(diagnoserActionParameters);
WriteLine(Engine.Signals.BeforeMainRun);
break;
```

Fix false allocations detection

---

src/BenchmarkDotNet.Core/Exporters/Json/JsonExporter.cs
src/BenchmarkDotNet.Core/Exporters/Json/JsonExporterBase.cs
src/BenchmarkDotNet.Core/Exporters/Json/SimpleJson.cs
tests/BenchmarkDotNet.Tests/Exporters/ApprovedFiles/ApprovalTest.Exporters.Invariant.approved.txt
tests/BenchmarkDotNet.Tests/Exporters/ApprovedFiles/ApprovalTest.Exporters.en-US.approved.txt
tests/BenchmarkDotNet.Tests/Exporters/ApprovedFiles/ApprovalTest.Exporters.ru-RU.approved.txt

This is a pull request for some minor bugs found from JsonExporter behavior while working on the [XmlExporter](https://github.com/dotnet/BenchmarkDotNet/issues/157). Here is some more context from the [comments](https://github.com/dotnet/BenchmarkDotNet/issues/157#issuecomment-300711076)
Fixes:
1. JsonExporter.BriefCompressed didn't correctly exclude the `Measurements`-property
2. JsonExport was showing incorrectly Lazy-type's `IsValueCreated` and `Value` properties in output instead just showing the actual value
3. SimpleJson uses `"\n"` as a line change, so I changed it to `Environment.NewLine` to match the rest of the approval test file line change style. Otherwise I couldn't get a `pass` from the exporter tests. I was getting `LF` line changes for the Json parts even though the …

Fix minor bugs in JsonExporter

---

src/BenchmarkDotNet.Core/Attributes/IterationSetupAttribute.cs

Wrong xml doc comment 
```c# 
/// <summary>
/// Marks method to be executed >after< each benchmark iteration. 
/// </summary> 
public class IterationSetupAttribute: Attribute  { }
```
It was copied from IterationCleanupAttribute, I guess.

Wrong xml doc comment

---

docs/guide/Guides/GettingStarted.md

These were pointing to the wrong location.
I'm not a web guy, so not sure if relative links are frowned upon, if so, tell me and I'll change them to whatever you want.

Fix links to Overview/FAQ

---

docs/guide/Advanced/SetupAndCleanup.md
src/BenchmarkDotNet.Core/Attributes/GlobalCleanupAttribute.cs
src/BenchmarkDotNet.Core/Attributes/GlobalSetupAttribute.cs
src/BenchmarkDotNet.Core/Attributes/IterationCleanupAttribute.cs
src/BenchmarkDotNet.Core/Attributes/IterationSetupAttribute.cs
src/BenchmarkDotNet.Core/Attributes/TargetedAttribute.cs
src/BenchmarkDotNet.Core/Running/BenchmarkConverter.cs
tests/BenchmarkDotNet.IntegrationTests/AllSetupAndCleanupTargetSpecificBenchmarkTest.cs
tests/BenchmarkDotNet.IntegrationTests/GlobalCleanupAttributeTargetTest.cs
tests/BenchmarkDotNet.IntegrationTests/GlobalSetupAttributeTargetTest.cs

This PR is for issue #469. It adds a Target property to the Setup and Cleanup attributes allowing setup methods to be targeted at specific benchmark methods.

Target Setup methods for specific Benchmarks

---

docs/guide/FAQ.md
src/BenchmarkDotNet.Core/Analysers/EnvironmentAnalyser.cs
src/BenchmarkDotNet.Core/Environments/HostEnvironmentInfo.cs
src/BenchmarkDotNet.Core/Portability/Antivirus.cs
src/BenchmarkDotNet.Core/Portability/RuntimeInformation.cs

According to the #364 
In case of invalid error code, analyzer prints warning about installed antivirus software and InProcessToolchain. 
Tested with Symantec and Windows Defender.

Warning about antivirus software after benchmark failure

---

tests/BenchmarkDotNet.Tests/Running/BenchmarkConverterTests.cs

#495 was fixed by @ipjohnson in 557246db by using `GetCustomAttributes` instead of `ReflectionExtensions::HasAttribute`. Version `v0.10.9` has this fix.
To be sure, I've added a unit test for expected behaviour

#495 - Unit test for reading attributes from the base class

---

src/BenchmarkDotNet.Core/Configs/DefaultConfig.cs
src/BenchmarkDotNet.Core/Running/BenchmarkConverter.cs
src/BenchmarkDotNet.Core/Validators/CompositeValidator.cs
src/BenchmarkDotNet.Core/Validators/SetupCleanupValidator.cs
tests/BenchmarkDotNet.IntegrationTests/GlobalCleanupAttributeTargetTest.cs
tests/BenchmarkDotNet.IntegrationTests/GlobalSetupAttributeTargetTest.cs
tests/BenchmarkDotNet.IntegrationTests/SetupCleanupValidatorTests.cs

this is to address issue #511 adds a validator for setup cleanup attributes as well as prefers targeted setup and cleanup methods over non targeted.

adding validator for setup cleanup attributes

---

docs/guide/Overview.md

Same as in `Diagnosers.md`.
Also maybe instead of having same information on two places, the `Overview.md` could just contain link to the `Diagnosers.md`, where all (more anyway) the detailed information is.

Fixed information about MemoryDiagnoser.

---

build.cake

Remove --no-build argument for dotnet test & pack commands.

---

src/BenchmarkDotNet.Core/Toolchains/InProcess/BenchmarkActionFactory_Base.cs

The correct type is `long` as indicated in the preceding comments.
This fixes a 32bit RyuJIT crash when running in-process tests: https://github.com/dotnet/coreclr/issues/13476

Fix type of local in EmitInvokeMultipleBody

---

samples/BenchmarkDotNet.Samples/BenchmarkDotNet.Samples.csproj
src/BenchmarkDotNet.Core/BenchmarkDotNet.Core.csproj
src/BenchmarkDotNet.Core/Toolchains/DotNetCli/NetCoreAppSettings.cs
src/BenchmarkDotNet.Diagnostics.Windows/BenchmarkDotNet.Diagnostics.Windows.csproj
src/BenchmarkDotNet.Toolchains.Roslyn/BenchmarkDotNet.Toolchains.Roslyn.csproj
src/BenchmarkDotNet/BenchmarkDotNet.csproj
tests/BenchmarkDotNet.IntegrationTests.ConfigPerAssembly/BenchmarkDotNet.IntegrationTests.ConfigPerAssembly.csproj
tests/BenchmarkDotNet.IntegrationTests.CustomPaths/BenchmarkDotNet.IntegrationTests.CustomPaths.csproj
tests/BenchmarkDotNet.IntegrationTests.DisabledOptimizations/BenchmarkDotNet.IntegrationTests.DisabledOptimizations.csproj
tests/BenchmarkDotNet.IntegrationTests.EnabledOptimizations/BenchmarkDotNet.IntegrationTests.EnabledOptimizations.csproj
tests/BenchmarkDotNet.IntegrationTests/BenchmarkDotNet.IntegrationTests.csproj
tests/BenchmarkDotNet.Tests/BenchmarkDotNet.Tests.csproj

Main changes:
- Remove PackageTargetFallback element (I guess that all required dependencies have updated TFM already).
- Replace TargetFramework with TargetFrameworkIdentifier to simplify conditions.
- Unify TargetFrameworks definition.
- Small fix of warning during compilation caused by typo with the XML tag. ([diff](https://github.com/dotnet/BenchmarkDotNet/commit/97a9b2b6bffe76956ca20061ff3a1b8e6e40a944#diff-0515d190f7048302fde6c5fd3f47ed23))
Please pay attention to [this change](https://github.com/dotnet/BenchmarkDotNet/compare/master...Ky7m:csproj-files-cleanup?expand=1#diff-b10f9fb46bba1c0e921ba10fed3c313eR7), was it a correct assumption?

Project files cleanup

---

src/BenchmarkDotNet.Core/Exporters/ExporterBase.cs
tests/BenchmarkDotNet.IntegrationTests/ExporterIOTests.cs

This PR fixes exporters to use fully qualified filenames instead of simple type names.
#529
- Changes how `ExporterBase` handles file naming:
- Uses `Type.FullName` instead of `Type.Name` as part of the filename
- Uses `Summary.Title` as the filename, if multiple benchmarks have been joined into a single `Summary`
- This convention follows the way `Summary.Title` is generated in [`BenchmarkRunnerCore r60`](https://github.com/dotnet/BenchmarkDotNet/blob/174c19dced6883c9f5d810303b7e969739e1cc2b/src/BenchmarkDotNet.Core/Running/BenchmarkRunnerCore.cs#L60)
- Adds two integration tests for the aforementioned features inside `BenchmarkDotNet.IntegrationTests.ExporterIOTests`:
1) Asserts the exporter uses fully qualified type name as part of the filename
2) Asserts joined summaries use …

Fix exporters to use fully qualified filenames

---

src/BenchmarkDotNet.Core/Configs/ConfigExtensions.cs
src/BenchmarkDotNet.Core/Configs/IConfig.cs
src/BenchmarkDotNet.Core/Configs/ReadOnlyConfig.cs
src/BenchmarkDotNet.Core/Running/BenchmarkConverter.cs
src/BenchmarkDotNet.Core/Running/BenchmarkRunInfo.cs
src/BenchmarkDotNet.Core/Running/BenchmarkRunnerCore.cs
src/BenchmarkDotNet.Core/Running/ClassicBenchmarkConverter.cs
src/BenchmarkDotNet.Core/Running/TypeParser.cs
src/BenchmarkDotNet.Core/Validators/ValidationParameters.cs
src/BenchmarkDotNet/Running/BenchmarkRunner.cs
src/BenchmarkDotNet/Running/BenchmarkSwitcher.cs
tests/BenchmarkDotNet.IntegrationTests/ExporterIOTests.cs
tests/BenchmarkDotNet.IntegrationTests/JitOptimizationsTests.cs
tests/BenchmarkDotNet.IntegrationTests/MemoryDiagnoserTests.cs
tests/BenchmarkDotNet.Tests/Mocks/MockFactory.cs
tests/BenchmarkDotNet.Tests/Reports/DefaultColumnProvidersTests.cs
tests/BenchmarkDotNet.Tests/Running/BenchmarkConverterTests.cs
tests/BenchmarkDotNet.Tests/Validators/ExecutionValidatorTests.cs

This commit tries to solve the issue of full config creation. 
Some parts of current code create full configs [three times during benchmark run](https://github.com/dotnet/BenchmarkDotNet/blob/5fe5647a158b41d0c2c949b6e04bca44ec5ff1d7/tests/BenchmarkDotNet.IntegrationTests/BenchmarkTestExecutor.cs#L64), others [do not create full config at all](https://github.com/dotnet/BenchmarkDotNet/blob/f2b9c0750fe236d9f4dc80571a58392d0ec7660d/src/BenchmarkDotNet/Running/BenchmarkSwitcher.cs#L77).
The fix is following:
* A new type, `BenchmarkRunInfo` is introduced. It keeps together benchmarks, a full config and a type for which the config was created. In case when there are multiple types in a single run (like with `join` switch) the current behavior is preserved: config is created using first type.
* …

Single point of full config creation

---

.travis.yml
build.cake
build.ps1
build.sh

- Add installation step to get the required .NET Core runtime to run backward compatibility tests (Windows, Linux).
- Clean up travis CI definition (since .NET Core 2.0 openssl prerequisite is not required).
- Replace CleanDirectories(delete and create) and  with DeleteDirectories(only delete) command.
- Updated Cake tool to version 0.23.0
- Fix prerequisite step that is required to run Tests tasks properly (e.g. build.ps1 -Target BackwardCompatibilityTests)

Update cakebuild scripts

---

src/BenchmarkDotNet.Core/Jobs/JobExtensions.cs

Technically renaming a parameter is a breaking change. I think in practice it's unlikely that any users of that API specified `buildConfiguraiton` using a named parameter, though.

Fix typo in WithCustomBuildConfiguration API

---

src/BenchmarkDotNet.Core/Environments/HostEnvironmentInfo.cs
tests/BenchmarkDotNet.Tests/Builders/HostEnvironmentInfoBuilder.cs
tests/BenchmarkDotNet.Tests/Environments/HostEnvironmentInfoTests.cs
tests/BenchmarkDotNet.Tests/Exporters/ApprovedFiles/ApprovalTest.Exporters.Invariant.approved.txt
tests/BenchmarkDotNet.Tests/Exporters/ApprovedFiles/ApprovalTest.Exporters.en-US.approved.txt
tests/BenchmarkDotNet.Tests/Exporters/ApprovedFiles/ApprovalTest.Exporters.ru-RU.approved.txt
tests/BenchmarkDotNet.Tests/Mocks/MockFactory.cs
tests/BenchmarkDotNet.Tests/Reports/DefaultColumnProvidersTests.cs
tests/BenchmarkDotNet.Tests/Reports/ScaledPrecisionTests.cs

With this change, information about VM hypervisor will be printed next to the OS version.
`BenchmarkDotNet=v0.10.x-mock, OS=Microsoft Windows NT 10.0.x.mock, VM=Hyper-V`
If hypevisor is not found, user will see default message `VM=Not detected`
This information is helpful, because usually people don't publish warnings from the benchmark.

Display VM name in summary section, fixes #574

---

build/pack.bat
src/BenchmarkDotNet.Disassembler.x64/Program.cs

Quick fix for issue reported later in https://github.com/dotnet/BenchmarkDotNet/issues/612
Had build issues also https://github.com/dotnet/BenchmarkDotNet/issues/614
Note this does simply ignores the case when more than one method found... didn't know how to add a test or debug this, but simply added this and now BDN at least doesn't crash when there is this issue.

Quick fix Disassembler.Program.GetMethod when more than one method found just return null

---

build.cake
build.ps1
build.sh

- Cake build 0.23.0 -> 0.24.0
- .NET Core SDK 2.0.3 -> 2.1.4
- .NET Core Runtime 1.1.4 -> 1.1.6 and 2.0.3 -> 2.0.5
Explicitly set a version of the installed .NET Core runtime to use to run netcoreapp1.1 tests. It closes #614.

Upgrade build tools

---

tests/BenchmarkDotNet.Tests/Portability/Cpu/ProcCpuInfoParserTests.cs
tests/BenchmarkDotNet.Tests/Portability/Cpu/SysctlCpuInfoParserTests.cs
tests/BenchmarkDotNet.Tests/Portability/Cpu/WmicCpuInfoParserTests.cs

Replace Assert.Equal(null,...) with Assert.Null(...) to simplify asserts and fix warnings from xunit analyzers.

Fix xunit warnings connected to usage of Assert.Equal() to check for Null

---

src/BenchmarkDotNet.Core/Order/DefaultOrderProvider.cs
src/BenchmarkDotNet.Core/Order/SummaryOrderPolicy.cs

Running 
```C#
[OrderProvider(SummaryOrderPolicy.Method, MethodOrderPolicy.Alphabetical)]
[DryJob]
public class IntroOrderAttr
{
[Params(1, 2, 3)]
public int X { get; set; }
[Benchmark]
public void Slow() => Thread.Sleep(X * 100);
[Benchmark]
public void Fast() => Thread.Sleep(X * 50);
}
```
Will produce:
| Method | X |      Mean | Error |
|------- |-- |----------:|------:|
|   **Fast** | **1** |  **50.02 ms** |    **NA** |
|   Fast | 2 | 100.37 ms |    NA |
|   Fast | 3 | 150.09 ms |    NA |
|   **Slow** | **1** | **100.57 ms** |    **NA** |
|   Slow | 2 | 200.80 ms |    NA |
|   Slow | 3 | 300.57 ms |    NA |

Allow sorting by the Method name in DefaultOrderProvider and OrderProviderAttribute

---

docs/guide/Advanced/Params.md

The old version shows fine on GitHub, but not on the website:
I *think* this change will fix it, but I haven't verified that.

Fixed code block formatting

---

src/BenchmarkDotNet.Core/Toolchains/CsProj/CsProjBuilder.cs
src/BenchmarkDotNet.Core/Toolchains/DotNetCli/DotNetCliBuilder.cs

Needed to provide a custom build command like so:
public class AspNetCoreProjBuilder : DotNetCliBuilder
{
protected override string GetBuildCommand(string frameworkMoniker, bool justTheProjectItself, string configuration)
=> $"publish --framework {frameworkMoniker} --configuration {configuration} --no-restore"
+ (justTheProjectItself ? " --no-dependencies" : string.Empty);
public AspNetCoreProjBuilder(string targetFrameworkMoniker, string customDotNetCliPath)
: base(targetFrameworkMoniker, customDotNetCliPath)
{
}
}
Hence "publish" as opposed to "build".
Have included the restore command in case someone would like to change that too as it makes sense to allow them to.

Allow restore and build command override

---

src/BenchmarkDotNet.Core/Characteristics/Characteristic.cs
src/BenchmarkDotNet.Core/Exporters/InstructionPointerExporter.cs
src/BenchmarkDotNet.Core/Exporters/RawDisassemblyExporter.cs
src/BenchmarkDotNet.Core/Extensions/CommonExtensions.cs
src/BenchmarkDotNet.Core/Horology/WindowsClock.cs
src/BenchmarkDotNet.Core/Portability/RuntimeInformation.cs
src/BenchmarkDotNet.Core/Toolchains/InProcess/BenchmarkActionFactory_Implementations.cs
tests/BenchmarkDotNet.IntegrationTests/CustomEngineTests.cs
tests/BenchmarkDotNet.IntegrationTests/ExporterIOTests.cs
tests/BenchmarkDotNet.IntegrationTests/ValuesReturnedByBenchmarkTest.cs
tests/BenchmarkDotNet.Tests/Engine/EngineResultStageTests.cs
tests/BenchmarkDotNet.Tests/Mocks/MockEngine.cs
tests/BenchmarkDotNet.Tests/Mocks/MockFactory.cs
tests/BenchmarkDotNet.Tests/Reports/DefaultColumnProvidersTests.cs
tests/BenchmarkDotNet.Tests/Reports/ScaledPrecisionTests.cs
tests/BenchmarkDotNet.Tests/Validators/ExecutionValidatorTests.cs

This was suggested by VS2017 Code Analysis.

Fix IDE0034: 'default' expression can be simplified

---

build.cake
build.ps1
build.sh

Update dotnet SDK (2.1.4 -> 2.1.101) and dotnet runtime (1.1.6 -> 1.1.7).
Enable FastTests run for netcoreapp1.1 on non-Windows environments.

Build system: Update dotnet SDK and dotnet runtime. Enable FastTests netcoreapp1.1 on non-Windows. 

---

src/BenchmarkDotNet/Helpers/FrameworkVersionHelper.cs
src/BenchmarkDotNet/Portability/RuntimeInformation.cs
src/BenchmarkDotNet/Toolchains/CsProj/CsProjClassicNetToolchain.cs

1) Add .NET Framework 4.7.2 version constant
2) Check for Reference Assemblies directory existence only for Toolchain select. This directory exists only when Developer Pack is installed. I think it would be better to display the version of framework (runtime, not sdk) in benchmarks output
3) Remove hardcoded Program Files directory path. It fix version detection on 32bit systems.
4) Refactor: move framework version detection from CsProjClassicNetToolchain, get rid of code clones

Improve .NET Framework version detection

---

docs/guide/Advanced/Arguments.md
docs/guide/Advanced/Params.md
src/BenchmarkDotNet/Helpers/SourceCodeHelper.cs
src/BenchmarkDotNet/Parameters/SmartParamBuilder.cs
src/BenchmarkDotNet/Running/BenchmarkConverter.cs
src/BenchmarkDotNet/Templates/BenchmarkProgram.txt
src/BenchmarkDotNet/Templates/BenchmarkType.txt
tests/BenchmarkDotNet.IntegrationTests/ArgumentsAttributeTests.cs

This change generates the right `IParam` for the users for any complex types returned by `[ArgumentsSource]` and `[ParamsSource]` 
I was tired of writing another IParam when I realized that I don't need to do that.
Idea: 
1. generate code which is going to call the `[Source]` getter/method 
2. it always returns `IEnumerable` so we can call `ToArray()` on it
3. use array indexer to get the argument
Examples and auto-generated code:
```cs
[ParamsSource(nameof(DictionaryAsParam))]
public Dictionary<int, string> DictionaryParamInstance;
public IEnumerable<object> DictionaryAsParam => new object[] { new Dictionary<int, string>() { { 1234, "it's an instance getter" } } };
generates:
Runnable_0 instance = new Runnable_0(); 
instance.DictionaryParamInstance= …
```

generate IParams for users in smart way

---

samples/BenchmarkDotNet.Samples/Other/GenericBenchmarks.cs
src/BenchmarkDotNet/Attributes/GenericBenchmarkAttribute.cs
src/BenchmarkDotNet/Extensions/ReflectionExtensions.cs
src/BenchmarkDotNet/Helpers/GenericBuilderHelper.cs
src/BenchmarkDotNet/Running/BenchmarkConverter.cs
src/BenchmarkDotNet/Running/TypeParser.cs
tests/BenchmarkDotNet.Tests/GenericBuilderTests.cs

Allows to define generic parameter of benchmark class via attribute.
Solves https://github.com/dotnet/BenchmarkDotNet/issues/745
Example:
```C#
[GenericBenchmark(typeof(int))]
[GenericBenchmark(typeof(char))]
public class GenericBenchmarks<T>
{
[Benchmark] public T Create() => Activator.CreateInstance<T>();
}
```

Generic Benchmark Attribute

---

src/BenchmarkDotNet/Order/DefaultOrderProvider.cs
src/BenchmarkDotNet/Order/SummaryOrderPolicy.cs

Fixes #720 
This is a pretty naive implementation of the `SummaryOrderPolicy.Defined`, just returning the incoming benchmarks without doing any sorting against the collection.
An alternative here would be to update the `BenchmarkComparer` to accept a `SummaryOrderPolicy` parameter, and to not do any comparison in that case, but I opted to not change the constructor of `BenchmarkComparer` in this case. Let me know if that's more in line with what you guys were thinking.

Add SummaryOrderPolicy.Defined to return benchmarks as instantiated

---

samples/BenchmarkDotNet.Samples/Intro/IntroInProcessWrongEnv.cs
src/BenchmarkDotNet/Diagnosers/WindowsDisassembler.cs
src/BenchmarkDotNet/Engines/Engine.cs
src/BenchmarkDotNet/Engines/EngineFactory.cs
src/BenchmarkDotNet/Engines/EngineParameters.cs
src/BenchmarkDotNet/Engines/IEngine.cs
src/BenchmarkDotNet/Engines/IEngineFactory.cs
src/BenchmarkDotNet/Engines/IterationMode.cs
src/BenchmarkDotNet/Engines/IterationModeExtensions.cs
src/BenchmarkDotNet/Extensions/ProcessExtensions.cs
src/BenchmarkDotNet/Portability/RuntimeInformation.cs
src/BenchmarkDotNet/Reports/Measurement.cs
src/BenchmarkDotNet/Templates/BenchmarkType.txt
src/BenchmarkDotNet/Toolchains/InProcess/InProcessRunner.cs
tests/BenchmarkDotNet.IntegrationTests/AllSetupAndCleanupTargetSpecificBenchmarkTest.cs
tests/BenchmarkDotNet.IntegrationTests/AllSetupAndCleanupTest.cs
tests/BenchmarkDotNet.IntegrationTests/CoreRtTests.cs
tests/BenchmarkDotNet.IntegrationTests/CustomEngineTests.cs
tests/BenchmarkDotNet.Tests/Engine/EngineFactoryTests.cs
tests/BenchmarkDotNet.Tests/Mocks/MockEngine.cs

Background: because of the default unroll factor = 16, every iteration was invoking benchmark at least 16 times. 
So if the benchmark took 1s, then:
1. jitting took 16x1s
2. warmup took 6 (MinIterationCount for EngineWarmupStage)  x 16 x 1s = 96 s
3. every target iteration was taking 16s
**Note:** In the default mode, this was described in our docs and was possible to change with custom config. We just did not have the time to fix it.
This PR introduces following changes:
1. EngineFactory is supposed to create an engine which is "ready to run", which means it's supposed to call `GlobalSetup`. (hence the method name change `Create` => `CreateReadyToRun`)
2. Engine implements `IDisposable`, which calls `GlobalCleanup`
3. When the strategy requires us to jit the code first (default mode) and …

don't execute long operations more than once per iteration

---

src/BenchmarkDotNet/Jobs/JobExtensions.cs
src/BenchmarkDotNet/Running/Benchmark.cs
src/BenchmarkDotNet/Running/BenchmarkConverter.cs
src/BenchmarkDotNet/Running/ClassicBenchmarkConverter.cs
tests/BenchmarkDotNet.Tests/CodeGeneratorTests.cs
tests/BenchmarkDotNet.Tests/Running/BenchmarkConverterTests.cs
tests/BenchmarkDotNet.Tests/Validators/CompilationValidatorTests.cs

fixes #730
Example:
```cs
public class FileSample
{
private readonly string filePath = Path.GetTempFileName();
[IterationSetup]
public void Create()
{
using (File.Create(filePath)) { }
}
[Benchmark]
public void Remove() => File.Delete(filePath);
}
```
/cc @stephentoub @nietras

if IterationSetup is provided, and InvocationCount and UnrollFactor are not, run benchmark once per iteration to avoid user confusion

---

src/BenchmarkDotNet/Engines/EngineFactory.cs
src/BenchmarkDotNet/Engines/EngineParameters.cs
src/BenchmarkDotNet/Engines/EnginePilotStage.cs
src/BenchmarkDotNet/Environments/EnvResolver.cs
src/BenchmarkDotNet/Templates/BenchmarkType.txt
src/BenchmarkDotNet/Toolchains/InProcess/InProcessRunner.cs
tests/BenchmarkDotNet.Tests/Engine/EngineFactoryTests.cs

I am currently working on porting CoreCLR to BenchmarkDotNet.
CoreCLR contains a lot of "benchmark game" benchmarks. These are long-running benchmarks.
After #760 the time it takes to run the benchmarks has greatly improved (ML.NET benchmarks from 20 to 2 minutes). However, I have found two extra scenarios for improvement:
1. The time to execute benchmark is slighly less than IterationTime. Let's say it's 0.4s when the IterationTime is 0.5s. In that case we invoke it 16 times per iteration (default unroll factor value). It's too much, we should invoke it just once.
2. The time to execute benchmark is just **few** times less than IterationTime. Let's say it's 0.1s when the IterationTime is 0.5s. In that case we invoke it 16 times per iteration (default unroll factor value). It's too much, …

have two main actions: with unroll and without, for no unroll icrease the step by 1 in pilot (not *2)

---

docs/template/styles/main.js

Preview: https://andreyakinshin.github.io/bdn-docs-wip/
Benefits:
* We can keep the old version of documentation on `https:/benchmarkdotnet.org/vNUMBER/`
* We can deploy documentation for the master branch on `https://benchmarkdotnet.org/`
* The implementation of this combobox is pretty simple and doesn't change the template.
Current problems:
* We still need a set of scripts for build & deploy, but it sounds solvable.

docs: multiversion combobox

---

src/BenchmarkDotNet/Loggers/SynchronousProcessOutputLoggerWithDiagnoser.cs
src/BenchmarkDotNet/Toolchains/Executor.cs

Potential fix for SynchronousProcessOutputLoggerWithDiagnoser infinite loop.
Related to my issue in #828 . Detected an abnormal streamread lock/loop. After some investigation, it looks to be potentially an infinite loop at the StreamReader.ReadLine(). It is capable of returning `string.Empty` and `null` as valid values.  The loop proceeds to continue when `string.IsNullOrEmpty`.
If EndOfStream is never achieved/reached, then a break or timeout will need to be added.
Ran the unit test that calls Execute and found that it froze during WaitForExit. I saw the comment should we add a Timeout and proceeded to do so.
Added timeout in Execute, detected freeze during UnitTest.
`ToolchainTests.CustomToolchainsAreSupported()`
* The infinite loop won't be fixed if the stream never ends.
* The …

Read StandardOutput in a smart way to avoid infinite loops

---

src/BenchmarkDotNet/Templates/CsProj.txt

Unless explicitly excluded, MSBuild will walk up the directory tree looking for
Directory.Build.props and Directory.Build.targets files. This is problematic for
one of the most common uses of Directory.Build.* files: redirecting output
directories. The rest of the benchmarking infrastructure has strong expectations
of where files will be produced, so things will often go wrong if they are redirected.

Exclude Directory.Build.props/targets from generated csproj files

---

tests/BenchmarkDotNet.IntegrationTests/GcModeTests.cs

In #221 there was a request to investigate why CanEnableServerGcMode failed on AppVeyor. I enabled this and ran a build on my own AppVeyor account to check if this still happened and it looks like this is fixed.
This PR enables the unit test and that would mean we could close issue #221.

Enabled GcModeTests.CanEnableServerGcMode

---

docs/articles/guides/choosing-run-strategy.md

The `RunStrategy` guide currently shows 2 identical `ColdStart` examples. I'm assuming we want to show `Monitoring` as the second one, instead.

Fix duplicate example in RunStrategy guide

---

src/BenchmarkDotNet/Templates/BuildPlots.R

Using a secure https connection should be preferred over http.
Download over http can be blocked by some corporate firewalls/proxy.

RPlotExporter: use https to download dependencies

---

tests/BenchmarkDotNet.IntegrationTests/GlobalCleanupAttributeTest.cs

This PR fixes corrects the tests because this test will also pass when
```C#
[Benchmark]
public void Benchmark()
{
Console.WriteLine(BenchmarkCalled);
}
```
is changed to
```C#
[Benchmark]
public void Benchmark()
{
//Console.WriteLine(BenchmarkCalled);
}
```
This is happening because there is a check if log contains `GlobalCleanupCalled` instead `BenchmarkCalled`. When the log only contains `GlobalCleanupCalled` this will happen:
```C#
string log = logger.GetLog();
Assert.Contains(GlobalCleanupCalled + System.Environment.NewLine, log);
// True
Assert.True(
log.IndexOf(GlobalCleanupCalled + System.Environment.NewLine) >
log.IndexOf(BenchmarkCalled + System.Environment.NewLine));
// 0 > -1 == true
```

Fix GlobalCleanupAttributeTest.GlobalCleanupMethodRunsTest

---

docs/articles/guides/console-args.md
src/BenchmarkDotNet/Configs/ConfigExtensions.cs
src/BenchmarkDotNet/Configs/ManualConfig.cs
src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs
src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Extensions/CommonExtensions.cs
src/BenchmarkDotNet/Jobs/JobExtensions.cs
src/BenchmarkDotNet/Jobs/MetaMode.cs
src/BenchmarkDotNet/Running/BenchmarkConverter.cs
src/BenchmarkDotNet/Running/BenchmarkSwitcher.cs
src/BenchmarkDotNet/Toolchains/CoreRt/Publisher.cs
src/BenchmarkDotNet/Toolchains/CsProj/CsProjCoreToolchain.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliGenerator.cs
tests/BenchmarkDotNet.Tests/ConfigParserTests.cs
tests/BenchmarkDotNet.Tests/GetRunnableJobsTests.cs
tests/BenchmarkDotNet.Tests/JobTests.cs

Recently I am using BDN on a large scale and in some scenarios I can't recompile the code, I need to be able to specify most of the settings from the command line. This PR adds most of the things to supported command line arguments.
The `--runtimes` or just `-r` allows you to run the benchmarks for selected Runtimes. Available options are: Mono, CoreRT, net46, net461, net462, net47, net471, net472, netcoreapp2.0, netcoreapp2.1, netcoreapp2.2, netcoreapp3.0.
Example: run the benchmarks for .NET 4.7.2 and .NET Core 2.1:
```log
dotnet run -c Release -- --runtimes net472 netcoreapp2.1
```
* `--launchCount` - how many times we should launch process with target benchmark. The default is 1.
* `--warmupCount` - how many warmup iterations should be performed. If you set it, the minWarmupCount and …

More command line args

---

src/BenchmarkDotNet/Configs/DefaultConfig.cs
src/BenchmarkDotNet/Loggers/LinqPadLogger.cs

Adds a logger that sends coloured output to LINQPad, fixing #447.
This new logger is enabled by default (in `DefaultConfig`) if the benchmark detects that it's being run under LINQPad. This makes it really easy to use, but I wasn't sure if this "magic" was appropriate; let me know if you'd like it to be done a different way.

Add LINQPad logging

---

src/BenchmarkDotNet/Loggers/LinqPadLogger.cs

From https://github.com/dotnet/BenchmarkDotNet/pull/903#issuecomment-429616305.
>  it would be nice to enable a monospaced font for `LinqPadLogger` by default.
This change specifies a variety of monospaced fonts commonly installed on Windows systems and suitable for summary chart output.

Use a monospaced font for LINQPad logging output

---

src/BenchmarkDotNet/Environments/ProcessorBrandStringHelper.cs
src/BenchmarkDotNet/Exporters/Json/JsonExporterBase.cs
src/BenchmarkDotNet/Exporters/Xml/SummaryDto.cs
src/BenchmarkDotNet/Portability/Cpu/CpuInfo.cs
src/BenchmarkDotNet/Portability/Cpu/CpuInfoFormatter.cs
tests/BenchmarkDotNet.Tests/Environments/ProcessorBrandStringTests.cs

I changed prettifier API to take whole CpuInfo so more logic can be used to determine whether we can safely remove the core count information. Hope that is OK, calling code also was a bit simplified because CpuInfo instance was already there.

Simplify AMD Ryzen CPU brand info

---

src/BenchmarkDotNet/Code/DeclarationsProvider.cs
src/BenchmarkDotNet/Validators/ExecutionValidatorBase.cs
tests/BenchmarkDotNet.IntegrationTests/AllSetupAndCleanupTest.cs
tests/BenchmarkDotNet.Tests/Validators/ExecutionValidatorTests.cs

This PR adds support for an `async` `GlobalSetup` as requested in #521. I am also planning to add support for `async` `GlobalCleanup.` I can add this to the same PR if that is preferred or I could open a separate PR for that.

Added support for async GlobalSetup.

---

src/BenchmarkDotNet/Validators/ExecutionValidatorBase.cs
tests/BenchmarkDotNet.Tests/Validators/ExecutionValidatorTests.cs

The `GlobalCleanup` attribute is not checked inside the `ExecutionValidatorBase` class. This patch adds support for that. 
The check inside the `Validate` method checks the count of the errors before and after executing `ExecuteBenchmarks`. And other option would be having `ExecuteBenchmarks` return a boolean but that would be a breaking change.

async GlobalCleanup support

---

src/BenchmarkDotNet/Jobs/JobExtensions.cs
src/BenchmarkDotNet/Jobs/NugetReference.cs
src/BenchmarkDotNet/Jobs/NugetReferenceList.cs
src/BenchmarkDotNet/Running/BenchmarkPartitioner.cs
tests/BenchmarkDotNet.Tests/JobTests.cs
tests/BenchmarkDotNet.Tests/Running/JobRuntimePropertiesComparerTests.cs

Fixes #931. Related to #922.
I tried to follow the local coding style, but my have failed. In particular, I saw no consistent method for calculating hashes. I'm happy to make any changes to conform.
The partitioner needs an implementation where package references are considered different if either name or version differ, so I amended `Equals` and `GetHashCode`. then `HashSet` wouldn't recognize duplicate packages, so I replaced it with a custom collection. I had it throw when the nuget reference's package name is a duplicate, since configuring different package versions of the same package for one job is an error, and it seems better to fail fast rather than run with perhaps an unintended version.
Thanks for considering this. Again, I'm happy to make any changes at all.

Partition benchmark run info based on added nuget packages

---

src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs
src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Extensions/ProcessExtensions.cs
src/BenchmarkDotNet/Toolchains/CoreRt/CoreRtToolchain.cs
src/BenchmarkDotNet/Toolchains/CoreRt/CoreRtToolchainBuilder.cs
src/BenchmarkDotNet/Toolchains/CoreRun/CoreRunPublisher.cs
src/BenchmarkDotNet/Toolchains/CoreRun/CoreRunToolchain.cs
src/BenchmarkDotNet/Toolchains/CsProj/CsProjClassicNetToolchain.cs
src/BenchmarkDotNet/Toolchains/CsProj/CsProjCoreToolchain.cs
src/BenchmarkDotNet/Toolchains/CustomCoreClr/CustomCoreClrToolchain.cs
src/BenchmarkDotNet/Toolchains/CustomCoreClr/CustomCoreClrToolchainBuilder.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/CustomDotNetCliToolchainBuilder.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliBuilder.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommand.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommandExecutor.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommandResult.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliPublisher.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/NetCoreAppSettings.cs
tests/BenchmarkDotNet.IntegrationTests/BuildTimeoutTests.cs
tests/BenchmarkDotNet.Tests/ConfigParserTests.cs

I need to run .NET Core 2.1 vs 2.2 for the official .NET Core preview release and I can't because I need a feature (the new disasm diff) from our CI which is red because of the hanging build #933 
This PR is very simple: add default timeout to the build commands we run with dotnet cli. If dotnet cli times out, kill the entire process tree. Moreover, if something fails: print all info we have.

Add Timeout for dotnet cli build commands to our toolchains

---

src/BenchmarkDotNet/Environments/BenchmarkEnvironmentInfo.cs
src/BenchmarkDotNet/Portability/RuntimeInformation.cs

For https://github.com/dotnet/BenchmarkDotNet/issues/788 . Uses environment variables, provided by runtime to detect version.

Detect correct version of .NET Core in Docker

---

docs/index.md

#787 changed the parameter name on job attributes, but the example code on the landing page still used the old name. I grepped the docs folder and this appears to be the only example that had this issue.

Fix example code (isBaseline -> baseline)

---

samples/BenchmarkDotNet.Samples/IntroTagColumn.cs

the sample read:
```csharp
Add(new TagColumn("Foo or Bar", name => name.Substring(0, 3)));
```
instead of
```csharp
Add(new TagColumn("Kind", name => name.Substring(0, 3)));
```

Fixed typo in IntroTagColumn sample

---

src/BenchmarkDotNet/Attributes/DisassemblyDiagnoserAttribute.cs

In last PR #937 I forgot to add `printDiff` to `DisassemblyDiagnoserAttribute`.

Add printDiff in DisassemblyDiagnoserAttribute

---

tests/BenchmarkDotNet.Tests/Mathematics/StatisticalTesting/MannWhitneyTests.cs

@AndreyAkinshin I caught parameters that reproduce error. 
Exception is throwing from this line: https://github.com/dotnet/BenchmarkDotNet/blob/05cc8d15ef88e382bbb1827d766d7275c3e42abd/src/BenchmarkDotNet/Mathematics/StatisticalTesting/MannWhitneyTest.cs#L23-L24
when `i=15, j=1, k=1` and `w = new long[20, 15, 266]`

Add failing test for #948

---

docs/articles/guides/console-args.md
docs/articles/samples/IntroStopOnFirstError.md
docs/articles/samples/toc.yml
samples/BenchmarkDotNet.Samples/IntroStopOnFirstError.cs
src/BenchmarkDotNet/Attributes/StopOnFirstErrorAttribute.cs
src/BenchmarkDotNet/Configs/ConfigExtensions.cs
src/BenchmarkDotNet/Configs/DebugConfig.cs
src/BenchmarkDotNet/Configs/DefaultConfig.cs
src/BenchmarkDotNet/Configs/IConfig.cs
src/BenchmarkDotNet/Configs/ManualConfig.cs
src/BenchmarkDotNet/Configs/ReadOnlyConfig.cs
src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs
src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Reports/BenchmarkReport.cs
src/BenchmarkDotNet/Running/BenchmarkRunner.cs
tests/BenchmarkDotNet.IntegrationTests/ExporterIOTests.cs
tests/BenchmarkDotNet.Tests/Mocks/MockFactory.cs
tests/BenchmarkDotNet.Tests/Reports/DefaultColumnProvidersTests.cs
tests/BenchmarkDotNet.Tests/Reports/RatioPrecisionTests.cs

Fixes for #939
I'm not sure all of my changes, especially adding property and changing constructor in BenchmarkReport.

Add option to stop running when the first benchmark fails

---

src/BenchmarkDotNet/BenchmarkDotNet.csproj
src/BenchmarkDotNet/Diagnosers/DiagnosersLoader.cs

Use DependencyContext to load diagnostics assembly

---

appveyor.yml
build.cake
build.ps1
build.sh
build/build-and-pack.cmd
build/common.props
build/pack.bat
docs/_changelog/ChangeLogBuilder/.gitignore

Fix for #967 
* I had to update .net to 2.1.500 version because this version support new snupkg symbol packages. There is information about it https://blog.nuget.org/20181116/Improved-debugging-experience-with-the-NuGet-org-symbol-server-and-snupkg.html 
* I had to change PackageLicenseUrl because it is deprecated. Without this change I got message: 
```
warning NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead.
```
More information: https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg. 
* I had to use 'ArgumentCustomization' in build.cake because Cake doesn't support new snupkg symbol packages. https://github.com/cake-build/cake/issues/2362 
Now after build project:
```
build.bat -Target Pack
```
You will see:
I don't know …

Support Nuget symbol server

---

azure-pipelines.Ubuntu.yml
azure-pipelines.Windows.yml
azure-pipelines.macOS.yml

It seems to me that we have to define branch for master builds explicitly.

Disable batch mode and explicitly enable build trigger for master branch

---

docs/articles/samples/IntroParamsAllValues.md
samples/BenchmarkDotNet.Samples/IntroParamsAllValues.cs
src/BenchmarkDotNet/Parameters/ParameterComparer.cs

This addresses some of the feedback from #660 that Enums should default to ordering by value instead of by name.

sort enum parameters by value instead of name

---

src/BenchmarkDotNet/Running/BenchmarkRunner.cs
src/BenchmarkDotNet/Toolchains/CsProj/CsProjCoreToolchain.cs

When running a .NET Core benchmark job from LINQPad, you will encounter an error like the following:
> // Generate Exception: Unable to find LINQPadQuery in C:\Program Files (x86)\LINQPad5 and its subfolders. Most probably the name of output exe is different than the name of the .(c/f)sproj
As noted in [this comment](https://github.com/dotnet/BenchmarkDotNet/issues/975#issuecomment-443297722), this is because to run a .NET Core job requires the benchmarks to be in .NET Core (LINQPad does not provide this).
This change detects that a .NET Core benchmark job was run from LINQPad and provides an additional error message stating this fact.
Detection of LINQPad is the same implementation used in [`JitOptimizationsValidator`](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDot …

Detect .NET Core benchmark failures from LINQPad

---

src/BenchmarkDotNet/Validators/CompilationValidator.cs
tests/BenchmarkDotNet.IntegrationTests/InProcessTest.cs
tests/BenchmarkDotNet.IntegrationTests/ParamsAttributeStaticTest.cs
tests/BenchmarkDotNet.Tests/Validators/CompilationValidatorTests.cs

For https://github.com/dotnet/BenchmarkDotNet/issues/983

Give a warning when the [Benchmark] method is static

---

src/BenchmarkDotNet/Columns/DefaultColumnProvider.cs
src/BenchmarkDotNet/Columns/MetricColumn.cs
src/BenchmarkDotNet/Reports/BenchmarkReport.cs
tests/BenchmarkDotNet.Tests/Reports/SummaryTests.cs

Fixes NRE after unchecked access to `BenchmarkReport.Metrics` property.

Fix NRE in MetricColumn (#986)

---

docs/articles/guides/nuget.md

`BenchmarkDotNet` `Doesn't have any dependencies` - is no longer true.

Remove obsolete info from the docs

---

docs/articles/overview.md

The opening sample in https://benchmarkdotnet.org/articles/overview.html does not specify `MemoryDiagnoser`, so `Allocated` column in benchmark results must not be present (at least on the latest 0.11.3).
Also the output (now?) contains `Error` column.

Synchronize benchmark output with the code in docs

---

docs/articles/contributing/documentation.md

The sample markdown as it was - was broken and misleading.
I guess it is https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html?tabs=tabid-1%2Ctabid-a#note-warningtipimportant to blame for abstract self-contradictory samples with copy-paste artifacts.

Rephrase Notes section and fix markdown

---

src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Templates/CsProj.txt
src/BenchmarkDotNet/Toolchains/CoreRt/CoreRtToolchain.cs
src/BenchmarkDotNet/Toolchains/CoreRt/CoreRtToolchainBuilder.cs
src/BenchmarkDotNet/Toolchains/CoreRt/Generator.cs
src/BenchmarkDotNet/Toolchains/CustomCoreClr/CustomCoreClrToolchainBuilder.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/CustomDotNetCliToolchainBuilder.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommand.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliGenerator.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/NetCoreAppSettings.cs

1. port #854 PR to CoreRT toolchain as well so the output file path doe not get overwritten by .props files
2. take the current TFM as default, not netcoreapp2.1 for CoreRT
3. if we fail to do the standard publish, let's try with --no-build
4. CoreRT toolchain must respect `--packages`

CoreRT toolchain update

---

src/BenchmarkDotNet/Running/BenchmarkRunner.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommand.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommandResult.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/NetCoreAppSettings.cs
src/BenchmarkDotNet/Toolchains/Results/BuildResult.cs
src/BenchmarkDotNet/Toolchains/Roslyn/Builder.cs
tests/BenchmarkDotNet.IntegrationTests/BuildTimeoutTests.cs
tests/BenchmarkDotNet.IntegrationTests/ProcessorArchitectureTest.cs
tests/BenchmarkDotNet.Tests/Reports/SummaryTests.cs

Some of our tests are still unstable which can be very confusing for new contributors (#1006).
In this PR I am going to improve the error logging, reproduce the faiulres and fix them.
/cc @CodeTherapist

Improve error logging to diagnose unstable tests

---

docs/articles/configs/jobs.md

Changed `TargetCount` attribute name to `IterationCount` in Configs.Jobs section of documentation as this attribute was renamed in class `BenchmarkDotNet.Jobs.RunMode` in this commit dotnet@5e6e331

Changed TargetCount to IterationCount in docs

---

samples/BenchmarkDotNet.Samples/Properties/launchSettings.json
src/BenchmarkDotNet/Toolchains/CoreRun/CoreRunGenerator.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommand.cs

After this changes `benchmarks_ci.py` works good.:
```ini
[2019/01/11 14:16:15][INFO] $ pushd "C:\Work\performance\src\benchmarks\micro"
[2019/01/11 14:16:15][INFO] $ dotnet run --project MicroBenchmarks.csproj --configuration Release --framework netcoreapp3.0 --no-restore --no-build -- --coreRun C:\Work\corefx\artifacts\bin\testhost\netcoreapp-Windows_NT-Debug-x64\shared\Microsoft.NETCore.App\9.9.9\CoreRun.exe --filter *.Perf_Dictionary.* --join --packages C:\Work\performance\artifacts\packages --runtimes netcoreapp3.0
[2019/01/11 14:16:24][INFO] // Validating benchmarks:
[2019/01/11 14:16:25][INFO] // ***** BenchmarkRunner: Start   *****
[2019/01/11 14:16:25][INFO] // ***** Building 1 exe(s) in Parallel: Start   *****
[2019/01/11 14:16:29][INFO] // start dotnet restore --packages …
```

Improve restore, build and publish projects - Fix for #1002

---

BenchmarkDotNet.sln
docs/articles/guides/global-dotnet-tool.md
docs/articles/guides/how-to-run.md
docs/articles/guides/nuget.md
docs/articles/guides/toc.yml
src/BenchmarkDotNet.Tool/BenchmarkDotNet.Tool.csproj
src/BenchmarkDotNet.Tool/Program.cs
src/BenchmarkDotNet.Tool/Properties/launchSettings.json

BenchmarkDotNet as global tool

---

build/common.props
docs/articles/contributing/debugging.md
docs/articles/contributing/development.md
docs/articles/faq.md
samples/BenchmarkDotNet.Samples.FSharp/BenchmarkDotNet.Samples.FSharp.fsproj
samples/BenchmarkDotNet.Samples/BenchmarkDotNet.Samples.csproj
src/BenchmarkDotNet.Diagnostics.Windows/BenchmarkDotNet.Diagnostics.Windows.csproj
src/BenchmarkDotNet/BenchmarkDotNet.csproj
tests/BenchmarkDotNet.IntegrationTests.ConfigPerAssembly/BenchmarkDotNet.IntegrationTests.ConfigPerAssembly.csproj
tests/BenchmarkDotNet.IntegrationTests.CustomPaths/BenchmarkDotNet.IntegrationTests.CustomPaths.csproj
tests/BenchmarkDotNet.IntegrationTests.DisabledOptimizations/BenchmarkDotNet.IntegrationTests.DisabledOptimizations.csproj
tests/BenchmarkDotNet.IntegrationTests.EnabledOptimizations/BenchmarkDotNet.IntegrationTests.EnabledOptimizations.csproj
tests/BenchmarkDotNet.IntegrationTests.FSharp/BenchmarkDotNet.IntegrationTests.FSharp.fsproj
tests/BenchmarkDotNet.IntegrationTests.ManualRunning/BenchmarkDotNet.IntegrationTests.ManualRunning.csproj
tests/BenchmarkDotNet.IntegrationTests.VisualBasic/BenchmarkDotNet.IntegrationTests.VisualBasic.vbproj
tests/BenchmarkDotNet.IntegrationTests/BenchmarkDotNet.IntegrationTests.csproj
tests/BenchmarkDotNet.Tests/BenchmarkDotNet.Tests.csproj

- Added support for CommandLineParser 2.3.1 Net Standard 2.0 library -- this is for future work on support Xamarin releases 
- Now use NET461 for the libraries, this is required for .Net Standard 2.0 support.
- Now use $(TargetFramework.StartsWith('net4')) in our csproj files, this allows upgrades to .NET 4 based libraries without the pain currently required.

Use .NET Standard 2.0 CommandLineParser, Update to net461 for NS2.0 support

---

src/BenchmarkDotNet/Exporters/PrettyGithubMarkdownDiffDisassemblyExporter.cs

Currently when you generate diff two disassembly, the result file looks like:
**Diff for LoweringTESTtoBT method between:**
.NET Core 2.0.9 (CoreCLR 4.6.26614.01, CoreFX 4.6.26614.01), 64bit RyuJIT
.NET Core 2.1.6 (CoreCLR 4.6.27019.06, CoreFX 4.6.27019.05), 64bit RyuJIT
```diff
xor     edx,edx
jmp     M00_L01
M00_L00:
-       mov     ecx,eax
-       and     ecx,1Fh
-       mov     edx,1
-       shl     edx,cl
-       mov     ecx,dword ptr [rsp+4]
-       test    edx,ecx
+       bt      ecx,eax
mov     edx,ecx
-       jne     M00_L01
+       jb      M00_L01
inc     eax
M00_L01:
lea     ecx,[rdx+1]
-       mov     dword ptr [rsp+4],ecx
cmp     edx,989680h
jl      M00_L00
-       add     rsp,8
-; Total bytes of code 49
+       ret
+; Total bytes of code 27
```
After changes: 
**Diff for …

Improve diff disassembly

---

samples/BenchmarkDotNet.Samples/IntroInProcessWrongEnv.cs
src/BenchmarkDotNet/Properties/AssemblyInfo.cs

Sample application shouldn't use internal class. Instead of `RuntimeInformation.Is64BitPlatform()` I've used `Environment.Is64BitProcess`
https://github.com/dotnet/corefx/blob/94e9d02ad70b2224d012ac4a66eaa1f913ae4f29/src/Common/src/CoreLib/System/Environment.cs#L111
Now global tool works well.

Remove InternalsVisibleTo for Samples application

---

src/BenchmarkDotNet/Toolchains/Roslyn/Builder.cs
tests/BenchmarkDotNet.IntegrationTests/RoslynToolchainTest.cs

Fixes culture-related errors mentioned in #1039.
Roslyn uses LocalizableString undercover; all methods that return human-readable messages should be called with specific culture passed as an arg.
I've added CanExecuteWithNonDefaultUiCulture test to prevent possible regressions.

Use invariant culture for csc messages

---

src/BenchmarkDotNet/Toolchains/CoreRt/Generator.cs

See https://github.com/dotnet/corert/pull/6955#discussion_r254766270.
BenchmakeDotNet reflects on this attribute here:
https://github.com/dotnet/BenchmarkDotNet/blob/a76f438a81e3e0235a2e9b1249a5280038189689/src/BenchmarkDotNet/Extensions/AssemblyExtensions.cs#L28-L38

Allow reflecting on DebuggableAttribute on CoreRT

---

src/BenchmarkDotNet/Diagnosers/MemoryDiagnoser.cs

Current titles of the MemoryDiagnoser columns contain too many chars.
Because of that, the summary table is too wide when MemoryDiagnoser is
enabled. Since we have a legend for each column below the summary table,
we can use shorter titles for these columns.

Shortify MemoryDiagnoser column titles

---

src/BenchmarkDotNet/Templates/CsProj.txt

If there is a CodeAnalysisRuleSet set by the Directory.Build.Props, the project will fail if there isn't a subsequent one in the benchmarks project folder.
This just forces them to be turned off since we don't care about the analysis.

Make it so that the code analysis settings are disabled.

---

docs/articles/samples/IntroInProcess.md
samples/BenchmarkDotNet.Samples/IntroInProcess.cs
samples/BenchmarkDotNet.Samples/IntroInProcessWrongEnv.cs
src/BenchmarkDotNet.Diagnostics.Windows/HardwareCounters.cs
src/BenchmarkDotNet/Jobs/InfrastructureMode.cs

Today I saw some people using `[InProcessAttribute]` and I realized that it's still using the old one.
I think that we should switch by default to the new one.

make InProcessEmitToolchain the default one

---

src/BenchmarkDotNet/Toolchains/CsProj/CsProjGenerator.cs

Fix for #1068 - Copy value of `CopyLocalLockFileAssemblies` to `BenchmarkDotNet.Autogenerated.csproj`

Fix #1068 - Copy value of CopyLocalLockFileAssemblies

---

src/BenchmarkDotNet/Toolchains/CoreRt/CoreRtToolchainBuilder.cs

CoreRT no longer publishes to MyGet.
See dotnet/corert#7268.

Consume CoreRT from the new NuGet feed

---

src/BenchmarkDotNet/Analysers/EnvironmentAnalyser.cs
src/BenchmarkDotNet/Configs/DebugConfig.cs
src/BenchmarkDotNet/Diagnosers/DisassemblyDiagnoser.cs
src/BenchmarkDotNet/Toolchains/InProcess.NoEmit/BenchmarkAction.cs
src/BenchmarkDotNet/Toolchains/InProcess.NoEmit/BenchmarkActionFactory.cs
src/BenchmarkDotNet/Toolchains/InProcess.NoEmit/BenchmarkActionFactory_Base.cs
src/BenchmarkDotNet/Toolchains/InProcess.NoEmit/BenchmarkActionFactory_Dummy.cs
src/BenchmarkDotNet/Toolchains/InProcess.NoEmit/BenchmarkActionFactory_Implementations.cs
src/BenchmarkDotNet/Toolchains/InProcess.NoEmit/InProcessNoEmitBuilder.cs
src/BenchmarkDotNet/Toolchains/InProcess.NoEmit/InProcessNoEmitExecutor.cs
src/BenchmarkDotNet/Toolchains/InProcess.NoEmit/InProcessNoEmitGenerator.cs
src/BenchmarkDotNet/Toolchains/InProcess.NoEmit/InProcessNoEmitRunner.cs
src/BenchmarkDotNet/Toolchains/InProcess.NoEmit/InProcessNoEmitToolchain.cs
src/BenchmarkDotNet/Toolchains/InProcess/BenchmarkActionCodegen.cs
src/BenchmarkDotNet/Toolchains/InProcess/InProcessHost.cs
src/BenchmarkDotNet/Toolchains/InProcess/InProcessValidator.cs
src/BenchmarkDotNet/Validators/ReturnValueValidator.cs

As suggested [here](https://github.com/dotnet/BenchmarkDotNet/pull/1093#issuecomment-470422460).
I've added a copy of `InProcessToolchain`, `InProcessNoEmitToolchain`, that has no emit-related code.
Origin classes marked obsolete, tests and usages updated.
Any suggestions are welcome, I'm not going to insist on this implementation.

+ InProcessNoEmitToolchain (obsoletes the InProcessToolchain)

---

src/BenchmarkDotNet/Engines/GcStats.cs
tests/BenchmarkDotNet.IntegrationTests/MemoryDiagnoserTests.cs
tests/BenchmarkDotNet.Tests/XUnit/TheoryNetCore30Attribute.cs

preview6 of .NET Core 3.0 exposes a new method that allows to get the number of allocated bytes for all threads. By using it we can fix #1153 and #723
Sample:
```cs
public class MultiThreadedAllocation
{
public const int Size = 1_000_000;
public const int ThreadsCount = 10;
private Thread[] threads;
[IterationSetup]
public void SetupIteration()
{
threads = Enumerable.Range(0, ThreadsCount)
.Select(_ => new Thread(() => GC.KeepAlive(new byte[Size])))
.ToArray();
}
[Benchmark]
public void Allocate()
{
foreach (var thread in threads)
{
thread.Start();
thread.Join();
}
}
}
```
```cmd
dotnet run -c Release -f netcoreapp2.1 --filter *MultiThreadedAllocation* --runtimes netcoreapp3.0 netcoreapp2.1 net461 --memory 
```
|   Method | Runtime |     Toolchain |     Gen 0 |     Gen 1 |     Gen 2 | …

Use new .NET Core 3.0 API to get the total number of allocated bytes for all threads

---

src/BenchmarkDotNet/Analysers/BaselineCustomAnalyzer.cs
src/BenchmarkDotNet/Columns/BaselineCustomColumn.cs
src/BenchmarkDotNet/Configs/DefaultConfig.cs

Fixes #600 
Sample Message:
```
// * Warnings *
BaselineCustomAnalyzer
Summary -> A question mark '?' symbol indicates that it was not possible to compute 
the (Ratio, RatioSD) column(s) because the baseline value is too close to zero.
```
Please note that the PR also adds the analyzer to the default configuration.

Warn the user when benchmark baseline value is too close to zero and the columns derived from BaselineCustomColumn cannot be computed

---

docs/index.md

Hey, index.md had extra bracket in the Main features -> Relative performance. So when you navigate to that link, it tried to open `https://benchmarkdotnet.org/(http://benchmarkdotnet.org/Advanced/Baseline.htm)`. I've removed extra bracket so now link navigates to correct place

Updated index.md and fixed Relative performance url

---

src/BenchmarkDotNet/Loggers/StreamLogger.cs

The `append` arg should be passed to the `StreamWriter` .ctor.

Invalid arg passing in StreamLogger constructor

---

docs/articles/configs/diagnosers.md

Added information about what a Gen X means. Right now the definition is ambiguous of whether it is the number of objects in that generation or the number of collections in that generation

Added information about what a Gen X column means

---

src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliExecutor.cs
src/BenchmarkDotNet/Toolchains/Executor.cs
src/BenchmarkDotNet/Toolchains/InProcess.Emit/InProcessEmitExecutor.cs
src/BenchmarkDotNet/Toolchains/InProcess.NoEmit/InProcessNoEmitExecutor.cs
src/BenchmarkDotNet/Toolchains/InProcess/InProcessExecutor.cs
src/BenchmarkDotNet/Toolchains/Results/ExecuteResult.cs
tests/BenchmarkDotNet.IntegrationTests/ToolchainTest.cs
tests/BenchmarkDotNet.Tests/Mocks/MockFactory.cs
tests/BenchmarkDotNet.Tests/Reports/DefaultColumnProvidersTests.cs
tests/BenchmarkDotNet.Tests/Reports/RatioPrecisionTests.cs

@tannergooding has pointed the fact that BDN does not print the benchmark process ID and it's hard to figure the PID when using some machine-wide profiler with BDN
this PR extends the logged output with one line. Example:
```log
// Benchmark Process 9868 has exited with code 0
```

print benchmark process id to the output (better profiler user story)

---

docs/articles/overview.md

This PR changes the default `hello world` of BenchmarkDotNet in a way, that it enables to adding new benchmarks without diving into the selection mechanism. IMO it's make it easier to just copy it and add new benchmarks without thinking why they are not run.

Easier introduction of new benchmarks

---

src/BenchmarkDotNet/Portability/RuntimeInformation.cs

@AndreyAkinshin I've recently been running a lot of benchmarks for x64, x86, ARM and ARM64. The reported results always contained "64bit" or "32bit" which does not tell if it's ARM or not. I think that we should use full architecture name.
Before:
```log
BenchmarkDotNet=v0.11.5.20190727-develop, OS=Windows 10.0.18362
Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 physical cores
[Host]     : .NET Framework 4.8 (4.8.3815.0), 64bit RyuJIT
DefaultJob : .NET Framework 4.8 (4.8.3815.0), 64bit RyuJIT
```
After:
```log
BenchmarkDotNet=v0.11.5.20190727-develop, OS=Windows 10.0.18362
Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 physical cores
[Host]     : .NET Framework 4.8 (4.8.3815.0), X64 RyuJIT
DefaultJob : .NET Framework 4.8 (4.8.3815.0), X64 RyuJIT
```

print full architecture name

---

docs/articles/configs/diagnosers.md
docs/articles/samples/IntroNativeMemory.md
samples/BenchmarkDotNet.Samples/IntroNativeMemory.cs
src/BenchmarkDotNet.Diagnostics.Windows/Configs/NativeMemoryProfilerAttribute.cs
src/BenchmarkDotNet.Diagnostics.Windows/EtwProfilerConfig.cs
src/BenchmarkDotNet.Diagnostics.Windows/NativeMemoryDiagnoser.cs
src/BenchmarkDotNet.Diagnostics.Windows/NativeMemoryProfiler.cs
src/BenchmarkDotNet/Diagnosers/DiagnosersLoader.cs

In this PR I support command line argument:
```
--profiler NativeMemory
```
@adamsitnik I wonder if `NativeMemoryDiagnoser` shouldn't be named `NativeMemoryProfiler`?
We have `MemoryDiagnoser` but there is also `EtwProfiler` and `ConcurrencyVisualizerProfiler`.

Support of --profiler NativeMemory command line argument

---

docs/articles/configs/diagnosers.md

In this PR I added links to:
- @adamsitnik's blog about `ETW Profiler` and `Concurrency Visualizer Profiler`
- my blok about `Native Memory Profiler`. You can read it here: [blog post](https://wojciechnagorski.com/2019/08/analyzing-native-memory-allocation-with-benchmarkdotnet/)

Add links to blogs.

---

docs/articles/contributing/disassembler.md
docs/articles/features/etwprofiler.md
docs/articles/samples/IntroArguments.md
docs/articles/samples/IntroEncoding.md
docs/articles/samples/IntroInProcess.md
docs/articles/samples/IntroStopOnFirstError.md

Mostly due to my editor settings it also removed trailing whitespace. If that's not desired let me know and I'll add them.

Documentation: Fix some typos in the documentation

---

src/BenchmarkDotNet/Parameters/ParameterDefinition.cs
src/BenchmarkDotNet/Parameters/SmartParamBuilder.cs
src/BenchmarkDotNet/Running/BenchmarkConverter.cs
tests/BenchmarkDotNet.IntegrationTests/ArgumentsTests.cs
tests/BenchmarkDotNet.Tests/ParameterComparerTests.cs
tests/BenchmarkDotNet.Tests/ParameterInstanceTests.cs

This is a fix for bug reported by @stephentoub in https://github.com/dotnet/corefx/pull/40377

Support IEnumerable as benchmark argument

---

src/BenchmarkDotNet/Toolchains/InProcess.Emit.Implementation/Runnable/RunnableReuse.cs
tests/BenchmarkDotNet.IntegrationTests/InProcessEmitTest.cs

Reported by @filipnavara in https://github.com/dotnet/performance/issues/788

Fix iteration cleanup bug

---

src/BenchmarkDotNet.Diagnostics.Windows/HardwareCounters.cs
src/BenchmarkDotNet.Diagnostics.Windows/Tracing/NativeMemoryLogParser.cs
src/BenchmarkDotNet/Configs/ImmutableConfigBuilder.cs
tests/BenchmarkDotNet.IntegrationTests/ImmutableConfigTests.cs

Some improvements for #1235. 
This is just nicer error handling. Unfortunately, this will not correct the mistake itself.

The null ArtifactsPath value causes exception for all EtwProfiler

---

src/BenchmarkDotNet/Columns/MetricColumn.cs
src/BenchmarkDotNet/Exporters/Csv/CsvExporter.cs
src/BenchmarkDotNet/Reports/SummaryStyle.cs
tests/BenchmarkDotNet.Tests/Mocks/MockFactory.cs
tests/BenchmarkDotNet.Tests/Reports/DefaultColumnProvidersTests.cs
tests/BenchmarkDotNet.Tests/Reports/FakeMetricDescriptor.cs
tests/BenchmarkDotNet.Tests/Reports/SummaryTableTests.cs
tests/BenchmarkDotNet.Tests/SummaryStyleTests.cs

In order to use generated csv reports for publishing results to TSDB (e.g. Influx) we need to change the way '0' are visualized. By default they are dashed '-'. The goal of this PR is to change it for CsvExporter, but leave it as it is for the other exporters (console/GH/HTML).
Addresses #1168

Amend SummaryStyle to support visualization of '0' in reports

---

docs/articles/configs/exporters.md
src/BenchmarkDotNet/Exporters/RPlotExporter.cs

Hello,
As long with #1220, few Docs changes has been proposed in #1221,
This one try to "extends" `RScript` detection if `R_HOME` value is wrong, so that it also look in the `PATH`
This branch is on purpose on top of the existing #1221 so that is would be easy to directly pick it up

Enhance rscript location

---

src/BenchmarkDotNet.Diagnostics.Windows/Sessions.cs
src/BenchmarkDotNet/Code/CodeGenerator.cs
src/BenchmarkDotNet/Extensions/ReflectionExtensions.cs
src/BenchmarkDotNet/Loggers/LinqPadLogger.cs
src/BenchmarkDotNet/Running/BenchmarkPartitioner.cs
src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs
src/BenchmarkDotNet/Toolchains/CsProj/CsProjCoreToolchain.cs
src/BenchmarkDotNet/Toolchains/ToolchainExtensions.cs
src/BenchmarkDotNet/Validators/CompilationValidator.cs

@AndreyAkinshin @albahari I don't have LINQPad 6 license so I was unable to test it properly.
Can any of you test BenchmarkDotNet version `0.11.5.1170` from our CI feed when [this](https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/builds/27384769) build finishes? (should be in half an hour from now)
```xml
<packageSources>
<add key="bdn-ci" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />
</packageSources
```
fixes #1241

LINQPad 6 support using InProcessEmitToolchain

---

docs/articles/configs/configoptions.md
docs/articles/configs/toc.yml
docs/articles/guides/console-args.md
src/BenchmarkDotNet/Configs/ConfigOptions.cs
src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs
src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs
tests/BenchmarkDotNet.IntegrationTests/BenchmarkSwitcherTest.cs
tests/BenchmarkDotNet.Tests/ConfigParserTests.cs
tests/BenchmarkDotNet.Tests/Configs/ConfigOptionsTests.cs

The proposed solution emphasizes:
* Minimal change
* Keeping the current behavior
* No IO when the log file is disabled (perf+)
* Simple to use for the users (relies on well-known API, `IConfig.With(ConfigOptions.DisableLogFile);`)
Documentation will be done, as soon the proposed solution is accepted and final.
Closes #198

Add possibility to disable the log file

---

build.ps1
build.sh

closes #1254 
required for #1253

Update Build Tools to use .NET Core SDK to 3.0.100

---

src/BenchmarkDotNet/Configs/ImmutableConfigBuilder.cs

Explicitly specify `default` types in `if` condition expressions.
This _might_ be a Roslyn bug.
Temp fix for #1267

Fix compilation error with post v3.3.1 Roslyn

---

src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs
src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Parameters/ParameterDefinitions.cs
src/BenchmarkDotNet/Parameters/ParameterInstance.cs
src/BenchmarkDotNet/Parameters/SmartParamBuilder.cs
src/BenchmarkDotNet/Reports/SummaryStyle.cs
src/BenchmarkDotNet/Running/BenchmarkConverter.cs
tests/BenchmarkDotNet.Tests/CharacteristicPresenterTests.cs
tests/BenchmarkDotNet.Tests/ConfigParserTests.cs
tests/BenchmarkDotNet.Tests/ParameterComparerTests.cs
tests/BenchmarkDotNet.Tests/ParameterInstanceTests.cs

Recently I've been working on improving the performance of `StartsWith` and `EndsWith` on Linux. I am interested in some test cases, not all possible permutations so I am using a `[ParamsSource]` combined with `ValueTuple`.
Example:
```cs
public static IEnumerable<(CultureInfo CultureInfo, CompareOptions CompareOptions, bool highChars)> GetOptions()
{
// Ordinal and OrdinalIgnoreCase use single execution path for all cultures, so we test it only for "en-US"
// without enforcing highChars - the execution path would be the same
yield return (new CultureInfo("en-US"), CompareOptions.Ordinal, false);
yield return (new CultureInfo("en-US"), CompareOptions.OrdinalIgnoreCase, false);
yield return (new CultureInfo("en-US"), CompareOptions.None, false); // no high chars = fast path (managed code …
```

make it possible to configure MaxParamterColumnWidth

---

docs/_changelog/header/v0.12.0.md

In #1208 we renamed `NativeMemoryDiagnoser` to `NativeMemoryProfiler`.

Improve documentation for version 0.12.0

---

src/BenchmarkDotNet/Engines/GcStats.cs
src/BenchmarkDotNet/Engines/RunResults.cs
src/BenchmarkDotNet/Engines/ThreadingStats.cs
src/BenchmarkDotNet/Toolchains/InProcess.Emit/InProcessEmitExecutor.cs
src/BenchmarkDotNet/Toolchains/InProcess.NoEmit/InProcessNoEmitExecutor.cs
src/BenchmarkDotNet/Toolchains/InProcess/InProcessExecutor.cs

Fix for #1280 
Without stats:
```
cd samples\BenchmarkDotNet.Samples\bin\Release\net461
.\BenchmarkDotNet.Samples.exe --filter IntroBasic
```
With stats (with `-m` option):
```
cd samples\BenchmarkDotNet.Samples\bin\Release\net461
.\BenchmarkDotNet.Samples.exe --filter IntroBasic -m
```

Print GC and threading stats only if needed

---

docs/index.md

Update link of " official benchmarking guide" to use the new recommended link. The link should now point to doc on dotnet/performance repo.
cc @adamsitnik

Update link of " official benchmarking guide" to use the new recommended link

---

templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.FSharp/_BenchmarkProjectName_.fsproj

```
mkdir benchmark
cd benchmark
dotnet new benchmark -lang f# -c true --console-app
dotnet run
```
>...\benchmark\Benchmarks.fs(7,28): error FS0039: The type 'BenchmarkConfig' is not defined in 'BenchmarkDotNet.Configs'. Maybe you want one of the following:↔   BenchmarkLogicalGroupRule [C:\git\local\benches\benches.fsproj]
>...benchmark\Benchmarks.fs(7,10): error FS0267: This is not a valid constant expression or custom attribute value [C:\git\local\benches\benches.fsproj]
>
>The build failed. Fix the build errors and run again.
Since `BenckmarConfig` is used within `(BenchmarkName).fs` it should precede it

Fix project file order

---

src/BenchmarkDotNet/Toolchains/CsProj/CsProjGenerator.cs

This allow use UserSecrets which implicitly obtained from entry point assembly.
Just copy UserSecretsId from benchmark project if available
Closes #1305

Copy UserSecrets from benchmark project

---

src/BenchmarkDotNet/Mathematics/ChangePointDetection/EdPeltChangePointDetector.cs

Turned the jagged array into a flat one.
Changed 2 lists into a pair of arrays and a single length counter. Got rid of Add, RemoveRange, and Clear calls by doing so.
I considered stackalloc Span<T>, but the arrays can get quite large and not fit the stack.
In GetSegmentCost I pulled `tau2 - tau1` out of the loop and also made indexing simpler.
In GetPartialSums I removed some array accesses by using a variable to store the previous value, and saved some writes by calculating the value before assigning it.
Added curly braces
Is there a reason it's not a static class?

EdPeltChangePointDetector improvements

---

src/BenchmarkDotNet/Code/EnumParam.cs
src/BenchmarkDotNet/Running/BenchmarkConverter.cs
tests/BenchmarkDotNet.IntegrationTests.FSharp/Program.fs
tests/BenchmarkDotNet.IntegrationTests/FSharpTests.cs
tests/BenchmarkDotNet.IntegrationTests/ReferencesTests.cs

Closes #1262 
I've added new type for enum params, that preserves type information for erasured F# enums in attributes. There is obvious code duplication, but that's for reason to keep code changes small and local. We can remove it after F# compiler is fixed. ;)
See also:
https://github.com/dotnet/fsharp/issues/995
Happy #hacktoberfest!

Add EnumParam preserving type information

---

src/BenchmarkDotNet/Environments/HostEnvironmentInfo.cs

fixes for https://twitter.com/andrey_akinshin/status/1204651253399216128 
Example:
```
// * Summary *
BenchmarkDotNet=v0.12.0.20191213-develop, OS=debian 9, Running in a container
Intel Core i7-4770 CPU 3.40GHz (Haswell), 1 CPU, 2 logical and 2 physical cores
.NET Core SDK=2.1.607
[Host] : .NET Core 2.1.14 (CoreCLR 4.6.28207.04, CoreFX 4.6.28208.01), X64 RyuJIT
```

Show information about docker

---

src/BenchmarkDotNet/Reports/Summary.cs

This prevents confusing ordering in the file system and should be more in line with the sane date format chosen for the file name as well.

Use 24-hour time in joined summary file name

---

src/BenchmarkDotNet/Code/CodeGenerator.cs
tests/BenchmarkDotNet.IntegrationTests/AsyncBenchmarksTests.cs

CodeGenerator does not correctly generate workload-code for non-generic `ValueTask` returning method. As a result, the runner does not await `ValueTask`, and the result is incorrect. This PR fixes it.
```csharp
[SimpleJob]
public class TestBenchmark
{
[Benchmark]
public async ValueTask ValueTask_NonGeneric()
{
await Task.Delay(100);
}
[Benchmark]
public async Task Task_NonGeneric()
{
await Task.Delay(100);
}
[Benchmark]
public async ValueTask<int> ValueTask_OfInt32()
{
await Task.Delay(100);
return 0;
}
[Benchmark]
public async Task<int> Task_OfInt32()
{
await Task.Delay(100);
return 0;
}
}
```
```
BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18363
Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.1.101
[Host]     : .NET Core 3.1.1 (CoreCLR …
```

Await non-generic ValueTask returning method

---

src/BenchmarkDotNet/Code/ArrayParam.cs
src/BenchmarkDotNet/Parameters/SmartParamBuilder.cs

Fixes #1348.
It would be better to unify display text generation across all parameters, but cannot find a good place for a common method. Maybe a base class?

Fixed display text for array parameters and arguments

---

src/BenchmarkDotNet/Columns/ParamColumn.cs
src/BenchmarkDotNet/Parameters/ParameterInstance.cs

Closes #1369
I added `ParameterInstance.ToDisplayText(CultureInfo cultureInfo)` that handles `IFormattable` values. To preserve backwards-compatibility I also added a parameter-less overload that uses current culture, which is how it works right now.
Before the change (notice the commas instead of periods for values of parameter `B`):
After the change (notice there are no commas):

Use CultureInfo when formatting parameter values

---

src/BenchmarkDotNet/Exporters/RPlotExporter.cs

Changed process stdout/stderr buffer to external buffer.
10x10 old code results artifact count: 504
10x10 old code run + Rscript runtime: Infinite (Cancelled after 9m6.493s)
10x10 new code results artifact count: 1,014
10x10 new code run + Rscript runtime: 6m47.011s
results artifact count = files in "netcoreapp2.2/BenchmarkDotNet.Artifacts/results/*"
```csharp
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Jobs;
using BenchmarkDotNet.Reports;
using BenchmarkDotNet.Running;
using System;
namespace BenchmarkDotNetTest
{
class Program
{
static void Main(string[] args)
{
Console.WriteLine("Started");
Summary summary = BenchmarkRunner.Run<Wide>();
Console.WriteLine("Ended");
}
}
[SimpleJob(RuntimeMoniker.NetCoreApp22, launchCount: 1, warmupCount: 0, targetCount: 1, invocationCount: …
```

fixes #641

---

src/BenchmarkDotNet.Diagnostics.Windows/BenchmarkDotNet.Diagnostics.Windows.csproj

Due to some strange bug in old version of `TraceEvent` library, the `TailCall` diagnoser reports... inlining events for .NET Core 2.2+ (2.1 works fine). Not tail call events. 
For details you can go to: https://github.com/dotnet/runtime/issues/2191

update TraceEvent to 2.0.49 to get TailCalls working again

---

src/BenchmarkDotNet.Diagnostics.Windows/JitDiagnoser.cs

While working on https://github.com/dotnet/runtime/issues/2191 I got surprised by how long it takes to get the benchmark results.
It turned out that so far we were always running the benchmarks one more time if `Inlining` or `TailCall` diagnosers were enabled. We simply don't need to do that, the overhead of these two diagnosers is very, very small (we just sign up for 3 events).
```cmd
git clone https://github.com/dotnet/BenchmarkDotNet/
cd BenchmarkDotNet
cd samples
cd BenchmarkDotNet.Samples.FSharp
dotnet run -c Release -f net461 --filter TailCallDetector
```
Before:
| Method | facRank |      Mean |     Error |    StdDev |
|------- |-------- |----------:|----------:|----------:|
|   test |       7 |  9.460 ns | 0.2158 ns | 0.2310 ns |
|  test1 |       7 |  4.758 ns | 0.0824 ns | 0.0731 …

don't require the JitDiagnosers (TailCall & Inlining) to run benchmarks once again just to gather JIT info, the overhead is very small

---

src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs
src/BenchmarkDotNet/Validators/ConfigCompatibilityValidator.cs
tests/BenchmarkDotNet.Tests/Validators/ConfigCompatibilityValidatorTests.cs

Closes #1238 
It's not complete solution, just a starting point for discussion. I've reviewed @AndreyAkinshin repro and existing validation system. It seems for now Validators work only per benchmark type and closely coupled with their configs.
I propose the following solution:
1. introduce special Validator for config compatibility checks; we need to call it from `BenchmarkRunnerClean.Validate` method in case of `JoinSummary` option enabled;
1. join all benchmark cases and Validators from all types;
1. merge all configs into one;
1. validate the cases with Validators and the config; we will get additional checks for free, e.g. `BaselineValidator`;
@adamsitnik @AndreyAkinshin What do you think? I'm looking forward to your response.
Thanks and happy #hacktoberfest!

Configuration compatibility validation

---

azure-pipelines.macOS.yml

On March 23, 2020, vs2015-win2012r2, macOS-10.13, win1803 vmImages
will be removed. We should use macOS-10.14 to make our CI green again.
See https://aka.ms/blocked-hosted-agent for more information.

Bump macOS Azure Pipeline vmImage to 10.14, fix #1396

---

src/BenchmarkDotNet/Templates/CsProj.txt

Fix compilation error MSB4086 with version 0.12.1 if the `LangVersion` MSBuild property is already set to one of the keywords such as `preview`, `latest` and `latestMajor` ([docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/langversion-compiler-option)).
Otherwise MSBuild complains that it cannot perform a numeric comparison and compilation fails.
Example compilation error from a project with `<LangVersion>latest</LangVersion>` specified in a `Directory.Build.props` file in the repository root:
```
\BenchmarkDotNet.Autogenerated.csproj(20,18): error MSB4086: A numeric comparison was attempted on "$(LangVersion)" that evaluates to "latest" instead of a number, in condition "'$(LangVersion)' == '' Or '$(LangVersion)' < '7.3'".
```
Open to alternative …

Fix MSB4086 if LangVersion is a keyword

---

src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommandExecutor.cs

Fix typo in log message when command times out.

Fix typo in log message

---

samples/BenchmarkDotNet.Samples.Forms/MainPage.xaml

These are just general UI improvements to the sample. Which is still admittedly, a bit ugly.
* Use a `Padding` for the entire page on iOS, to accomodate an iOS device/simulator with the "notch".
* Use a valid mono-spaced font on iOS: `Courier`
* Use `Margin` instead of `Padding` on the "Run" button. The wrong property was used before.

[samples] UI tweaks to Xamarin samples

---

src/BenchmarkDotNet/Environments/OsBrandStringHelper.cs
tests/BenchmarkDotNet.Tests/Environments/OsBrandStringTests.cs

Fix wrongly reported os brand string for Windows 10 1909

---

src/BenchmarkDotNet/Toolchains/CsProj/CsProjGenerator.cs
tests/BenchmarkDotNet.Tests/CsProjGeneratorTests.cs

Hello,
We are using a test framework called Gauge (https://gauge.org/) to do regression testing and wanted to roll performance tests in with those regression tests.  In our case we want to use Gauge steps to control and kick off different BenchmarkDotNet benchmarks (so we have a common top level framework for all of our regression tests).  
One issue we have run into is Gauge loads assemblies via streams, this causes the assembly location to be an empty string when running against net core/net standard.  More information about the assembly location being empty in this case can be found in Microsoft's documentation (https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.location).
This PR provides a way to handle that scenario by providing a default location for the project …

Handle assemblies loaded via a stream

---

src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs

Fixes #1456 
Quoting from https://github.com/dotnet/BenchmarkDotNet/issues/1456#issuecomment-628513994
> If it's annoying to you that the Debug build is throwing so many exceptions please feel free to send a PR with some defensive checks that avoid parsing blank lines.
It does annoy me! :)
This PR filters out blank lines before attempting to parse.

Don't try to parse blank lines

---

src/BenchmarkDotNet.Disassembler.x64/BenchmarkDotNet.Disassembler.x64.csproj
src/BenchmarkDotNet.Disassembler.x86/BenchmarkDotNet.Disassembler.x86.csproj
src/BenchmarkDotNet/BenchmarkDotNet.csproj

An unfortunate turn of events led me to a place where I need to perform this sort of upgrade to avoid crashing on Linux with a disassembler.
As far as I could tell, the windows version is completely unaffected / not crashing with the previous version.

Upgrades ClrMD to a version that will not crash on Linux :(

---

docs/articles/features/disassembler.md

It looks like after #1332 docs about [Disassembler](https://benchmarkdotnet.org/articles/features/disassembler.html) settings are out of date. PR unifies them with the code.

Updated Disassembler docs

---

docs/articles/features/disassembler.md
src/BenchmarkDotNet/Attributes/DisassemblyDiagnoserAttribute.cs
src/BenchmarkDotNet/Disassemblers/DisassemblyDiagnoserConfig.cs

Improved doc description of the ExportDiff property

---

src/BenchmarkDotNet/Exporters/FullNameProvider.cs
src/BenchmarkDotNet/Parameters/SmartParamBuilder.cs
tests/BenchmarkDotNet.IntegrationTests/ArgumentsTests.cs

I wanted to reproduce https://github.com/dotnet/BenchmarkDotNet/issues/1476 but I've failed.
Instead, I've found few cases where a combination of params and args did not work well with params source that was returning `IEnumerable<object[]>` so I've fixed that

ParamsSource returning IEnumerable<object[]> fixes

---

src/BenchmarkDotNet/Reports/Measurement.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommandExecutor.cs

This seems to fix issue: https://github.com/dotnet/BenchmarkDotNet/issues/1480

set process output encoding to utf8 so BenchmarkRunnerDotNet works in self hosted VSTS agent.

---

src/BenchmarkDotNet/Portability/RuntimeInformation.cs
src/BenchmarkDotNet/Templates/CsProj.txt
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommand.cs
tests/BenchmarkDotNet.IntegrationTests/CustomBuildConfigurationTests.cs

enforce Optimizations when using Custom Build Configurations

---

src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs
src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
tests/BenchmarkDotNet.Tests/ConfigParserTests.cs

While reviewing [ClrMd benchmarks](https://github.com/microsoft/clrmd/tree/master/src/Benchmarks) I've realized that we don't support specyfing platform via console line args

allow the users to specify Platform via console args

---

src/BenchmarkDotNet.Disassembler.x64/BenchmarkDotNet.Disassembler.x64.csproj
src/BenchmarkDotNet.Disassembler.x86/BenchmarkDotNet.Disassembler.x86.csproj
src/BenchmarkDotNet/BenchmarkDotNet.csproj
src/BenchmarkDotNet/Disassemblers/DisassemblyDiagnoser.cs
src/BenchmarkDotNet/Disassemblers/DisassemblyDiagnoserConfig.cs
src/BenchmarkDotNet/Disassemblers/Exporters/GithubMarkdownDisassemblyExporter.cs
src/BenchmarkDotNet/Disassemblers/InstructionFormatter.cs
src/BenchmarkDotNet/Exporters/InstructionPointerExporter.cs

Iced released a 1.8.0 some hours ago, see https://github.com/0xd4d/iced/releases/tag/v1.8.0 for changes.

Update to latest Iced

---

samples/BenchmarkDotNet.Samples.Forms/MainPage.xaml.cs
src/BenchmarkDotNet/Configs/DebugConfig.cs
src/BenchmarkDotNet/Configs/DefaultConfig.cs
src/BenchmarkDotNet/Environments/Runtimes/MonoRuntime.cs
src/BenchmarkDotNet/Portability/RuntimeInformation.cs
src/BenchmarkDotNet/Toolchains/ToolchainExtensions.cs

Using `DebugInProcessConfig` results in an error on Android:
System.IO.IOException: Read-only file system
at System.IO.FileSystem.CreateDirectory (System.String fullPath) [0x00187] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs:317
at System.IO.Directory.CreateDirectory (System.String path) [0x0002c] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.IO.FileSystem/src/System/IO/Directory.cs:40
at BenchmarkDotNet.Extensions.CommonExtensions.CreateIfNotExists (System.String directoryPath) [0x0000e] in C:\src\BenchmarkDotNet\src\BenchmarkDotNet\Extensions\CommonExtensions.cs:71
at BenchmarkDotNet.Running.BenchmarkRunnerClean.GetRootArtifactsFolde …

[xamarin] fix for DebugConfig and read-only file system

---

samples/BenchmarkDotNet.Samples/IntroTailcall.cs

There's a tiny error in the following code
private static long FactorialWithTailing(int depth)
=> FactorialWithTailing(1, depth); // The first parameter value must be 'depth - 1' instead of just '1'

FactorialWithTailing - incorrect implementation

---

src/BenchmarkDotNet.Annotations/Jobs/RuntimeMoniker.cs
src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Environments/HostEnvironmentInfo.cs
src/BenchmarkDotNet/Environments/Runtimes/CoreRtRuntime.cs
src/BenchmarkDotNet/Environments/Runtimes/CoreRuntime.cs
src/BenchmarkDotNet/Extensions/RuntimeMonikerExtensions.cs
src/BenchmarkDotNet/Portability/RuntimeInformation.cs
src/BenchmarkDotNet/Toolchains/CoreRt/CoreRtToolchain.cs
src/BenchmarkDotNet/Toolchains/CsProj/CsProjCoreToolchain.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/MsBuildErrorMapper.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/NetCoreAppSettings.cs
src/BenchmarkDotNet/Toolchains/ToolchainExtensions.cs
tests/BenchmarkDotNet.Tests/ConfigParserTests.cs
tests/BenchmarkDotNet.Tests/RuntimeVersionDetectionTests.cs

This PR:
- adds `net6.0` support
- renames `netcoreapp5.0` to `net5.0` (I personally don't like it but well we have to live with that)
- simplifies displayed version numbers for .NET 5.0+
Before:
```ini
BenchmarkDotNet=v0.12.1.20200824-develop, OS=Windows 10.0.18363.959 (1909/November2019Update/19H2)
Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=5.0.100-preview.8.20362.3
[Host]     : .NET Core 2.1.21 (CoreCLR 4.6.29130.01, CoreFX 4.6.29130.02), X64 RyuJIT
Job-ILZMMP : .NET Core 5.0.0 (CoreCLR 5.0.20.36102, CoreFX 5.0.20.36102), X64 RyuJIT
```
After:
```ini
BenchmarkDotNet=v0.12.1.20200824-develop, OS=Windows 10.0.18363.959 (1909/November2019Update/19H2)
Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET Core …
```

add .NET 6.0 support, rename .NET Core 5.0 to .NET 5.0

---

src/BenchmarkDotNet.Diagnostics.Windows/Tracing/NativeMemoryLogParser.cs
src/BenchmarkDotNet.Diagnostics.Windows/Tracing/TraceLogParser.cs
src/BenchmarkDotNet/Extensions/CommonExtensions.cs
src/BenchmarkDotNet/Portability/RuntimeInformation.cs

This PR is NOT a solution for https://twitter.com/lukaszpyrzyk/status/1295003260990959621, it's just a small improvement.
It just removes etlx files after run ETW Profiler and NativeMemoryProfiler.

Remove unneeded files after etw profiler

---

docs/articles/guides/console-args.md

`--maxWidth` console argument is described under [Command-line tool](https://benchmarkdotnet.org/articles/guides/tool.html) page, but is missing under page [How to use console arguments](https://benchmarkdotnet.org/articles/guides/console-args.html).

Documentation: add --maxWidth description

---

src/BenchmarkDotNet/ConsoleArguments/CorrectionsSuggester.cs

`allBenchmarkNames` is a `HashSet` so the order of the added elements should not matter.

Simplify code: remove sort before adding to HashSet

---

src/BenchmarkDotNet/Extensions/ProcessExtensions.cs

`corerun` does not know how to load GC configuration from `runtimeconfig.json` files.
The only portable way is to set the `COMPlus_gcServer` environment variable when spawning the `corerun` child process.
Closes #1495

Enable supported GcMode characteristics with corerun

---

src/BenchmarkDotNet/Columns/MetricColumn.cs

The number format is not used when formatting a size value in a MetricColumn

Respect size number format in MetricColumn

---

src/BenchmarkDotNet.Diagnostics.Windows/Tracing/TraceLogParser.cs

fixes #1546
`overhead / (double) overheadIterations.Length` was giving us a `double.NaN` and we were ending up reporting `NaN` as hardware counter for long-running benchmarks
cc @AndyAyersMs @kunalspathak
@AndreyAkinshin could you please take a look?

hardware counters: don't try to exclude non-existing overhead for long running benchmarks

---

src/BenchmarkDotNet.Diagnostics.Windows/BenchmarkDotNet.Diagnostics.Windows.csproj
src/BenchmarkDotNet/BenchmarkDotNet.csproj
src/BenchmarkDotNet/Helpers/ArtifactFileNameHelper.cs
tests/BenchmarkDotNet.Tests/ArtifactFileNameHelperTests.cs

Fixes #1544 
to tell the long story short, if Long Paths support is enabled on Windows, the ETW might still throw errors.
The fix is to always use 260 characters limit

Fix Merge operation failed for EtwProfiler

---

src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Environments/Runtimes/CoreRuntime.cs
src/BenchmarkDotNet/Toolchains/CsProj/CsProjCoreToolchain.cs
src/BenchmarkDotNet/Toolchains/CsProj/CsProjGenerator.cs
src/BenchmarkDotNet/Toolchains/ToolchainExtensions.cs
tests/BenchmarkDotNet.Tests/ConfigParserTests.cs
tests/BenchmarkDotNet.Tests/Running/JobRuntimePropertiesComparerTests.cs
tests/BenchmarkDotNet.Tests/RuntimeVersionDetectionTests.cs

.NET 5.0 introduced platform-specific TFMs like `net5.0-windows`. Since .NET 5.0 **RC2** it's now possible to recognize that given .NET Core app is running as such (https://github.com/dotnet/sdk/pull/13672)
```xml
<TargetFramework>net5.0-windows</TargetFramework>
```
Fixes #1535
I think that it's the last missing feature related to full .NET 5.0 support

Add support for Platform-specific TFMs introduced in .NET 5

---

src/BenchmarkDotNet/Helpers/ConsoleExitHandler.cs
src/BenchmarkDotNet/Loggers/SynchronousProcessOutputLoggerWithDiagnoser.cs
src/BenchmarkDotNet/Parameters/ParameterInstance.cs
src/BenchmarkDotNet/Parameters/ParameterInstances.cs
src/BenchmarkDotNet/Parameters/SmartParamBuilder.cs
src/BenchmarkDotNet/Running/BenchmarkCase.cs
src/BenchmarkDotNet/Running/BenchmarkRunInfo.cs
src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliExecutor.cs
src/BenchmarkDotNet/Toolchains/Executor.cs
tests/BenchmarkDotNet.IntegrationTests/ArgumentsTests.cs

#1383 contained a very unusual bug: benchmarks were executing fine, but hanging after printing "// AfterAll" to the console
I've dug into that and found out (https://github.com/dotnet/BenchmarkDotNet/issues/1383#issuecomment-714563319) that there is a locking finalizer which prevents the process from exiting which was a thing until it got fixed in .NET 5 (https://github.com/dotnet/runtime/issues/314)
The problem was that disposing the finalizable instance in the `[GlobalCleanup]` was not enough: https://github.com/JohnMasen/VirusSimulator/blob/432e185866b80aac69b95abbeb00d1bb2e3735c1/src/ComputeShaderTest/ComputeShaderPerformanceILGPU.cs#L63
For two reasons:
* when we are using `[ParamsSource]` or `[ArgumentsSource]` the boilerplate code was so far calling `.ToArray()[index]` on it, where …

Dispose parameters, kill benchmarking process when it hangs after printing the results

---

src/BenchmarkDotNet/Engines/EngineFactory.cs
src/BenchmarkDotNet/Engines/EngineResolver.cs
tests/BenchmarkDotNet.Tests/Engine/EngineFactoryTests.cs

if the Jitting took more than IterationTime but still less than 1s (a magic number based on observations of the reported bug)
we call it one more time to see if Jitting itself has not dominated the first invocation
if it did, it should NOT be a single invocation engine (fixes #837, fixes #1337 and fixes #1338)
example:
```cs
public class Repro
{
int count;
[Benchmark]
public void Tricky()
{
if (count++ == 0)
{
System.Threading.Thread.Sleep(TimeSpan.FromSeconds(0.5));
}
}
}
```
```cmd
--filter Repro --iterationtime 250
```
Before:
<details>
```log
// Benchmark Process Environment Information:
// Runtime=.NET Core 2.1.22 (CoreCLR 4.6.29220.03, CoreFX 4.6.29220.01), X64 RyuJIT
// GC=Concurrent Workstation
// Job: Job-QFHVLA(IterationTime=250.0000 ms)
OverheadJitting  1: 1 op, 299700.00 ns, …
```

Don't run the benchmark once per iteration if only the first ivocation lasts longer than IterationTime

---

src/BenchmarkDotNet/Environments/Runtimes/CoreRuntime.cs

Fixes #1576
I've tested it both with CoreRun from 3.1 dotnet/corefx and 6.0 dotnet/runtime and it works properly now:
```cmd
dotnet run -c Release -f netcoreapp2.1 --filter IntroArguments --job dry --corerun 
C:\Projects\forks\corefx\artifacts\bin\testhost\netcoreapp-Windows_NT-Release-x64\shared\Microsoft.NETCore.App\3.1.9\CoreRun.exe 
C:\Projects\forks\corefx\artifacts\bin\testhost\netcoreapp-Windows_NT-Release-x64\shared\Microsoft.NETCore.App\copy\CoreRun.exe
```
```cmd
dotnet run -c Release -f netcoreapp2.1 --filter IntroArguments --job dry --corerun
C:\Projects\forks\corefx\artifacts\bin\testhost\netcoreapp-Windows_NT-Release-x64\shared\Microsoft.NETCore.App\3.1.9\CoreRun.exe
C:\Projects\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x64\shared\Microsoft.NETCore.App\6.0.0\Co …
```

use Environment.Version to determine .NET 5+ versions

---

templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.CSharp/_BenchmarkProjectName_.csproj
templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.FSharp/_BenchmarkProjectName_.fsproj
templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.VB/_BenchmarkProjectName_.vbproj

Prevent the dotnet pack command from unexpectedly packaging benchmarking projects built via the dotnet new templates.

Prevent dotnet pack from packaging benchmark projects

---

src/BenchmarkDotNet/Validators/JitOptimizationsValidator.cs

Update the hint for non-optimised references to use the `WithOptions(ConfigOptions)` method, rather than the obsolete `With(ConfigOptions)` overload.

Update message to not suggest an obsolete API

---

src/BenchmarkDotNet.Annotations/Jobs/RuntimeMoniker.cs
src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs

Currently there is no way to specify whether to use net5.0 or net6.0 for wasm; this change introduces that ability. With out it there is no way to do wasm net6.0 runs.
This fixes: https://github.com/dotnet/BenchmarkDotNet/issues/1591

Add wasmnet50 wasmnet60 monikers

---

src/BenchmarkDotNet.Diagnostics.Windows/Tracing/NativeMemoryLogParser.cs

This PR fixes issue #1561. I've improved NativeMemoryProfiler and it always should show results, but I found a few cases that I need to check deeply. 
I've run benchmarks twice with :
```c#
.WithWarmupCount(1)
.WithLaunchCount(1)
.WithIterationCount(1)
.WithInvocationCount(1)
.WithUnrollFactor(1)
```
And for some benchmarks I got different results for `Allocated native memory` `Native memory leaks` for each run (number 1 on the following picture)
I will check it, but it requires more time, so I think we should merge this fix now.
@adamsitnik On the picture above you can see that the `Allocated` column is different for each run. Did you know about it?

fix issue #1561

---

src/BenchmarkDotNet/Columns/ParamColumn.cs
src/BenchmarkDotNet/Parameters/ParameterInstance.cs

Fix proposal for #1604 
By enabling to pass the summary style to ParameterInstances, it is possible to have different max column widths for different exporters. It also fixes the problem when not parsing the config through the run method (at which point the constructor for ParameterInstance is called).

Fix #1604 - pass SummaryStyle to ParameterInstance.ToDisplayText()

---

src/BenchmarkDotNet/Columns/BaselineRatioColumn.cs

Fixes the following test on machines with different culture info: RatioPrecisionTestWithBaseline(testDataKey: "Trend")

Fix add missing culuture info to ToString in RatioStyle

---

templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.CSharp/.template.config/template.json
templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.CSharp/_BenchmarkProjectName_.csproj
templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.FSharp/.template.config/template.json
templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.FSharp/_BenchmarkProjectName_.fsproj
templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.VB/.template.config/template.json
templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.VB/_BenchmarkProjectName_.vbproj

This is to address the issue #1512.
.template.json file as follow.
* Additional [generated switch](https://github.com/dotnet/templating/wiki/Available-Symbols-Generators#switch)  symbol `frameworksDefaults` to calculate the default values when `--console-app` is `true` or `false`
* [Generated join](https://github.com/dotnet/templating/wiki/Available-Symbols-Generators#join) with the original `frameworks` to take its value if its not empty.

Update framework symbol on dotnet new template #1512

---

build.sh

When using `build.sh` on Unix, it prompts for user password upon installation of the .NET SDK. That even contradicts the .NET SDK installer instruction:
```sh
$ ./build.sh
Installing .NET CLI...
Password:
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
```
(line 2 and 4 indicate the said contradiction)
We don't need administrator's privilege to install the SDK in `{repo root direcotry}/.dotnet`.

Install local SDK without sudo on Unix

---

templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.CSharp/.template.config/template.json
templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.CSharp/_BenchmarkProjectName_.csproj
templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.FSharp/.template.config/template.json
templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.FSharp/_BenchmarkProjectName_.fsproj
templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.VB/.template.config/template.json
templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.VB/_BenchmarkProjectName_.vbproj

This is to address the missing output type as mentioned [here](https://github.com/dotnet/BenchmarkDotNet/pull/1630/files#r553350990).
Based on the test on my local. the original issue #1512 is actually fixed by bumping up the referenced version to `0.12.1`.

update console app templating

---

samples/BenchmarkDotNet.Samples/IntroMemoryRandomization.cs
src/BenchmarkDotNet/Attributes/Mutators/MemoryRandomizationAttribute.cs
src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs
src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Engines/Engine.cs
src/BenchmarkDotNet/Engines/EngineResolver.cs
src/BenchmarkDotNet/Jobs/JobExtensions.cs
src/BenchmarkDotNet/Jobs/RunMode.cs

A very simple implementation of https://github.com/dotnet/BenchmarkDotNet/issues/1513 that I hope is going to help us answer the question of whether we should invest more in this direction.
I am creating the PR just to have a NuGet package published by our CI so others can easily give it a try.
Sample benchmark:
```cs
public class IntroMemoryRandomization
{
[Params(512 * 4)]
public int Size;
private int[] _array;
private int[] _destination;
[GlobalSetup]
public void Setup()
{
_array = new int[Size];
_destination = new int[Size];
}
[Benchmark]
public void Array() => System.Array.Copy(_array, _destination, Size);
}
```
```cs
dotnet run -c Release -f netcoreapp2.1 --filter IntroMemoryRandomization
```
```ini
-------------------- Histogram --------------------
[502.859 ns ; 508.045 ns) | …
```

Memory Randomization

---

src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommandExecutor.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliExecutor.cs
src/BenchmarkDotNet/Toolchains/Executor.cs
tests/BenchmarkDotNet.IntegrationTests/StandardErrorTests.cs

fixes #1629
@AndreyAkinshin PTAL
cc @jonsequitur

don't redirect Standard Error, as we don't read it and writing to it by benchmark can cause deadlocks

---

docs/articles/configs/exporters.md
samples/BenchmarkDotNet.Samples/IntroCustomMono.cs
src/BenchmarkDotNet/Configs/ManualConfig.cs
src/BenchmarkDotNet/Reports/SummaryStyle.cs

when users use `ManualConfig.CreateEmpty` they often don't know that they should add column provider and logger.
Introducing this new method should make it easier for the users to define custom exporters etc by using `ManualConfig`
```cs
var config = ManualConfig.CreateEmpty()
.AddColumnProvider(DefaultColumnProviders.Instance)
.AddLogger(ConsoleLogger.Default);
```

introduce ManualConfig.CreateMinimumViable() method

---

azure-pipelines.Ubuntu.yml
azure-pipelines.Windows.yml
docs/articles/configs/toolchains.md
src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Environments/Runtimes/CoreRtRuntime.cs
src/BenchmarkDotNet/Toolchains/CoreRt/CoreRtToolchain.cs
src/BenchmarkDotNet/Toolchains/CoreRt/CoreRtToolchainBuilder.cs
src/BenchmarkDotNet/Toolchains/CoreRt/Generator.cs
tests/BenchmarkDotNet.IntegrationTests.ManualRunning/LocalCoreRtToolchainTests.cs
tests/BenchmarkDotNet.IntegrationTests/BuildTimeoutTests.cs
tests/BenchmarkDotNet.IntegrationTests/CoreRtTests.cs
tests/BenchmarkDotNet.IntegrationTests/MemoryDiagnoserTests.cs
tests/BenchmarkDotNet.IntegrationTests/ThreadingDiagnoserTests.cs

@AndreyAkinshin CoreRT has moved from https://github.com/dotnet/corert/ to https://github.com/dotnet/runtimelab/tree/feature/NativeAOT and we need to update the default compiler version and nuget feed address to avoid issue like #1605
Fixes #1605
/cc @MichalStrehovsky @jkotas

CoreRT feed and version update

---

src/BenchmarkDotNet/Toolchains/CoreRt/Generator.cs
tests/BenchmarkDotNet.IntegrationTests/BuildTimeoutTests.cs
tests/BenchmarkDotNet.IntegrationTests/MemoryDiagnoserTests.cs
tests/BenchmarkDotNet.Tests/BenchmarkDotNet.Tests.csproj

Remove CoreRT workaround

---

docs/articles/configs/configoptions.md

Fix #1655 
Update the documentation [https://github.com/dotnet/BenchmarkDotNet/blob/master/docs/articles/configs/configoptions.md/#L1](https://github.com/dotnet/BenchmarkDotNet/blob/master/docs/articles/configs/configoptions.md/#L1)
- Replace the method `With` by `WithOptions`
- Remove the section about the use of `Options.Set(<boolean>, <ConfigOptions>)`, because `ConfigOptionsExtensions` is `internal`.

1655 doc with options obsolete usage of with

---

src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommand.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommandExecutor.cs

Fixes #1570
@AndreyAkinshin this is my last PR for 0.13.0 
In the example below I have `dotnet50` (snap) but no `dotnet` (typicall installation)
```log
adam@adsitnik-ubuntu:~/projects/BenchmarkDotNet/samples/BenchmarkDotNet.Samples$ dotnet --info
bash: /usr/bin/dotnet: No such file or directory
adam@adsitnik-ubuntu:~/projects/BenchmarkDotNet/samples/BenchmarkDotNet.Samples$ dotnet50 run -c Release -f net5.0 --filter BenchmarkDotNet.Samples.IntroColdStart.Foo
/home/adam/projects/BenchmarkDotNet/src/BenchmarkDotNet/Attributes/Filters/OperatingSystemsArchitectureFilterAttribute.cs(15,96): warning CS1573: Parameter 'architectures' has no matching param tag in the XML comment for 'OperatingSystemsArchitectureFilterAttribute.OperatingSystemsArchitectureFilterAttribute(bool, params …
```

Basic snap support

---

src/BenchmarkDotNet/ConsoleArguments/CorrectionsSuggester.cs
src/BenchmarkDotNet/Filters/GlobFilter.cs
tests/BenchmarkDotNet.Tests/CorrectionsSuggesterTests.cs
tests/BenchmarkDotNet.Tests/GlobFilterTests.cs
tests/BenchmarkDotNet.Tests/TypeFilterTests.cs

fixes #1539
1. don't allow for `--filter typeName` anymore, always use globs. doc does not need to be updated as it was not recommended and not mentioned anywhere that it was possible. This was causing confusion as it was an exception from using globs with `*`
2. change the filter suggestions to use full names and globs only

Filter hint improvements

---

src/BenchmarkDotNet/Toolchains/CoreRt/Generator.cs

Even if native folder contains generated output, that location contains only ompiled C# code, without additional native dependencies.
I project has Microsoft.Data.SqlClient dependency, then benchmark would not run, since it cannot find Microsoft.Data.SqlClient.SNI.dll
Proper location is to look for publish folder, where all nescessary files to run application copied.

Fix location for NativeAOT publish files

---

src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs

We have the possibility to ask BDN to stop on the first error: `--stopOnFirstError true`.
The problem is when the users don't ask for that, try to run `n` benchmarks, all of them fail to build, and BDN prints the same build error `n` times.
This PR changes that, so when all the builds fail, we stop after printing the first error.
Example:
```cmd
dotnet run -c Release -f net5.0 --filter *Algo* *IntroGenericTypeArguments* --runtimes corert50 --buildTimeout 5
```
Before:
<details>
```log
PS C:\Projects\BenchmarkDotNet\samples\BenchmarkDotNet.Samples> dotnet run -c Release -f net5.0 --filter *Algo* *IntroGenericTypeArguments* --runtimes corert50 --buildTimeout 5 …
```

when all builds fail, BDN should stop after printing first error

---

src/BenchmarkDotNet/Loggers/SynchronousProcessOutputLoggerWithDiagnoser.cs
src/BenchmarkDotNet/Running/BenchmarkCase.cs
src/BenchmarkDotNet/Toolchains/Executor.cs

This is needed to address this issue in dotnet/performance: https://github.com/dotnet/performance/issues/1720
To reiterate what is said there, since wasm processes cannot and is not reading from standard in, they do not wait for acknowledgements. This means the process can race ahead, and finish before the acknowledgement is even sent, at which point it will fail due to a closed pipe.
This change simply ignores the exception in that case, and prints an error.

Dont redirect standard input for WASM

---

samples/BenchmarkDotNet.Samples/IntroEventPipeProfilerAdvanced.cs

Necessary, since Core30 is not a build target for samples anymore.
Error message when running `#25`
```
// Build Error: The project which defines benchmarks does not target 'netcoreapp3.0'.
You need to add 'netcoreapp3.0' to <TargetFrameworks> in your project file ('C:\Data\Documents\CSharp\Knowledge\BenchmarkDotNet\samples\BenchmarkDotNet.Samples\BenchmarkDotNet.Samples.csproj').
Example: <TargetFrameworks>net461;netcoreapp3.0</TargetFrameworks>
```
This is the last occurance of Core30 in the samples.

Fix change runtime target to Core50

---

src/BenchmarkDotNet/Environments/Runtimes/CoreRuntime.cs

this is a proper fix for #1616 
fixes #1616

don't remove OS version number from the platform-specifc TFM

---

src/BenchmarkDotNet/Templates/MonoAOTLLVMCsProj.txt

Set ValidateExecutableReferencesMatchSelfContained to false in aotllvm template. 
Fixes: https://github.com/dotnet/performance/issues/1804

Set ValidateExecutableReferencesMatchSelfContained to false in aotllvm template

---

src/BenchmarkDotNet/Parameters/ParameterInstance.cs
tests/BenchmarkDotNet.IntegrationTests/ParamSourceTests.cs

Fixes #1703 
The original idea was to explicitly specify `UTF-8` as a `StreamWriter` encoding. It would cause `StreamWriter` to **not** throw an exception when only part of a surrogate pair left (it would be replaced with the replacement character).   
But actually updating `.ToDisplayText()` forbidding surrogate pairs splitting looks like a better fix.
Old `DisplayText`: `a😀☐(...)😀😀 [201]` (causes `StreamWriter` to throw the exception)
New `DisplayText`: `a😀(...)😀😀 [201]`
Logs:
```
// ***** BenchmarkRunner: Start   *****
// ***** Found 1 benchmark(s) in total *****
// ***** Building 1 exe(s) in Parallel: Start   *****
BuildScript: C:\Users\onovak\Documents\repos\BenchmarkDotNet\samples\BenchmarkDotNet.Samples\bin\Debug\net461\b681758f-a705-4498-bd08-6073e1006811.bat
// ***** Done, took …
```

do not split surrogates in `ParameterInstance.ToDisplayText()`

---

src/BenchmarkDotNet/Templates/WasmCsProj.txt

A check was added to the SDK to check for the wasm "workloads" to be installed when building wasm apps, but BDN doesn't actually need this. So this PR adds a msbuild property to disable  the check.
Fixes: https://github.com/dotnet/performance/issues/1823

Added UsingBrowserRuntimeWorkload

---

src/BenchmarkDotNet/Templates/WasmAotCsProj.txt
src/BenchmarkDotNet/Templates/WasmCsProj.txt

This is needed to prevent another check in the SDK that is not needed for BDN, and unblock an issue we are seeing in wasm-aot.

Added <WasmNativeWorkload>false</WasmNativeWorkload> to Wasm cs proj

---

src/BenchmarkDotNet/Templates/WasmAotCsProj.txt

This disables another check in the SDK that we don't actually need for wasm.

Added UsingBrowserRuntimeWorkload false

---

src/BenchmarkDotNet/Templates/WasmAotCsProj.txt
src/BenchmarkDotNet/Templates/WasmCsProj.txt

Context: https://github.com/dotnet/runtime/issues/56033
The standalone (aka non-blazor) projects have to set
`WasmAssembliesToBundle` item themselves. (for now, it might be easier
in future)

Fix WasmAssembliesToBundle item is empty error

---

src/BenchmarkDotNet/Templates/WasmAotCsProj.txt
src/BenchmarkDotNet/Templates/WasmLinkerDescription.xml
src/BenchmarkDotNet/Toolchains/MonoWasm/WasmGenerator.cs

This fixes build errors, where `System.IntPtr` wasn't fully preserved.
Example error:
runtime/src/mono/wasm/build/WasmApp.Native.targets(425,5): error : Precompiling failed for .../performance/artifacts/bin/MicroBenchmarks/Release/net6.0/Job-DGQDZJ/bin/net6.0/browser-wasm/publish/System.Private.CoreLib.dll: Unable to compile method 'object System.Enum:GetValue ()' due to: 'VTable setup of type System.IntPtr failed assembly:.../performance/artifacts/bin/MicroBenchmarks/Release/net6.0/Job-DGQDZJ/bin/net6.0/browser-wasm/publish/System.Private.CoreLib.dll type:IntPtr member:(null)'.
Also suppress linker warnings. There are too many of them (around 414)
and we cannot fix them currently as most of them comes
from the referenced assemblies.

Add linker description for wasm AOT

---

src/BenchmarkDotNet/Toolchains/MonoWasm/WasmToolChain.cs

Just log a warning about it. It eases development on Windows.
I tried to run a microbenchmark from the dotnet/performance repo and it
run the build phase just fine. I am not sure yet, whether it will run
fine, so I kept the log message there.

Make mono/wasm run on Windows

---

src/BenchmarkDotNet/Templates/WasmAotCsProj.txt
src/BenchmarkDotNet/Templates/WasmCsProj.txt

The `WasmBuildAppDependsOn` property gets overwritten by the wasm-tools
workload's https://github.com/dotnet/runtime/blob/main/src/mono/wasm/build/WasmApp.props#L9-L18
So instead, set the `WasmBuildAppAfterThisTarget` property to our
`PrepareForWasmBuild` target and make it run after `Publish` target.
The workload's `WasmApp` has condition on `WasmBuildAppAfterThisTarget`
and should not overwrite it.

Make PrepareForWasmBuild work with wasm workload

---

src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliExecutor.cs
src/BenchmarkDotNet/Toolchains/Results/ExecuteResult.cs

This PR fixes #1731 by:
- Increasing process exit timeout from 250 to 2000 milliseconds.
- Waiting 500 milliseconds for `KillProcessTree()` to work.
- Guarding `process.ExitCode` on `process.HasExited` and giving more meaningful error messages for hung benchmarking processes.
Thank you!

Fix #1731.

---

src/BenchmarkDotNet/Engines/Consumer.cs
src/BenchmarkDotNet/Extensions/ReflectionExtensions.cs
src/BenchmarkDotNet/Templates/BenchmarkType.txt
tests/BenchmarkDotNet.Tests/ReflectionTests.cs

- `System.Void*` is not supported as type in C#, so I map to `void*` in GetCorrectCSharpTypeName similarly to regular `void`
- `System.Void*` and other pointer types cannot be consumed, so I have to add two Consume functions. I do not mark them as `[PublicAPI]` since this is too would be much liberty from me.
- I mark whole autogenerated class as `unsafe` to not introduce special checks for unsafe types when generate code. Hopefully this is accepteable.
Closes #1720

Add support for returning unmanaged types from benchmarks

---

src/BenchmarkDotNet/Templates/WasmAotCsProj.txt
src/BenchmarkDotNet/Templates/WasmCsProj.txt

The c3fb7b9724a62048d27ef5bcaec616117d68b934 commit introduced unsafe
code. Update the wasm autogenerated projects to allow unsafe code.

[wasm] Allow unsafe code

---

src/BenchmarkDotNet/Templates/WasmCsProj.txt

This should fix errors like:
performance/tools/dotnet/x64/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/6.0.0-rc.1.21378.3/Sdk/WasmApp.targets(139,5): error : $(WasmMainJSPath) property needs to be set

[wasm] Add WasmMainJSPath in interpreter projects

---

tests/BenchmarkDotNet.IntegrationTests/ThreadingDiagnoserTests.cs

The trailing space was triggering
tests\BenchmarkDotNet.IntegrationTests\ThreadingDiagnoserTests.cs(159,140): warning SA1028: Code should not contain trailing whitespace

Get rid of warning

---

src/BenchmarkDotNet/Attributes/MemoryDiagnoserAttribute.cs
src/BenchmarkDotNet/Columns/MetricColumn.cs
src/BenchmarkDotNet/Configs/ImmutableConfig.cs
src/BenchmarkDotNet/Diagnosers/AllocatedNativeMemoryDescriptor.cs
src/BenchmarkDotNet/Diagnosers/MemoryDiagnoser.cs
src/BenchmarkDotNet/Diagnosers/MemoryDiagnoserConfig.cs
src/BenchmarkDotNet/Diagnosers/PmcMetricDescriptor.cs
src/BenchmarkDotNet/Diagnosers/ThreadingDiagnoser.cs
src/BenchmarkDotNet/Disassemblers/DisassemblyDiagnoser.cs
src/BenchmarkDotNet/Reports/Metric.cs
tests/BenchmarkDotNet.Tests/Reports/FakeMetricDescriptor.cs
tests/BenchmarkDotNet.Tests/Reports/SummaryTests.cs

Some of our users, are not interested in the `Gen 0/1/2` columns, all they want to see is the `Allocated` column.
Example:
```cs
public class AccurateAllocations
{
[Benchmark] public byte[] EightBytesArray() => new byte[8];
[Benchmark] public byte[] SixtyFourBytesArray() => new byte[64];
[Benchmark] public Task<int> AllocateTask() => Task.FromResult(default(int));
}
```
Before:
|              Method |     Mean |     Error |    StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------- |---------:|----------:|----------:|-------:|------:|------:|----------:|
|     EightBytesArray | 4.245 ns | 0.0804 ns | 0.0671 ns | 0.0041 |     - |     - |      32 B |
| SixtyFourBytesArray | 8.160 ns | 0.1413 ns | 0.1180 ns | 0.0112 |     - |     - |      88 B |
|        AllocateTask | 7.561 ns | …

Allow users to hide Gen X columns

---

src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Templates/WasmCsProj.txt
src/BenchmarkDotNet/Toolchains/MonoWasm/WasmGenerator.cs

I couldn't push to the branch for this PR: https://github.com/dotnet/BenchmarkDotNet/pull/1759 so I created this one to keep working on it.
Fixes:
```
The "WasmAppBuilder" task failed unexpectedly.
System.ArgumentException: File MainJS='$RUNTIMESRCDIR$\src\mono\wasm\runtime-test.js' doesn't exist.
at WasmAppBuilder.Execute() in WasmAppBuilder.dll:token 0x6000042+0x27
at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() in Microsoft.Build.dll:token 0x6001602+0x3e
at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) in Microsoft.Build.dll:token 0x6001481+0x2b5
```

Pr wasm set runtimesrcdir for interpreter

---

docs/articles/samples/IntroSetupCleanupIteration.md

As mentioned in https://github.com/dotnet/BenchmarkDotNet/issues/730#issuecomment-389971683
I think it would be useful to include that information in the documentation as well (effects on `UnrollFactor` and `InvocationCount`).

Clarify effects of IterationSetup on UnrollFactor and InvocationCount

---

src/BenchmarkDotNet/Templates/MonoAOTLLVMCsProj.txt

Fixes: https://github.com/dotnet/performance/issues/1927

Set allow unsafe blocks to true in MonoAOTLLVM runtime

---

src/BenchmarkDotNet/Configs/ImmutableConfigBuilder.cs

Diagnoser-provided Analysers weren't automatically added to config before this fix.

Bugfix in ImmutableConfigBuilder. Fixes #1789

---

src/BenchmarkDotNet/BenchmarkDotNet.csproj

- Also updated Microsoft.Win32.Registry to latest (5.0.0) since it is a direct dependency of the former.
- Fixes bugs in .Net Core >=3.1 builds in RuntimeInformation.GetAntivirusProducts() and GetVirtualMachineHypervisor() where the use of ManagementObjectSearcher throws a silently eaten exception.
Theoretically, this would also have affected MosCpuInfoProvider.MosCpuInfo, but its use is limited to .Net Framework by the caller.
You can easily see this in previous CI logs where the net461 build shows VM=Hyper-V in the system info while the net5.0 build doesn't.

Update PackageReference for System.Management to latest (5.0.0).

---

src/BenchmarkDotNet.Annotations/Jobs/RuntimeMoniker.cs
src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Environments/Runtimes/CoreRtRuntime.cs
src/BenchmarkDotNet/Environments/Runtimes/CoreRuntime.cs
src/BenchmarkDotNet/Extensions/RuntimeMonikerExtensions.cs
src/BenchmarkDotNet/Toolchains/CoreRt/CoreRtToolchain.cs
src/BenchmarkDotNet/Toolchains/CsProj/CsProjCoreToolchain.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/NetCoreAppSettings.cs
src/BenchmarkDotNet/Toolchains/ToolchainExtensions.cs
tests/BenchmarkDotNet.Tests/ConfigParserTests.cs

Runtime has switched to net7.0. This PR adds support for 7.0 in BDN.
IMO, we should look into removing hard coded mechanism (enums, --tfm / --cli options etc.). There are just too many redundant moving parts and it is not scaling well.

Add net70 runtime support

---

azure-pipelines.Ubuntu.yml

ubuntu-16.04 was removed recently (https://github.com/actions/virtual-environments/issues/3287), bumping to 20.04.

Use non-deprecated Azure Pipelines Ubuntu pool

---

NuGet.Config
src/BenchmarkDotNet.Annotations/Jobs/RuntimeMoniker.cs
src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs

This change lets the llvmaot tool chain work with net7 (and, in principle, netX for any X), and also allows selecting net6. 
Also add a .net7 nuget feed.
Fixes: https://github.com/dotnet/performance/issues/2100

Enable mono llvmaot tool chain to work with net7

---

azure-pipelines.Ubuntu.yml
src/BenchmarkDotNet/Configs/ImmutableConfigBuilder.cs
src/BenchmarkDotNet/Reports/Summary.cs
src/BenchmarkDotNet/Validators/ConfigCompatibilityValidator.cs
tests/BenchmarkDotNet.Tests/Configs/ImmutableConfigTests.cs
tests/BenchmarkDotNet.Tests/Validators/ConfigCompatibilityValidatorTests.cs

ImmutableConfigBuilder.cs
- Force default for SummaryStyle if null (like it's already done for Orderer etc).
- Test added to ImmutableConfigTests.cs
Summary.cs
- Same behavior for getting SummaryStyle as for Orderer. Style property can no longer be null.
ConfigCompatibilityValidator.cs
- Add check against multiple, non-equal SummaryStyles.
- Test added to ConfigCompatibilityValidatorTests
Repro for previous behavior:
```cs
using System;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Columns;
using BenchmarkDotNet.Configs;
using BenchmarkDotNet.Reports;
using BenchmarkDotNet.Running;
namespace BDNSummaryStyle
{
[DryJob]
public class Benchmarks1
{
[Benchmark] public void Method1() { }
}
[DryJob]
public class Benchmarks2
{
[Benchmark] public void Method2() { }
}
internal class …
```

Ensure proper SummaryStyle handling

---

src/BenchmarkDotNet/Extensions/StringAndTextExtensions.cs
tests/BenchmarkDotNet.IntegrationTests/ArgumentsTests.cs

Fixes a bug reported by @stephentoub in https://github.com/dotnet/performance/pull/2125/files/52b20996fa82093a0daed0cecedec39017c11abb#r750329575
Ideally I would just use [ProcessStartInfo.ArgumentList](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.argumentlist?view=net-5.0) and let it take care of all the args escaping, but BDN targets .NET Standard 2.0 and I can't do that.

Fix argument escaping

---

docs/articles/configs/toolchains.md
samples/BenchmarkDotNet.Samples/IntroWasm.cs
src/BenchmarkDotNet/Templates/WasmAotCsProj.txt
src/BenchmarkDotNet/Templates/WasmCsProj.txt
src/BenchmarkDotNet/Toolchains/Executor.cs
src/BenchmarkDotNet/Toolchains/MonoWasm/WasmGenerator.cs

fix perf after renames in https://github.com/dotnet/runtime/pull/61596

[wasm] fix perf after test renames

---

azure-pipelines.macOS.yml

Fixes the warning: "The macOS-10.14 environment is deprecated and will be removed on December 10, 2021. For more details see https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/"
/cc @AndreyAkinshin

Use non-deprecated macOS pool on Azure Pipelines

---

src/BenchmarkDotNet/Diagnosers/MemoryDiagnoser.cs
src/BenchmarkDotNet/Disassemblers/DisassemblyDiagnoser.cs

The split pull request of #1852. The Part 1.
master:
| Method | Code Size | Allocated |
|------- |----------:|----------:|
|      A |      0 KB |      1 KB |
| Method | Code Size | Allocated |
|------- |----------:|----------:|
|      C |   1,120 B |     432 B |
PR:
| Method | Code Size | Allocated |
|------- |----------:|----------:|
|      A |   0.04 KB |   1.49 KB |
| Method | Code Size | Allocated |
|------- |----------:|----------:|
|      C |    1120 B |     432 B |
Benchmarks:
```C#
[MemoryDiagnoser, DisassemblyDiagnoser]
public class Benchmark1
{
[Benchmark] public byte[] A() => new byte[1500];
}
[MemoryDiagnoser, DisassemblyDiagnoser]
public class Benchmark2
{
[Benchmark] public byte[] C() => new byte[100].Select(x => x).Reverse().ToArray();
}
```

Fix size specifier

---

src/BenchmarkDotNet/Reports/SummaryStyle.cs

Bugfix for a likely typo in merged PR #1855: Equals(SizeUnit, other.CodeSizeUnit)` -> Equals(**Code**SizeUnit, other.CodeSizeUnit)

Bugfix for merged PR #1855

---

src/BenchmarkDotNet.Diagnostics.Windows/JitDiagnoser.cs

JitDiagnosers should print an error when run on non-Windows OS

---

src/BenchmarkDotNet/Columns/BaselineAllocationRatioColumn.cs
src/BenchmarkDotNet/Columns/BaselineCustomColumn.cs
src/BenchmarkDotNet/Columns/DefaultColumnProvider.cs
src/BenchmarkDotNet/Diagnosers/AllocatedMemoryMetricDescriptor.cs
src/BenchmarkDotNet/Diagnosers/MemoryDiagnoser.cs
src/BenchmarkDotNet/Reports/SummaryStyle.cs

fixes #722
It's an analog of [`BaselineRatioColumn`.](https://github.com/dotnet/BenchmarkDotNet/blob/63e28c100a42a6492d09a0b93a8a4c141061bb0d/src/BenchmarkDotNet/Columns/BaselineRatioColumn.cs)
Notes:
If it's a breaking change
```C#
public virtual ColumnCategory Category => ColumnCategory.Baseline;
//for 
public override ColumnCategory Category => ColumnCategory.Metric; //it should be displayed after Allocated column
```
Then it can be done thought EIMI, but I think it's helpful extension for the future. 
```C#
IColumn.ColumnCategory Category => ColumnCategory.Metric;
```
P.S. `ColumnCategory` is used for the outer sorting:
https://github.com/dotnet/BenchmarkDotNet/blob/63e28c100a42a6492d09a0b93a8a4c141061bb0d/src/BenchmarkDotNet/Reports/SummaryExtensions.cs#L13-L24
.
There are 2 ways how …

Add Allocation Ratio column

---

src/BenchmarkDotNet/Exporters/CompositeExporter.cs

Preventing benchmark failure when some of the exporters fail. It's annoying when long running benchmark crashes because of exporter failure (e.g. Disassembly exporter, when I care only about measurements), without printing report to console.

Handled exceptions from exporters in CompositeExporter

---

src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs
tests/BenchmarkDotNet.IntegrationTests/ExceptionHandlingTests.cs

Fixes few issues:
* when `OverheadJitting` succeeds, but workload fails there are some measurements reported. I've improved the check to take this into account:
```diff
- if (!measurements.Any())
+ if (!measurements.Any(measurement => measurement.IsWorkload()))
```
* when few iterations run OK, but then some fail the `MemoryDiagnoser` (which runs at the end) is not collecting any data, hence there is nothing to parse. I've changed `lines.Last` to `lines.LastOrDefault` to account for that
* when we know that the benchmarking has failed, we should not try to run any diagnosers
fixes #1803
cc @jeffhandley who has reported this bug offline

don't use diagnosers when running the benchmark has failed

---

src/BenchmarkDotNet.Annotations/Attributes/BenchmarkAttribute.cs
src/BenchmarkDotNet/Running/BenchmarkConverter.cs
src/BenchmarkDotNet/Running/TypeFilter.cs
tests/BenchmarkDotNet.Tests/Running/BenchmarkConverterTests.BAC_Partial_DifferentFiles.cs
tests/BenchmarkDotNet.Tests/Running/BenchmarkConverterTests.cs

The story behind this fix is quite long.
In the dotnet/performance repo we have a single type that allows for partitioning benchmarks. The idea is quite simple: it's a filter that takes partition index and count and performs modulo operation to check whether current benchmark belongs to given partition (and should be executed).
Entire [logic](https://github.com/dotnet/performance/blob/main/src/harness/BenchmarkDotNet.Extensions/PartitionFilter.cs#L25):
```cs
public bool Predicate(BenchmarkCase benchmarkCase)
=> _counter++ % _partitionsCount == _partitionIndex; // will return true only for benchmarks that belong to it’s partition
```
Some time ago @DrewScoggins has realized that some of the benchmarks in our Reporting System seem to be missing data from time to time. In the example below …

ensure the default order of benchmarks is the same as declared in source code

---

src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs

A feature request I got offline from our users who run a LOT of benchmarks (thousands) and would like to know when approximately it's going to finish.
Sample log output:
```log
// ** Remained 17 (94.4%) benchmark(s) to run. Estimated finish 2/2/2022 7:23:32 PM **
```
cc @danmoseley

Log progress and estimated finish time

---

src/BenchmarkDotNet/Templates/CsProj.txt

https://github.com/dotnet/roslyn/issues/59240

Don't run Analyzers for the generated project + Roslyn workaround

---

docs/articles/guides/console-args.md
src/BenchmarkDotNet/Templates/WasmAotCsProj.txt
src/BenchmarkDotNet/Templates/WasmCsProj.txt
src/BenchmarkDotNet/Toolchains/Executor.cs
src/BenchmarkDotNet/Toolchains/MonoWasm/WasmGenerator.cs

This file generated by wasm apps changed names; this fix makes bdn  use the new name.
Fixes: https://github.com/dotnet/runtime/issues/64553

[WASM] Fix rename of main.js to test-main.js

---

src/BenchmarkDotNet/Exporters/Json/JsonExporterBase.cs
src/BenchmarkDotNet/Exporters/Xml/SummaryDto.cs
tests/BenchmarkDotNet.Tests/Exporters/ApprovedFiles/CommonExporterApprovalTests.Exporters.Invariant.approved.txt
tests/BenchmarkDotNet.Tests/Exporters/ApprovedFiles/CommonExporterApprovalTests.Exporters.en-US.approved.txt
tests/BenchmarkDotNet.Tests/Exporters/ApprovedFiles/CommonExporterApprovalTests.Exporters.ru-RU.approved.txt
tests/BenchmarkDotNet.Tests/Exporters/CommonExporterApprovalTests.cs

Fix `BytesAllocatedPerOperation` not being output by the JSON and XML exporters.
This appears to have been broken in v0.13.1 by the changes in #1762, which removed the public `BytesAllocatedPerOperation` property from the `GcStats` structure.

Restore BytesAllocatedPerOperation for JSON and XML

---

src/BenchmarkDotNet/Analysers/ConclusionHelper.cs
src/BenchmarkDotNet/Configs/DebugConfig.cs
src/BenchmarkDotNet/Configs/DefaultConfig.cs
src/BenchmarkDotNet/Configs/IConfig.cs
src/BenchmarkDotNet/Configs/ImmutableConfig.cs
src/BenchmarkDotNet/Configs/ImmutableConfigBuilder.cs
src/BenchmarkDotNet/Configs/ManualConfig.cs
src/BenchmarkDotNet/Running/BenchmarkConverter.cs
src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs
tests/BenchmarkDotNet.Tests/Configs/ImmutableConfigTests.cs

fixes #1700
alternative version of PR #1702

fixes(configuration): Not unique exporter for exporter type 

---

src/BenchmarkDotNet/Templates/WasmCsProj.txt

Get the wasm targets building again.
```BenchmarkDotNet.Autogenerated.csproj(21,5): error MSB4025: The project file could not be loaded. The 'WasmMainJSPath' start tag on line 15 position 6 does not match the end tag of 'PropertyGroup'. Line 21, position 5```

Fix typo in WasmCsProj.txt

---

src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Environments/Runtimes/WasmRuntime.cs

Fix https://github.com/dotnet/performance/issues/2250
Commit 80f45cedc started using the runtime moniker to decide, which
main JS file to use. We use `test-main.js` in net7.0, while we were
using `main.js` in older versions.
To make that work, let set the right runtime moniker to `WasmRuntime`. So
that later in `Executor::ProcessStartInfo` we select the right file.

[wasm] Set the right runtime moniker

---

src/BenchmarkDotNet/Templates/BenchmarkType.txt

Not sure this is sufficient to catch all the cases where these methods are generated, but this is the rough idea.
Fixes #1934

Fix optimization of action methods for coreclr

---

src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs
src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Environments/Runtimes/WasmRuntime.cs
src/BenchmarkDotNet/Templates/WasmCsProj.txt
src/BenchmarkDotNet/Toolchains/MonoWasm/WasmGenerator.cs

In an earlier commit, generated projects got support for importing
props/targets files from the benchmark projects. And that allows
customizing the build.
But there isn't a clean way to inject/add references to the build of the
project, like custom paths, or access to additional files, without
adding new command line parameters.
To solve that, `--wasmDataDir` param is added which is surfaced in the
generated project as the msbuild property - `$(WasmDataDir)`.
An example use case is to have the wasm js file added to this data dir,
and in the props file use:
`<WasmMainJSPath>$(WasmDataDir)test-main.js</WasmMainJSPath>`.

[wasm] Add a `--wasmDataDir` parameter

---

src/BenchmarkDotNet/Loggers/AsyncProcessOutputReader.cs

Using a `ConcurrentStack<string>` and converting it to a string
results in the output being in reverse order.
Eg:
```
[2022/03/11 18:50:56][INFO]  Standard error:
[2022/03/11 18:50:56][INFO]  Time Elapsed 00:00:04.52
[2022/03/11 18:50:56][INFO]     1 Error(s)
[2022/03/11 18:50:56][INFO]     1 Warning(s)
[2022/03/11 18:50:56][INFO] /home/helixbot/work/C1620A35/p/dotnet-wasm/src/mono/wasm/build/WasmApp.targets(273,5): error : File MainJS='/home/helixbot/work/C1620A35/p/dotnet-wasm/src/mono/wasm/main.js' doesn't exist. [/home/helixbot/work/C1620A35/p/performance/artifacts/bin/MicroBenchmarks/Release/net6.0/bad71138-a579-43c9-adcb-c1124d577ac6/BenchmarkDotNet.Autogenerated.csproj]
[2022/03/11 18:50:56][INFO] CSC : warning CS8002: Referenced assembly 'MicroBenchmarks, Version=42.42.42.42, …
```

AsyncProcessOutputReader: Use ConcurrentQueue instead of ConcurrentStack

---

src/BenchmarkDotNet/Engines/EngineFactory.cs

Increase the magic limit to 10s per #1780.
Also use the "1.5" criteria for retry so we don't have odd threshold
where initial jitting is a bit faster than IterationTime but not fast
enough to trigger the multi action engine.

Revise heuristic for initial jitting.

---

src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs

improve error message for users who pass path to Core_Root instead of CoreRun

---

src/BenchmarkDotNet/Loggers/AsyncProcessOutputReader.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliBuilder.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommand.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommandExecutor.cs
src/BenchmarkDotNet/Toolchains/MonoWasm/WasmToolChain.cs

This is useful when building wasm/aot projects, which can take
10-20mins. Being able to see the progress helps, for example, with
diagnosing issues when the whole thing might timeout, or when running
locally.
This enables it by default for wasm/aot builds.

DotNetCli*: Allow logging command output

---

src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommand.cs
src/BenchmarkDotNet/Toolchains/Executor.cs

Once the `AfterAll` signal is received, and the process doesn't exit within 2s, we try to kill the process tree with SIGTERM. But the process might not immediately quit, so trying to access `process.ExitCode` with the process still running throws an exception:
```
[2022/03/17 05:48:51][INFO] // AfterAll
[2022/03/17 05:48:53][INFO] // The benchmarking process did not quit on time, it's going to get force killed now.
[2022/03/17 05:48:53][INFO] Unhandled exception. System.InvalidOperationException: Process must exit before requested information can be determined.
[2022/03/17 05:48:53][INFO]    at System.Diagnostics.Process.EnsureState(State state)
[2022/03/17 05:48:53][INFO]    at BenchmarkDotNet.Toolchains.Executor.Execute(Process process, BenchmarkCase benchmarkCase, …
```

Executor: Don't use Process.ExitCode, unless the process has exited

---

docs/articles/guides/troubleshooting.md
src/BenchmarkDotNet/Configs/ConfigOptions.cs
src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs
src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Running/BuildPartition.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommand.cs
tests/BenchmarkDotNet.Tests/ConfigParserTests.cs

In #1950 @radical has added the possibility to log build output to the console. This PR exposes this feature via `--logBuildOutput` command line arg.

add possibility to enable build output logging via command line args

---

src/BenchmarkDotNet/Extensions/StringAndTextExtensions.cs
src/BenchmarkDotNet/Toolchains/CoreRt/CoreRtToolchain.cs
src/BenchmarkDotNet/Toolchains/CoreRt/Generator.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommand.cs
tests/BenchmarkDotNet.Tests/StringExtensionsTests.cs

Previous discussion here: https://github.com/dotnet/BenchmarkDotNet/pull/1951 (and https://github.com/dotnet/BenchmarkDotNet/pull/1952)
This was tested locally by manually pointing dotnet/performance to this code and running a CoreRT benchmark against it. 
This fixes 2 different issues:
1. The architecture flag "-r" didn't have a leading space and therefore was combine with the string in front of it, causing it not to be passed to the dotnet restore/build/publish commands. Would look like this: `dotnet restore /p:DebugType=portable -bl:benchmarkdotnet.binlog-r win-x64 /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 /p:Deterministic=true /p:Optimize=true and dotnet fails to restore/build/publish`
2. The output directory of CoreRT publishes wasn't specified and if running the …

Cleaning up argument spacing in CLI calls. Add output path for publish. CoreRT

---

src/BenchmarkDotNet/Loggers/SynchronousProcessOutputLoggerWithDiagnoser.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliExecutor.cs
src/BenchmarkDotNet/Toolchains/Executor.cs
src/BenchmarkDotNet/Toolchains/GeneratorBase.cs
src/BenchmarkDotNet/Toolchains/InProcess.Emit/InProcessEmitBuilder.cs
src/BenchmarkDotNet/Toolchains/InProcess.Emit/InProcessEmitGenerator.cs
src/BenchmarkDotNet/Toolchains/InProcess.NoEmit/InProcessNoEmitGenerator.cs
src/BenchmarkDotNet/Toolchains/InProcess/InProcessGenerator.cs
src/BenchmarkDotNet/Toolchains/Results/BuildResult.cs
src/BenchmarkDotNet/Toolchains/Results/GenerateResult.cs
tests/BenchmarkDotNet.IntegrationTests/ToolchainTest.cs
tests/BenchmarkDotNet.Tests/BuildResultTests.cs
tests/BenchmarkDotNet.Tests/Mocks/MockFactory.cs
tests/BenchmarkDotNet.Tests/Reports/RatioPrecisionTests.cs
tests/BenchmarkDotNet.Tests/Reports/RatioStyleTests.cs
tests/BenchmarkDotNet.Tests/Reports/SummaryTests.cs

This PR fixes a bug that I've introduced in https://github.com/dotnet/BenchmarkDotNet/pull/1940
In #1940 I've changed the benchmark process code to not wait for a blocking acknowledgment if there is no need to.
But he thost process was still writing the acknowledgments (which were just ignored by the benchmark process). In cases when  benchmark process has managed to already quit, it's std in was closed and host was failing with "broken pipe":
```log
at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
at System.IO.FileStream.FlushWriteBuffer()
at System.IO.FileStream.Flush(Boolean flushToDisk)
at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
at System.IO.StreamWriter.WriteLine(String value)
at BenchmarkDotNet.Loggers.SynchronousProcessOutputLoggerWithDiagno …
```

fix broken pipe issue

---

src/BenchmarkDotNet.Annotations/Attributes/DynamicallyAccessedMemberTypes.cs
src/BenchmarkDotNet.Annotations/Attributes/DynamicallyAccessedMembersAttribute.cs
src/BenchmarkDotNet.Annotations/Attributes/GenericTypeArgumentsAttribute.cs
src/BenchmarkDotNet.Annotations/Jobs/RuntimeMoniker.cs
src/BenchmarkDotNet/Attributes/Filters/AotFilterAttribute.cs
src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs
src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Environments/Runtimes/CoreRtRuntime.cs
src/BenchmarkDotNet/Environments/Runtimes/MonoAotLLVMRuntime.cs
src/BenchmarkDotNet/Environments/Runtimes/MonoRuntime.cs
src/BenchmarkDotNet/Environments/Runtimes/NativeAotRuntime.cs
src/BenchmarkDotNet/Environments/Runtimes/Runtime.cs
src/BenchmarkDotNet/Environments/Runtimes/WasmRuntime.cs
src/BenchmarkDotNet/Extensions/RuntimeMonikerExtensions.cs
src/BenchmarkDotNet/Portability/RuntimeInformation.cs
src/BenchmarkDotNet/Toolchains/CoreRt/CoreRtToolchain.cs
src/BenchmarkDotNet/Toolchains/CoreRt/CoreRtToolchainBuilder.cs
src/BenchmarkDotNet/Toolchains/Executor.cs
src/BenchmarkDotNet/Toolchains/ToolchainExtensions.cs
tests/BenchmarkDotNet.Tests/ConfigParserTests.cs

With the following 3 recent fixes:
* https://github.com/dotnet/runtime/pull/66290 (https://github.com/dotnet/runtime/issues/66028) 
* https://github.com/dotnet/runtime/pull/66650 (https://github.com/dotnet/runtime/issues/66637)
* https://github.com/dotnet/BenchmarkDotNet/pull/1955
It required very little work to improve the NativeAOT support. Main changes:
* CoreRT and NativeAOT are treated as two different runtimes, mostly to be able to run .NET 6 with CoreRT vs .NET 7 with NativeAOT
* `--runtimes` no longer supports `corert70`. The proper name is `nativeaot70` (case and dots are ignored, so you can use `NativeAOT7.0` as well)
* the default feed for the `CoreRtToolchainBuilder` has been upgraded to .NET 7 feed
* the default ILCompiler for the `CoreRtToolchainBuilder` has been upgraded to …

Improve support for NativeAOT

---

src/BenchmarkDotNet/Templates/MonoAOTLLVMCsProj.txt

The library extension of FreeBSD is wrong for the MonoAOTLLVM tool chain.

Fixed FreeBSD shared library extension in MonoAOTLLVM tool chain.

---

src/BenchmarkDotNet/Toolchains/NativeAot/Generator.cs
src/BenchmarkDotNet/Toolchains/NativeAot/NativeAotToolchain.cs
src/BenchmarkDotNet/Toolchains/NativeAot/NativeAotToolchainBuilder.cs

To ensure that trimmer only analyzes the parts of the dependencies that are used. With this setting, the build time for our samples project goes from 116 to 15 seconds! I've tested it with dotnet/performance microbenchmarks and everything works fine. In case it does not, users can still disable it:
```cs
builder.SeTrimmerDefaultAction("");
```
cc @MichalStrehovsky

[NativeAOT] Set TrimmerDefaultAction to link 

---

src/BenchmarkDotNet.Annotations/Attributes/GenericTypeArgumentsAttribute.cs

it's a nop for NativeAOT and a bug for WASM. Instead of using `params` I've added ctors that accept 1, 2 and 3 types.
https://github.com/dotnet/BenchmarkDotNet/pull/1960#discussion_r832712652
cc @MichalStrehovsky @radical

don't place DynamicallyAccessedMembers on an array

---

README.md
docs/articles/guides/console-args.md
docs/index.md
src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs
src/BenchmarkDotNet/Environments/Platform.cs
src/BenchmarkDotNet/Extensions/ConfigurationExtensions.cs
src/BenchmarkDotNet/Portability/RuntimeInformation.cs
tests/BenchmarkDotNet.Tests/ConfigParserTests.cs

Add support for LoongArch64.

---

src/BenchmarkDotNet/Toolchains/NativeAot/Generator.cs

For now added either `rd.xml` or files which ends with `.rd.xml`
Rename `rd.xml` supplied by BDN to `bdn_generated.rd.xml`
Closes https://github.com/dotnet/BenchmarkDotNet/issues/1680

Add support for Rd.xml file around project file

---

src/BenchmarkDotNet/Toolchains/NativeAot/Generator.cs
src/BenchmarkDotNet/Toolchains/NativeAot/NativeAotToolchain.cs
src/BenchmarkDotNet/Toolchains/NativeAot/NativeAotToolchainBuilder.cs
tests/BenchmarkDotNet.IntegrationTests.ManualRunning/LocalNativeAotToolchainTests.cs

Cpp codegeneration was never part of NativeAOT, and CoreRT is not tested/used in BDN right now, so I remove that option.

Remove CPP codegen for NativeAOT

---

src/BenchmarkDotNet/Templates/CsProj.txt

Starting from net5 Microsoft introduces a breaking change - that will prevent the solution from building if 
**executable project references another executable project and the SelfContained values don't match**
https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/5.0/referencing-executable-generates-error
It can be fixed by adding 
`<ValidateExecutableReferencesMatchSelfContained>false</ValidateExecutableReferencesMatchSelfContained>`
But BenchmarkDotNet does not copy it from the original .csproj for some reason. So I've added it directly to the CspProj.txt template. Not sure about the rest of the templates.
To reproduce this issue you can:
1. create the project A - web project/WPF project
2. create the project B - benchmark project and reference project A
2.1 Add …

Fix for issue NETSDK1150

---

appveyor.yml
build/global.json
samples/BenchmarkDotNet.Samples.FSharp/BenchmarkDotNet.Samples.FSharp.fsproj
samples/BenchmarkDotNet.Samples/BenchmarkDotNet.Samples.csproj
tests/BenchmarkDotNet.IntegrationTests.ConfigPerAssembly/BenchmarkDotNet.IntegrationTests.ConfigPerAssembly.csproj
tests/BenchmarkDotNet.IntegrationTests.DisabledOptimizations/BenchmarkDotNet.IntegrationTests.DisabledOptimizations.csproj
tests/BenchmarkDotNet.IntegrationTests.EnabledOptimizations/BenchmarkDotNet.IntegrationTests.EnabledOptimizations.csproj
tests/BenchmarkDotNet.IntegrationTests.FSharp/BenchmarkDotNet.IntegrationTests.FSharp.fsproj
tests/BenchmarkDotNet.IntegrationTests.ManualRunning/BenchmarkDotNet.IntegrationTests.ManualRunning.csproj
tests/BenchmarkDotNet.IntegrationTests.ManualRunning/LocalNativeAotToolchainTests.cs
tests/BenchmarkDotNet.IntegrationTests.Static/BenchmarkDotNet.IntegrationTests.Static.csproj
tests/BenchmarkDotNet.IntegrationTests.VisualBasic/BenchmarkDotNet.IntegrationTests.VisualBasic.vbproj
tests/BenchmarkDotNet.IntegrationTests/BenchmarkDotNet.IntegrationTests.csproj
tests/BenchmarkDotNet.IntegrationTests/DisassemblyDiagnoserTests.cs
tests/BenchmarkDotNet.IntegrationTests/JitRuntimeValidationTest.cs
tests/BenchmarkDotNet.IntegrationTests/MultipleRuntimesTest.cs
tests/BenchmarkDotNet.Tests/BenchmarkDotNet.Tests.csproj

.NET 5 would be out of support in early May, so maybe it's time to update test infra from it to .NET 6

Migrate from .NET 5 to .NET 6.0

---

src/BenchmarkDotNet/Code/CodeGenerator.cs
src/BenchmarkDotNet/Code/DeclarationsProvider.cs
src/BenchmarkDotNet/Templates/BenchmarkType.txt

We are getting OOM from x86 Roslyn in dotnet/performance as the generated source file is 3 128 078 lines long (116 MB).
With this PR we are getting code that does exactly the same thing, but using 832 679 lines of code (46 MB)
Partially addresses https://github.com/dotnet/performance/issues/2350

Reduce generated code size

---

src/BenchmarkDotNet/Extensions/ProcessExtensions.cs
src/BenchmarkDotNet/Templates/MonoAOTLLVMCsProj.txt

Some of the microbenchmarks use generic type, where Mono full AOT would emit a generic function to handle various types, which is very slow and doesn't worth benchmarking. This is one example:
https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Numerics.Vectors/Perf_VectorOfT.cs
This PR will change the AOT mode to Normal LLVM AOT with LLVM JIT fallback. Because Normal AOT leaves the generic type cases for JIT to handle. That way optimized code will be emitted.
Additionally, Maui Android is using Profiled AOT with JIT fallback, which is similar to Normal AOT with JIT fallback. Ideally, they would like to leverage LLVM too at some point.
cc: @naricc

[Mono] Change AOT mode to Normal AOT with LLVM JIT fall back

---

src/BenchmarkDotNet/Toolchains/NativeAot/Generator.cs
src/BenchmarkDotNet/Toolchains/NativeAot/NativeAotToolchain.cs
src/BenchmarkDotNet/Toolchains/NativeAot/NativeAotToolchainBuilder.cs
tests/BenchmarkDotNet.IntegrationTests/NativeAotTests.cs

Changes:
- allow the users to specify `IlcOptimizationPreference`, use `Speed` as default
- allow the users to specify `IlcInstructionSet`, use host process settings as default
Sample benchmark:
```cs
private string a = new string('a', 1000) + "a";
private string b = new string('a', 1000) + "b";
[Benchmark]
public bool Compare() => a.Equals(b, System.StringComparison.Ordinal);
```
```cmd
dotnet run -c Release -f net6.0 --filter *Compare --job short --keepFiles true --runtimes nativeaot7.0
```
|  Method |       Runtime |          Toolchain |     Mean |    Error |   StdDev |
|-------- |-------------- |------------------- |---------:|---------:|---------:|
| Compare | NativeAOT 7.0 | ILCompiler 7.0.0-* | 66.88 ns | 2.263 ns | 0.124 ns |
|  Method |       Runtime |          Toolchain | …

NativeAOT: IlcOptimizationPreference & IlcInstructionSet

---

src/BenchmarkDotNet/Extensions/ConfigurationExtensions.cs

fixes #1711
context: tools like MSBuild and Rolsyn don't support S390x yet, so we need to use `AnyCPU` as a platform target
cc @stefan-sf-ibm

use AnyCPU for S390x

---

docs/articles/configs/toolchains.md
src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs
src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Toolchains/NativeAot/Generator.cs
src/BenchmarkDotNet/Toolchains/NativeAot/NativeAotToolchain.cs
src/BenchmarkDotNet/Toolchains/NativeAot/NativeAotToolchainBuilder.cs
tests/BenchmarkDotNet.IntegrationTests.ManualRunning/LocalNativeAotToolchainTests.cs
tests/BenchmarkDotNet.Tests/ConfigParserTests.cs

The PR contains a refresh of the NativeAOT docs and fix for support of local NativeAOT build based on https://github.com/dotnet/runtime/pull/68308.
Sample:
```cmd
dotnet run -c Release -f net6.0 --project .\samples\BenchmarkDotNet.Samples\BenchmarkDotNet.Samples.csproj --filter *basic* --runtimes nativeaot7.0 --ilcPackages D:\projects\forks\jkotas\artifacts\packages\Release\Shipping\
```
```log
// Validating benchmarks:
// ***** BenchmarkRunner: Start   *****
// ***** Found 2 benchmark(s) in total *****
// ***** Building 1 exe(s) in Parallel: Start   *****
// start dotnet  restore --packages "C:\Users\adsitnik\AppData\Local\Temp\41eb8a5b-7d94-485e-bdd3-9bcdd3e8ddc1" -r win-x64 /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 /p:Deterministic=true /p:Optimize=true in …
```

Update NativeAOT docs, fix the support for local NativeAOT builds

---

src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
tests/BenchmarkDotNet.Tests/ConfigParserTests.cs

Contributes to #1954:
> Mix `--corerun` and `--netX.Y` on one command line
cc @stephentoub @AndyAyersMS

when user specifies both --runtimes and --corerun, multiple independent jobs should be created

---

src/BenchmarkDotNet.Annotations/Jobs/RuntimeMoniker.cs
src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Environments/Runtimes/CoreRuntime.cs
tests/BenchmarkDotNet.Tests/ConfigParserTests.cs

as it's used only by dotnet/runtime contributors
Sample usage:
```cmd
dotnet run -c Release -f net48 --filter ** --runtimes net48 netcoreapp3.1 net5.0 --corerun d:\coreclrtest\main\corerun.exe
```
Translates to: take all benchmarks that can be build for net4.8, build and run the generated project for:
* net48
* netcoreapp3.1
* net5.0
* build as net7.0, run using provided corerun
cc @stephentoub

when Host process is not .NET Core, CoreRunToolchain should use latest available TFM

---

src/BenchmarkDotNet/Toolchains/NativeAot/Generator.cs

Benchmark.NET opts itself into trimming, but it's trim compatible only by accident ~~(it's reflecting on things that are statically referenced and therefore would be kept by IL-based trimming solutions). NativeAOT is able to trim metadata more aggressively - e.g. an accessed field might still have its name and metadata removed and the only thing that is kept is a location in memory that can be read and written.~~
~~I'm now seeing Benchmark.NET failing with latest ILCompiler packages after https://github.com/dotnet/runtime/pull/70201 that enabled more aggressive trimming.~~
It's reflecting on a field that is not used in any other way than by unanalyzable reflection. We would previously keep all fields, irrespective of whether they're used on reflected on …

Opt out of metadata trimming

---

samples/BenchmarkDotNet.Samples/BenchmarkDotNet.Samples.csproj
src/BenchmarkDotNet/Templates/CsProj.txt
tests/BenchmarkDotNet.IntegrationTests.ManualRunning/BenchmarkDotNet.IntegrationTests.ManualRunning.csproj
tests/BenchmarkDotNet.IntegrationTests/BenchmarkDotNet.IntegrationTests.csproj

as it breaks arm64 windows build due to Roslyn bug
https://github.com/dotnet/roslyn/issues/59421
fixes #2028

don't emit debug symbols for samples and test projects 

---

src/BenchmarkDotNet.Diagnostics.Windows/BenchmarkDotNet.Diagnostics.Windows.csproj

Before:
```log
Please install the latest Microsoft.Diagnostics.Tracing.TraceEvent package in the project with benchmarks so MSBuild can copy the native dependencies of TraceEvent to the output folder.
Unhandled exception. System.ComponentModel.Win32Exception (126): The specified module could not be found.
at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.LoadKernelTraceControl()
at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.StartKernelSession(UInt64& TraceHandle, Void* propertyBuff, Int32 propertyBuffLength, STACK_TRACING_EVENT_ID* stackTracingEventIds, Int32 cStackTracingEventIds)
at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableKernelProvider(Keywords flags, Keywords stackCapture)
at BenchmarkDotNet.Diagnostics.Windows.KernelSession.EnableProvide …
```

update TraceEvent to 3.0.1 to have a proper ARM64 support for Diagnostics package

---

src/BenchmarkDotNet/Columns/MetricColumn.cs
tests/BenchmarkDotNet.Tests/Columns/MetricColumnTests.cs

The previous implementation would only use the given unit if SummaryStyle.PrintUnitsInContent was true, otherwise it would fallback to the default unit, regardless whether SummaryStyle.PrintUnitsInHeader was true or not. This fix takes both SummaryStyle.PrintUnitsIn* into account.
It should be noted that other columns than the MetricColumn do **not** take the visibility of units into account and always use the given unit, be it explicitly selected by the user, or calculated via GetBest*Unit().

Bugfix MetricColumn: Respect unit when formatting values.

---

.gitignore
src/BenchmarkDotNet/BenchmarkDotNet.csproj
src/BenchmarkDotNet/Engines/IEngine.cs
src/BenchmarkDotNet/Environments/OsBrandStringHelper.cs
src/BenchmarkDotNet/Environments/ProcessorBrandStringHelper.cs
src/BenchmarkDotNet/Extensions/CommonExtensions.cs
src/BenchmarkDotNet/Extensions/ProcessExtensions.cs
src/BenchmarkDotNet/Helpers/FrameworkVersionHelper.cs
src/BenchmarkDotNet/Portability/Cpu/MosCpuInfoProvider.cs
src/BenchmarkDotNet/Portability/Cpu/SysctlCpuInfoParser.cs
src/BenchmarkDotNet/Portability/PlatformApis.cs
src/BenchmarkDotNet/Portability/RuntimeInformation.cs
src/BenchmarkDotNet/Running/ClassicBenchmarkConverter.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/CustomDotNetCliToolchainBuilder.cs
src/BenchmarkDotNet/Toolchains/InProcess.Emit/InProcessEmitExecutor.cs
src/BenchmarkDotNet/Toolchains/InProcess.NoEmit/InProcessNoEmitExecutor.cs
src/BenchmarkDotNet/Toolchains/InProcess/InProcessExecutor.cs
tests/BenchmarkDotNet.IntegrationTests/BenchmarkDotNet.IntegrationTests.csproj

- Clean up the package dependencies as described in #2009.
- Add a `net6.0` TFM.
- Resolve supported platform and obsolete warnings for .NET 6.
- Add a TODO to correctly return the version for .NET Framework 4.8.1.
Resolves #2009.

Cleanup dependencies and add net6.0 TFM

---

.gitignore
samples/BenchmarkDotNet.Samples/BenchmarkDotNet.Samples.csproj
src/BenchmarkDotNet.Diagnostics.Windows/BenchmarkDotNet.Diagnostics.Windows.csproj
src/BenchmarkDotNet.Disassembler.x64/ClrMdV1Disassembler.cs
src/BenchmarkDotNet.Disassembler.x64/Program.cs
src/BenchmarkDotNet.Disassembler.x86/BenchmarkDotNet.Disassembler.x86.csproj
src/BenchmarkDotNet/BenchmarkDotNet.csproj
src/BenchmarkDotNet/Disassemblers/ClrMdV2Disassembler.cs
src/BenchmarkDotNet/Disassemblers/Exporters/DisassemblyPrettifier.cs
src/BenchmarkDotNet/Disassemblers/LinuxDisassembler.cs
src/BenchmarkDotNet/Disassemblers/SourceCodeProvider.cs
tests/BenchmarkDotNet.IntegrationTests/BenchmarkDotNet.IntegrationTests.csproj
tests/BenchmarkDotNet.Tests/BenchmarkDotNet.Tests.csproj

I've finally managed to port our disassembler to ClrMd v2. It should fix a lot of issues like #2000
I've kept the V1 disassembler for Full .NET Framework, as I was not able to get it working in the way I would be happy about it.
Updating TraceEvent fixes #1756

Port the .NET (Core) disassembler to ClrMd v2

---

src/BenchmarkDotNet.Annotations/Attributes/DynamicallyAccessedMembersAttribute.cs
src/BenchmarkDotNet/BenchmarkDotNet.csproj
src/BenchmarkDotNet/Characteristics/Characteristic.cs
src/BenchmarkDotNet/Characteristics/CharacteristicHelper.cs
src/BenchmarkDotNet/Characteristics/CharacteristicObject.cs
src/BenchmarkDotNet/Characteristics/CharacteristicObject`1.cs
src/BenchmarkDotNet/Characteristics/Characteristic`1.cs
src/BenchmarkDotNet/Characteristics/CompositeResolver.cs
src/BenchmarkDotNet/Characteristics/IResolver.cs
src/BenchmarkDotNet/Characteristics/Resolver.cs
src/BenchmarkDotNet/Toolchains/NativeAot/Generator.cs

Another attempt at fixing the problem I tried to fix in #2020.
In that pull request, I reflection-rooted all of BenchmarkDotNet, but that looks like it increases the size of the closure too much (https://github.com/dotnet/performance/pull/2532). So here I'm rolling that part back and annotating enough of the `Characteristic` APIs to make it so that we shouldn't run into the original problem.
I basically added `<EnableTrimAnalyzer>true</EnableTrimAnalyzer>` to the BechmarkDotNet project, looked at the trimming warning in https://github.com/dotnet/BenchmarkDotNet/blob/63e28c100a42a6492d09a0b93a8a4c141061bb0d/src/BenchmarkDotNet/Characteristics/CharacteristicHelper.cs#L49-L68 where we were getting the crash and kept adding annotations until it stopped generating new warnings.
We now have an …

Make a bit of BenchmarkDotNet trimmable

---

src/BenchmarkDotNet/Code/CodeGenerator.cs
src/BenchmarkDotNet/Parameters/SmartParamBuilder.cs
src/BenchmarkDotNet/Running/BenchmarkConverter.cs
tests/BenchmarkDotNet.IntegrationTests/ParamSourceTests.cs

SmartParameter codegen must use the target type for casting, not the type of the source value.
Basically, this is a follow up to PR #1228 (1678a49a7b044b7915c3cbcd64300501cfef9035), which fixed this problem for SmartArgument.
EDIT: ~Fixes #2011. Probably also #1812 and a few similar issues reported in the past.~
Fixes #2011, fixes #1812, fixes #1177.
@adamsitnik 
Not sure yet if the fix is complete or if the shortcuts in `SmartParamBuilder.CreateForParams()` that bypass the creation of `SmartParameter` instances have to be removed. Same for `BenchmarkConverter.GetValidValues()`.
(test failures are unrelated, though)

Bugfix SmartParameter source code generation

---

build/Program.cs
docs/docfx.json
docs/filter.yml
src/BenchmarkDotNet.Annotations/BenchmarkDotNet.Annotations.csproj
src/BenchmarkDotNet/BenchmarkDotNet.csproj

- Bump DocFx version to 2.59.3 (fixes #1992)
- ~Build BDN before building docs (fixes xref issues)~ (see notes on 3c18c4fbba8f6fd6aefbbbd3711692614ae40a92)
- Add \<ProduceReferenceAssembly\> to BDN and BDN.Annotations projects (fixes xref issues)
- Add filter.yml to avoid listing inherited members of System.Object for each type.
- Add xrefService for resolving references to .NET SDK types.

Fix DocFx configuration and build

---

src/BenchmarkDotNet/Disassemblers/DisassemblyDiagnoser.cs
src/BenchmarkDotNet/Disassemblers/LinuxDisassembler.cs
src/BenchmarkDotNet/Disassemblers/WindowsDisassembler.cs

I've tried to repro bug reported in #2063 but I've failed (script running for a whole day, everything fine).
I am guessing that the issue was caused by the fact that ClrMd 1.x has failed to attach to the benchmark process. I've seen it in the past over the years.
The best we can do is to use ClrMd v2 diassembler when the host process and benchmark process architectures are the same. It should be just more reliable.
Why we have two diassemblers? Because ClrMd2 comes with a LOT of new `System*` dependencies and in order to make it work we would need to embed at least few dozens of `System.*.dll`:
https://github.com/dotnet/BenchmarkDotNet/blob/0f457d1d476b466751774fa150d1ed08ea652bf1/src/BenchmarkDotNet/BenchmarkDotNet.csproj#L42-L45
Why do we still keep the standalone disassembler? …

use ClrMd v2 disassembler on Windows whenever possible

---

src/BenchmarkDotNet.Disassembler.x64/ClrMdV1Disassembler.cs
src/BenchmarkDotNet.Disassembler.x64/DataContracts.cs
src/BenchmarkDotNet/Attributes/DisassemblyDiagnoserAttribute.cs
src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs
src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Disassemblers/ClrMdV2Disassembler.cs
src/BenchmarkDotNet/Disassemblers/DisassemblyDiagnoserConfig.cs
src/BenchmarkDotNet/Disassemblers/SameArchitectureDisassembler.cs
src/BenchmarkDotNet/Disassemblers/WindowsDisassembler.cs
src/BenchmarkDotNet/Filters/GlobFilter.cs
tests/BenchmarkDotNet.IntegrationTests/DisassemblyDiagnoserTests.cs

So far, the disassembler was always loading the type that was generated by BDN, searching for the benchmark method, disassembling it and when encountered direct method calls, disassembling the called methods as well (if their depth was <= configured depth).
This was working fine, but only for direct method calls. For indirect, the disassembly was incomplete.
When I was working on https://github.com/dotnet/runtime/pull/73064 it was really a PITA to me, and I tried to come up with a workaround for it. So here it is: a possibility to specify a glob pattern(s) for methods that we want to be disassembled.
How it works:
- ClrMD is used to enumerate over all modules
- for each module, all types are enumerated
- for each type, every method that can be disassembled and its full signature matches …

Add glob filters support to disassembler to allow disassembling specific methods

---

src/BenchmarkDotNet/Disassemblers/ClrMdV2Disassembler.cs

Fixes #2074
Sample C# code:
```cs
public class Repro
{
[Benchmark]
public void Simple()
{
Empty();
Call();
WithThrow(false);
}
[MethodImpl(MethodImplOptions.NoInlining)]
private void Empty() { }
[Benchmark]
public void Call() => Console.WriteLine();
private void WithThrow(bool doThrow)
{
if (doThrow) throw new NotImplementedException();
}
}
```
Output for ClrMD v1:
<details>
ClrMd V1
```assembly
; BenchmarkDotNet.Samples.Repro.Simple()
push      rbp
sub       rsp,20
lea       rbp,[rsp+20]
mov       [rbp+10],rcx
mov       rcx,[rbp+10]
call      0000000000001D90
mov       rcx,[rbp+10]
call      0000000000001D98
mov       rcx,[rbp+10]
xor       edx,edx
call      0000000000001DA0
nop
add       rsp,20
pop       rbp
ret
; Total bytes of code 50
```
```assembly
; …
```

Fix disassembler

---

src/BenchmarkDotNet/Running/BenchmarkConverter.cs
src/BenchmarkDotNet/Running/BenchmarkRunnerDirty.cs
src/BenchmarkDotNet/Running/ClassicBenchmarkConverter.cs

Change unhandled exception with message exception.
Add Unsupported checking directly to the methods, because It fails in .NET core (and they are public).
Hide it from IntelliSense cuz it not working and not recommended. Feel free to drop the commit if it isn't desired.
Change unhandled exception with message-exception for the case:
```C#
BenchmarkRunner.Run(typeof(GenericBenchmarkType<>));
````
#1908

Make FromUrl and FromSource more friendly

---

src/BenchmarkDotNet/Toolchains/NativeAot/Generator.cs
tests/BenchmarkDotNet.IntegrationTests/NativeAotTests.cs

The builds has recently started to fail with:
```log
C:\Program Files\dotnet\sdk\7.0.100-rc.1.22423.16\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ConflictResolution.targets(112,5): error NETSDK1152: Found multiple publish output files with the same relative path: D:\projects\BenchmarkDotNet\tests\BenchmarkDotNet.IntegrationTests\xunit.runner.json, D:\projects\BenchmarkDotNet\tests\BenchmarkDotNet.Tests\xunit.runner.json. [D:\projects\BenchmarkDotNet\tests\BenchmarkDotNet.IntegrationTests\bin\Release\net6.0\7fafdcdc-4f53-49fa-afb4-3e835b41b979\BenchmarkDotNet.Autogenerated.csproj]
```
Since it's just a complain about test project file settings, we can ignore it.
Update: and #2080

fix the CI

---

src/BenchmarkDotNet/Exporters/Json/JsonExporterBase.cs

Hello,
I would like to add additional data to the existing JSON BenchmarkDotNet report, but there is currently no possibility to enrich the report. That's why I separated ExportToLog into report creation (ExportToLog) and further virtual report data generation methods (CreateLog).
Best regards
Peter
@adamsitnik Sorry for closing my initial pull request (#1915). I applied your suggested change (Rename CreateLog-> GetDataToSerialize) and had an issue rebasing this change into my initial commit.

JsonExporter: make Json export more extensible.

---

templates/BenchmarkDotNet.Templates.csproj

that happens during pack command for master branch build on AppVeyor
I've tested that it works locally. Due to the fact that we publish packages only when the PR gets merged to the master branch, I am going to merge it right away.

remove last warning

---

docs/articles/guides/how-to-run.md

[Docs](https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html?tabs=tabid-1%2Ctabid-a#:~:text=Do%20not%20use%20the%20%40uid%20link%20in%20brackets%20(like%20this%3A%20(%40uid)).%20DocFX%20cannot%20parse%20this%20link.%20The%20%40uid%20link%20should%20be%20separated%20with%20white%20spaces.%20If%20you%20need%20to%20add%20a%20link%20in%20brackets%2C%20use%20%5B%5D(xref%3Auid).):
> Do not use the @uid link in brackets (like this: (@uid)). DocFX cannot parse this link. The @uid link should be separated with white spaces. If you need to add a link in brackets, use [](xref:uid).
---
Master:
PR:

Nit: fix broken link

---

src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Toolchains/NativeAot/Generator.cs
src/BenchmarkDotNet/Toolchains/NativeAot/NativeAotToolchain.cs
src/BenchmarkDotNet/Toolchains/NativeAot/NativeAotToolchainBuilder.cs

After recent SDK changes the NativeAOT support got broken again. This time the failure was silent: since we were not setting `PublishAot` to true, the published app was regular .NET app, not NativeAOT.
This PR sets  `PublishAot` to `true` and removes the explicit reference to `ILCompiler` if it's specific version was not provided.
I've tested:
- support for the old CoreRT bits (we are going to remove it once .NET 7 is released and BDN repo can move to .NET 7 SDK)
- support for the latests NativeAOT bits
- support for benchmarking specific NativeAOT version
@AndreyAkinshin we might need to release a new BDN version soon (preferably with #2092 merged as well)
cc @MichalStrehovsky

[NativeAOT] use PublishAot and don't reference ILCompiler in explicit way

---

src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs
src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
tests/BenchmarkDotNet.Tests/ConfigParserTests.cs

Added a new commandline argument: ``--noForcedGCs`` that doesn't invoke any induced GCs. This is an important consideration for GC based microbenchmarks where we want to not force any GCs so that we can compare multiple runs in an equitable way. 
PS: I am not sure where to have added documentation for this.

Added a command line arg for not inducing any GCs while running Benchmarks

---

src/BenchmarkDotNet/Configs/ConfigOptions.cs
src/BenchmarkDotNet/Configs/ManualConfig.cs
src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs
src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Jobs/JobExtensions.cs
src/BenchmarkDotNet/Jobs/RunMode.cs
src/BenchmarkDotNet/Parameters/ParameterInstances.cs
src/BenchmarkDotNet/Running/BenchmarkSwitcher.cs
src/BenchmarkDotNet/Running/Descriptor.cs
src/BenchmarkDotNet/Validators/RunModeValidator.cs

Sample:
```cs
public class IntroApplesToApples
{
private readonly string path = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
private readonly string content = new string('a', 100_000);
[Benchmark]
public void WriteAllText() => File.WriteAllText(path, content);
[GlobalCleanup]
public void Delete() => File.Delete(path);
}
```
```cmd
dotnet run -c Release -f net6.0 --filter *IntroApplesToApples* --apples --runtimes net6.0 net7.0 --iterationCount 20 --statisticalTest 5%
```
It runs every benchmark for just one iteration, just so the Pilot Stage can estimate invocation count:
Then for every job defined in the config, it runs the benchmarks again, but using exact same invocation count:
Users can at the same time use one of the built-in profilers or provide their own or don't use …

Implement apples to apples comparison mode

---

src/BenchmarkDotNet/Toolchains/Roslyn/RoslynToolchain.cs
tests/BenchmarkDotNet.IntegrationTests/NugetReferenceTests.cs

Currently, it writes the error and does not return to console.

Roslyn Toolchain does not support .NET Core

---

src/BenchmarkDotNet/Disassemblers/Arm64Disassembler.cs
src/BenchmarkDotNet/Disassemblers/ClrMdV2Disassembler.cs
src/BenchmarkDotNet/Disassemblers/IntelDisassembler.cs

* Added some cleanup
* arm64 JIT in .NET 7 can generate a new form of constant loading using `adrp` / `add` instruction pair, so add handling that case
* Reordered address checks in `TryTranslateAddressToName` to first check for method addresses and only when it fails to look for `MethodDesc` / `MethodTable`. The `MethodDesc` is checked on arm64 only if the `i`sAddressPrecodeMD` is passed in, the `MethodTable` check is never made. The reason is that on arm64, we only try translate call / jump targets.

Added other arm64 constant form extraction plus other changes

---

src/BenchmarkDotNet/Extensions/StringAndTextExtensions.cs
src/BenchmarkDotNet/Parameters/ParameterInstance.cs
src/BenchmarkDotNet/Running/BenchmarkId.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliExecutor.cs
src/BenchmarkDotNet/Toolchains/Roslyn/Generator.cs
tests/BenchmarkDotNet.Tests/Exporters/ApprovedFiles/MarkdownExporterApprovalTests.GroupExporterTest.Escape_ParamsAndArguments.approved.txt
tests/BenchmarkDotNet.Tests/Exporters/MarkdownExporterApprovalTests.cs

This PR adds escaping the `Param` data for the exporters only. 
Currently, you can only pass `\t`, `\n`, other control characters throw an exception in the generated project). 
Try `Param["\0"] string Param` (In the linked PR below I fix it).
---
`Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(str, quote);` 
the naming is 10/10 😄. It escapes the non-displayed characters and emojis.
---
I don't escape the `column.ColumnName`, because that would require calling `.EscapeSpecialCharacter()` after every 'column.ColumName' (~20 times).
Fixes #1867
Fixes #1839

Escape Param data for the exporters

---

src/BenchmarkDotNet/Toolchains/CsProj/CsProjGenerator.cs

throw an exception when multiple benchmark projects with the same name are found

---

docs/articles/configs/jobs.md
docs/articles/samples/IntroLargeAddressAware.md
docs/articles/samples/toc.yml
samples/BenchmarkDotNet.Samples/IntroLargeAddressAware.cs
src/BenchmarkDotNet/Jobs/EnvironmentMode.cs
src/BenchmarkDotNet/Jobs/JobExtensions.cs
src/BenchmarkDotNet/Running/BenchmarkPartitioner.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliBuilder.cs
src/BenchmarkDotNet/Toolchains/LargeAddressAware.cs
src/BenchmarkDotNet/Toolchains/Roslyn/Builder.cs
tests/BenchmarkDotNet.IntegrationTests/LargeAddressAwareTest.cs

Fix #1469
It seems that BenchmarkDotNet does not support `Job.Dry.WithRuntime(CoreRuntime.Core60).WithPlatform(Platform.X86)`, so the feature becomes .Net Framework only. See also [ProcessorArchitectureTest](https://github.com/dotnet/BenchmarkDotNet/blob/master/tests/BenchmarkDotNet.IntegrationTests/ProcessorArchitectureTest.cs#L22) which skips this too.

Handle addresses larger than 2GB for 32-bit benchmarks #1469

---

src/BenchmarkDotNet/Running/UserInteraction.cs

Fixes #1709
```
Available Benchmarks:
#0 Test01
#1 Test02
```
if you write `0` it matches:
* Test01 (by benchmark class index)
* Test01 (class name contains `0`)
* Test02 (class name contains `0`)
This only applies to interactive mode, the `--filter` cmd option does not work with benchmark class index (`--filter 0` or `--filter #0`)

Fix user input matching

---

docs/articles/samples/IntroStaThread.md

Call out that support for `[STAThread]` was fixed in .NET Core 2.1.
Fix a couple minor grammatical errors.

Update StaThread intro documentation

---

samples/BenchmarkDotNet.Samples/IntroLargeAddressAware.cs
src/BenchmarkDotNet/Attributes/PerfCollectProfilerAttribute.cs
src/BenchmarkDotNet/BenchmarkDotNet.csproj
src/BenchmarkDotNet/Diagnosers/PerfCollectProfiler.cs
src/BenchmarkDotNet/Diagnosers/PerfCollectProfilerConfig.cs
src/BenchmarkDotNet/Jobs/EnvironmentMode.cs
src/BenchmarkDotNet/Portability/Libc.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommandExecutor.cs

fixes #2146
reported by @radical and @lewing in https://github.com/dotnet/performance/pull/2639#issuecomment-1279537243

remove dependency to Mono.Posix.NETStandard to unblock WASM benchmarks runs

---

src/BenchmarkDotNet/Configs/ImmutableConfigBuilder.cs

The author forgot to add this validator to the list of required validators in #908.
```C#
[DryJob]
public class MyClass
{
[ParamsAllValues] public int MyParam;
[Benchmark] public void MyMethod(){ }
}
```
The first command has `DefaultConfig`.
The second command has `ManualConfig.CreateMinimumViable()`.

Make ParamsAllValues validator mandatory

---

samples/BenchmarkDotNet.Samples/IntroWasm.cs
src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Loggers/LoggerExtensions.cs
src/BenchmarkDotNet/Reports/Summary.cs
src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs
src/BenchmarkDotNet/Running/BenchmarkRunnerDirty.cs
src/BenchmarkDotNet/Running/BuildPartition.cs
src/BenchmarkDotNet/Toolchains/CoreRun/CoreRunToolchain.cs
src/BenchmarkDotNet/Toolchains/CsProj/CsProjClassicNetToolchain.cs
src/BenchmarkDotNet/Toolchains/CsProj/CsProjCoreToolchain.cs
src/BenchmarkDotNet/Toolchains/IToolchain.cs
src/BenchmarkDotNet/Toolchains/InProcess.NoEmit/InProcessNoEmitToolchain.cs
src/BenchmarkDotNet/Toolchains/InProcess/InProcessToolchain.cs
src/BenchmarkDotNet/Toolchains/InProcess/InProcessValidator.cs
src/BenchmarkDotNet/Toolchains/Mono/MonoAotToolchain.cs
src/BenchmarkDotNet/Toolchains/MonoWasm/WasmToolchain.cs
src/BenchmarkDotNet/Toolchains/Roslyn/RoslynToolchain.cs
src/BenchmarkDotNet/Toolchains/Toolchain.cs
src/BenchmarkDotNet/Toolchains/ToolchainExtensions.cs
src/BenchmarkDotNet/Validators/ValidationError.cs
tests/BenchmarkDotNet.IntegrationTests/InProcessTest.cs
tests/BenchmarkDotNet.IntegrationTests/NugetReferenceTests.cs

Aims to fix #989, added a similar test to the one that is described in the issue.
After this PR, the summary will include validation errors and the output will look like this:
```
Standard Output: 
// Benchmark BenchmarkAllCases.InvokeOnceVoid: Dry(Platform=X86, Toolchain=InProcessToolchain, InvocationCount=16, IterationCount=1, LaunchCount=1, RunStrategy=ColdStart, UnrollFactor=16, WarmupCount=1)
// cannot be run in-process. Validation errors:
//    * Job Dry, EnvironmentMode.Platform was run as X64 (X86 expected). Fix your test runner options.
// Benchmark BenchmarkAllCases.InvokeOnceTaskAsync: Dry(Platform=X86, Toolchain=InProcessToolchain, InvocationCount=16, IterationCount=1, LaunchCount=1, RunStrategy=ColdStart, UnrollFactor=16, WarmupCount=1)
// cannot be run in-process. Validation …
```

adding validation errors when the benchmarks are unsupported

---

src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs
src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
tests/BenchmarkDotNet.Tests/ConfigParserTests.cs

For the GC team, doing an equitable comparison without evaluation overhead is important as we do want an equal number of GCs amongst comparands and the baseline we use to run our microbenchmarks with. 
This PR allows us to specify the flag to not run with evaluation overhead, a feature previously only available with the fluent API.

Added the ability to not run with Evaluation Overhead

---

docs/articles/configs/jobs.md
docs/articles/faq.md
docs/articles/guides/choosing-run-strategy.md
docs/articles/overview.md
docs/articles/samples/IntroExportJson.md
docs/articles/samples/IntroMonitoring.md
docs/articles/samples/IntroPercentiles.md
samples/BenchmarkDotNet.Samples/IntroColdStart.cs
samples/BenchmarkDotNet.Samples/IntroMonitoring.cs
samples/BenchmarkDotNet.Samples/IntroPercentiles.cs
samples/BenchmarkDotNet.Samples/IntroRatioSD.cs
samples/BenchmarkDotNet.Samples/IntroSetupCleanupIteration.cs
samples/BenchmarkDotNet.Samples/IntroSetupCleanupTarget.cs
samples/BenchmarkDotNet.Samples/IntroStatisticalTesting.cs
src/BenchmarkDotNet/Attributes/Jobs/SimpleJobAttribute.cs
src/BenchmarkDotNet/Engines/EngineGeneralStage.cs

Commit (https://github.com/dotnet/BenchmarkDotNet/commit/5e6e331b9fe1bbb5ef77c9bb025978e0dcf80aa4) did not change the name of TargetCount in the SimpleJob attribute. After the followup (https://github.com/dotnet/BenchmarkDotNet/commit/6d649b06aaa3bb7a818a1770fddc9dd4bcbe82d6) documentation was removed. This fix completes the rename.

Rename TargetCount to IterationCount in SimpleJob attribute

---

src/BenchmarkDotNet/Attributes/Columns/BaselineColumnAttribute.cs
src/BenchmarkDotNet/Attributes/Columns/LogicalGroupColumnAttribute.cs

We can remove attributes because **ColumnConfigBaseAttribute** already has
```C#
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Assembly)]
```

Remove allowMultiple=true from column attributes

---

src/BenchmarkDotNet/Engines/ExceptionsStats.cs
tests/BenchmarkDotNet.IntegrationTests/ExceptionDiagnoserTests.cs

When a Benchmark spawns multiple threads that throw Exceptions, FirstChanceException event handler is called concurrently. It must count Exceptions in a thread-safe way.
* Note: do not use lock keyword because that will influence Monitor lock contention count of ThreadingDiagnoser.
* Note: I changed type of ExceptionsCount property to long because there's no Interlocked.Increment overload for ulong. At the single call site, it is promoted to a double and divided by the number of total operations count to get the frequency.

Fix a threading issue in ExceptionDiagnoser #1736

---

docs/index.md

Fix #2167
I was unable to remove the vertical bar, so I make it important like for the other pages that show '<title> | BenchmarkDotNet' in the tab.
Give the main page a title. Then the tab displays 'Home | BenchmarkDotNet'.

Fix #2167 - Give main page a title. Then the tab displays 'Home | Be…'

---

src/BenchmarkDotNet/Loggers/AsyncProcessOutputReader.cs

The process.WaitForExit call doesn't guarantee that the last calls of ProcessOnOutputDataReceived and ProcessOnErrorDataReceived are processed. The subsequent call of reader.StopRead detaches the *DataReceived events, which leaves the output/error queues incomplete.
This race leads to flakiness of various tests (e.g., AllSetupAndCleanupMethodRunsForSpecificBenchmark).

Fix race in AsyncProcessOutputReader

---

src/BenchmarkDotNet/Analysers/Conclusion.cs
src/BenchmarkDotNet/Analysers/HideColumnsAnalyser.cs
src/BenchmarkDotNet/BenchmarkDotNet.csproj
src/BenchmarkDotNet/Columns/SizeUnit.cs
src/BenchmarkDotNet/Disassemblers/ClrMdV2Disassembler.cs
src/BenchmarkDotNet/Engines/GcStats.cs
src/BenchmarkDotNet/Engines/ThreadingStats.cs
src/BenchmarkDotNet/Environments/BenchmarkEnvironmentInfo.cs
src/BenchmarkDotNet/Environments/Runtimes/ClrRuntime.cs
src/BenchmarkDotNet/Environments/Runtimes/MonoAotLLVMRuntime.cs
src/BenchmarkDotNet/Environments/Runtimes/MonoRuntime.cs
src/BenchmarkDotNet/Environments/Runtimes/Runtime.cs
src/BenchmarkDotNet/Environments/Runtimes/WasmRuntime.cs
src/BenchmarkDotNet/Helpers/HashCode.cs
src/BenchmarkDotNet/Jobs/Argument.cs
src/BenchmarkDotNet/Jobs/EnvironmentVariable.cs
src/BenchmarkDotNet/Jobs/GcMode.cs
src/BenchmarkDotNet/Jobs/NugetReference.cs
src/BenchmarkDotNet/Jobs/NugetReferenceList.cs
src/BenchmarkDotNet/Reports/SummaryStyle.cs
src/BenchmarkDotNet/Running/BenchmarkPartitioner.cs
src/BenchmarkDotNet/Toolchains/CsProj/CsProjGenerator.cs
src/BenchmarkDotNet/Validators/ReturnValueValidator.cs
src/BenchmarkDotNet/Validators/ValidationError.cs

This simplifies the code, fixes 1 bug and improves performance.
If an additional dependency has any disadvantages, we can easily copy its files. This dependency consists of 2 files: `HashCode` and `BitOperations` (2 one-line methods)

Simplify GetHashCode()

---

src/BenchmarkDotNet/Running/BenchmarkSwitcher.cs

We need to filter out the mutator jobs:
https://github.com/dotnet/BenchmarkDotNet/blob/761590eb1a0ab813e4c53ccfa8903608ae31cb12/src/BenchmarkDotNet/Configs/ImmutableConfigBuilder.cs#L221-L222
before performing:
https://github.com/dotnet/BenchmarkDotNet/blob/21a29406406aeca1cdfa195fa86ac28d04ba8e33/src/BenchmarkDotNet/Running/BenchmarkSwitcher.cs#L157
As for configs like dotnet/performance (an instance of `IConfig` passed to switcher) and command like this:
```cmd
dotnet run -c Release -f net7.0 --filter *String.IndexOfAny --apples --profiler ETW --runtimes net7.0 net8.0 --iterationCount 20
```
I was getting 3 instead of 2 jobs and an error (for a perfectly valid command).
Related to https://github.com/dotnet/runtime/issues/77906 which I am trying to diagnose in automated way ;)

use ImmutableConfig when doing apples-to-apples comparison

---

src/BenchmarkDotNet/Configs/ImmutableConfigBuilder.cs
src/BenchmarkDotNet/Environments/BenchmarkEnvironmentInfo.cs
tests/BenchmarkDotNet.Tests/Configs/ImmutableConfigTests.cs
tests/BenchmarkDotNet.Tests/Running/JobRuntimePropertiesComparerTests.cs

Currently, the jobs with same reference are excluded, but if you use any `.With*` method, a new job will be created.
```C#
DefaultConfig.Instance
.AddJob(Job.Dry)
.AddJob(Job.Dry) // not added
.AddJob(Job.Dry.WithRuntime(CoreRuntime.Core70))
.AddJob(Job.Dry.WithRuntime(CoreRuntime.Core70));
```
```C#
// 1 job added
[DryJob]
[DryJob]
// 2 jobs added
[DryJob(RuntimeMoniker.Net70)]
[DryJob(RuntimeMoniker.Net70)]
```
https://github.com/dotnet/BenchmarkDotNet/blob/1fb1015556039664451dd101b4e2ef9501e03805/src/BenchmarkDotNet/Configs/ImmutableConfigBuilder.cs#L213-L218

Fix job filtering

---

src/BenchmarkDotNet/Running/BenchmarkRunnerDirty.cs
src/BenchmarkDotNet/Running/ClassicBenchmarkConverter.cs

https://github.com/dotnet/BenchmarkDotNet/issues/1677#issuecomment-1322017638

Deprecate RunSource/RunUrl methods

---

build/Program.cs
src/BenchmarkDotNet.Disassembler.x64/ClrMdV1Disassembler.cs
src/BenchmarkDotNet.Disassembler.x64/DataContracts.cs
src/BenchmarkDotNet/Disassemblers/Arm64Disassembler.cs
src/BenchmarkDotNet/Disassemblers/Arm64InstructionFormatter.cs
src/BenchmarkDotNet/Disassemblers/InstructionFormatter.cs
src/BenchmarkDotNet/Disassemblers/IntelDisassembler.cs
src/BenchmarkDotNet/Disassemblers/WindowsDisassembler.cs
tests/BenchmarkDotNet.IntegrationTests/BenchmarkSwitcherTest.cs
tests/BenchmarkDotNet.IntegrationTests/DisassemblyDiagnoserTests.cs
tests/BenchmarkDotNet.IntegrationTests/MemoryDiagnoserTests.cs
tests/BenchmarkDotNet.Tests/ConfigParserTests.cs

fix tests that were broken recently and went undetected (we updated the project to `net462` but were still running `net461`):
* default TFM when using CoreRun is now net8.0
* don't load Capstone.NET types when using disassembler to avoid strong signature error (https://github.com/9ee1/Capstone.NET/issues/36)
* Pass mandatory TFM to ClrMdV1 disassembler
cc @AndreyAkinshin

Fix Full Framework tests

---

src/BenchmarkDotNet/Toolchains/NativeAot/NativeAotToolchain.cs
src/BenchmarkDotNet/Toolchains/NativeAot/NativeAotToolchainBuilder.cs

NuGet.org should be the default feed for NativeAOT 7.0 ILCompiler

---

src/BenchmarkDotNet/Engines/Engine.cs
src/BenchmarkDotNet/Engines/GcStats.cs
src/BenchmarkDotNet/Portability/RuntimeInformation.cs
tests/BenchmarkDotNet.IntegrationTests/MemoryDiagnoserTests.cs

Sample results:
```ini
BenchmarkDotNet=v0.13.2.20221209-develop, OS=Windows 11 (10.0.22621.819)
AMD Ryzen Threadripper PRO 3945WX 12-Cores, 1 CPU, 24 logical and 12 physical cores
.NET SDK=8.0.100-alpha.1.22558.1
[Host]     : .NET 7.0.1 (7.0.122.56804), X64 RyuJIT AVX2
Job-TPQNZV : .NET 7.0.0 (7.0.22.42610) using MonoVM, X64 VectorSize=128
Runtime=Mono with .NET 7.0  Toolchain=Mono with .NET 7.0
```
|           Method |     Mean |     Error |    StdDev |   Gen0 |   Gen1 |   Gen2 | Allocated |
|----------------- |---------:|----------:|----------:|-------:|-------:|-------:|----------:|
| 'new byte[10kB]' | 5.751 us | 0.1126 us | 0.1156 us | 0.5798 | 0.5798 | 0.5798 |    9.8 KB |

Add support for MonoVM to MemoryDiagnoser

---

src/BenchmarkDotNet/Disassemblers/SameArchitectureDisassembler.cs
src/BenchmarkDotNet/Environments/Runtimes/CoreRuntime.cs
src/BenchmarkDotNet/Environments/Runtimes/MonoRuntime.cs
src/BenchmarkDotNet/Portability/RuntimeInformation.cs
src/BenchmarkDotNet/Toolchains/ToolchainExtensions.cs
tests/BenchmarkDotNet.IntegrationTests/MonoTests.cs

fixes https://github.com/dotnet/performance/issues/2787

Add support for .NET SDK that uses Mono instead CLR as a default VM

---

tests/BenchmarkDotNet.IntegrationTests/JitRuntimeValidationTest.cs
tests/BenchmarkDotNet.IntegrationTests/ProcessorArchitectureTest.cs

All tests are now passing on Linux arm64

tests can't assume x64 hardware

---

src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs
src/BenchmarkDotNet/Running/ConsoleTitler.cs

Fix IOException when Console window unavailable (#2237)

---

docs/articles/guides/getting-started.md
docs/articles/guides/how-to-run.md
docs/articles/overview.md
docs/index.md

- Adjust the instructions and examples to reflect more modern .NET
- Add a section about how to run the benchmarks (making sure you use Release)
- Fix the "Analyze" section, which was misleading, and add more useful information

Improve getting started guide

---

src/BenchmarkDotNet.Diagnostics.Windows/InliningDiagnoser.cs
src/BenchmarkDotNet.Diagnostics.Windows/JitDiagnoser.cs
src/BenchmarkDotNet.Diagnostics.Windows/JitStatsDiagnoser.cs
src/BenchmarkDotNet.Diagnostics.Windows/TailCallDiagnoser.cs
src/BenchmarkDotNet/Diagnosers/DiagnosersLoader.cs

I'm currently working on improving System.CommandLine (mainly design, but also perf).
One of the things unique about S.CL is that it's typically used just once, during process startup time. So what matters is the number of JIT compilations. I've implemented this simple diagnoser that prints simple JIT stats.
Sample usage:
```cmd
dotnet run -c Release -f net7.0 --filter *IntroBasic.Sleep --profiler jit
```
| Method |     Mean |    Error |   StdDev | Methods JITted | Methods Tiered | JIT allocated memory |
|------- |---------:|---------:|---------:|---------------:|---------------:|---------------------:|
|  Sleep | 15.53 ms | 0.034 ms | 0.032 ms |          1,102 |             15 |            221,736 B |
@AndyAyersMS @kunalspathak @stephentoub @EgorBo @kouvel I am opened to extending it, …

JitStatsDiagnoser

---

src/BenchmarkDotNet/Diagnosers/UnresolvedDiagnoser.cs

A fix for bug reported offline by @KrzysztofCwalina
otherwise CompositeDiagnoser.DisplayResults throws:
https://github.com/dotnet/BenchmarkDotNet/blob/e715d5bb63984fca65120d9a497f7d16395f9e5b/src/BenchmarkDotNet/Diagnosers/CompositeDiagnoser.cs#L47

UnresolvedDiagnoser needs to have an Id as well

---

docs/articles/configs/diagnosers.md
docs/articles/samples/IntroJitStatsDiagnoser.md
docs/articles/samples/toc.yml
samples/BenchmarkDotNet.Samples/IntroJitStatsDiagnoser.cs
src/BenchmarkDotNet.Diagnostics.Windows/Configs/JitStatsDiagnoserAttribute.cs

Based on https://github.com/dotnet/BenchmarkDotNet/pull/2243#issuecomment-1396794907
Also added documentation example for the diagnoser

Add JitStatsDiagnoserAttribute

---

build/global.json

We need https://github.com/dotnet/runtime/pull/79862 to fix our disassembler tests

bump SDK version to pick up .NET Runtime fix that should fix disassembler test issues

---

src/BenchmarkDotNet/Portability/RuntimeInformation.cs

This adds an Android specific way to get the NetCore version of the runtime being used via Environment.Version. This is necessary because Android apps don't uncompress the downloaded apk's which causes FileNotFound errors. To double check the precision, I ran this locally. After testing the Environment.Version vs the FileVersion from the PrivateCoreLib.dll, it does appears that the Environment.Version is not as precise. The results from the test were Envirornment.Version giving 7.0.3 while the FileVersion gave 7.0.323.6910.

Add Android specific GetNetCoreVersion Runtime Information capabilities.

---

src/BenchmarkDotNet/Loggers/AsyncProcessOutputReader.cs
src/BenchmarkDotNet/Loggers/CompositeLogger.cs

BenchmarkRunner uses a single instance of CompositeLogger, it passes it as ILogger to various components, which may use it in parallel.
We need to acquire the lock to avoid race conditions like #2125 and #2264
fixes #2264

log all access to CompositeLogger

---

src/BenchmarkDotNet/Environments/Runtimes/CustomRuntime.cs
src/BenchmarkDotNet/Toolchains/Executor.cs

Hello folks! This PR makes a small change to `Executor` to allow it be used for custom runtimes. The only downside I can see is that  the current `NotSupportedException` is probably a useful reminder when adding built-in runtimes, to ensure the correct behaviour is added or re-used here.
My use-case: I've written a custom runtime, and currently I need to copy/paste all of `Executor` and its supporting classes into my own codebase, which seems a bit redundant when all I really want to change are these 3 lines. Of course this particular setup for `ProcessStartInfo` is not applicable for every custom runtime - but at least it allows `Executor` to be used for those runtimes for which this is applicable.
But of course you'll have a better view of whether this change is a good idea and / or …

Allow custom runtimes to use Executor

---

src/BenchmarkDotNet/Running/UserInteraction.cs

Is this written somewhere? Looks pretty used
https://github.com/dotnet/BenchmarkDotNet/blob/f17453cef3a91ac90540dec1dcdee21725def6f8/src/BenchmarkDotNet/Running/UserInteraction.cs#L97-L103
FYI: 
It's not `string.Contains` but `IEnumerable.Contains`, so the input "a*b" or "**" doesn't work (as excepted).

Tell the user about the asterisk

---

docs/articles/samples/IntroComparableComplexParam.md
docs/articles/samples/toc.yml
samples/BenchmarkDotNet.Samples/IntroComparableComplexParam.cs
src/BenchmarkDotNet/Parameters/ParameterComparer.cs
tests/BenchmarkDotNet.Tests/ParameterComparerTests.cs

All the types in `PrimitiveComparer` are actually already `IComparable`, so I feel we can just remove this whole part altogether and have a single implementation that uses `IComparable`. Thoughts?
Not sure if just removing it will replicate current behavior, since it does some stuff with enums, and it also even does a string comparison (which feels weird to me since there's already a string comparison in `ParameterComparer.Compare`).
Closes #2301

IComparable for complex params

---

src/BenchmarkDotNet/Templates/CsProj.txt

Auto-generated .CSPROJ file now uses <CodeAnalysisTreatWarningsAsErrors>false</CodeAnalysisTreatWarningsAsErrors> to avoid failing toolchain compilation if consumer uses global Directory.Build.props has the same flag as true. Related issue #2312

Updated CsProj.txt, set CodeAnalysisTreatWarningsAsErrors=false

---

src/BenchmarkDotNet/BenchmarkDotNet.csproj
src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Running/BenchmarkSwitcher.cs
tests/BenchmarkDotNet.Tests/ConfigParserTests.cs

Only these methods do not contain the `args` parameter.
What order of parameters should be used? (I did not break backward compatibility)
```
BenchmarkSwitcher
RunAll(IConfig config, string[] args)  NEW
RunAllJoined(IConfig config, string[] args) NEW
Run(string[] args, IConfig config)
BenchmarkRunner
Run<T>(IConfig config, string[] args)
Run(Type, IConfig config, string[] args)
Run(Type[], IConfig config, string[] args)
Run(Assembly, IConfig config, string[] args)
```
I upgrade the library version because we need `settings.SkipDefault = true` (since version 2.7).

Add the args parameter to RunAll and RunAllJoined

---

docs/articles/guides/dotnet-new-templates.md
templates/install-from-source.bat
templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.CSharp/.template.config/template.json
templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.CSharp/Program.cs
templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.FSharp/.template.config/template.json
templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.VB/.template.config/template.json

The `framework` parameter must be of type `choice` (see the discussion with the VS developers below).
Currently:
VS doesn't display the templates at all.
Rider displays it with disabled dropdown but crashes when creating project.
The `choice` type means that we have to write all the supported frameworks by hand.
I've added all version frameworks, that have not expired end-of-life:
Also we can no longer use platform-specific TFM:
```
dotnet new benchmark -f net7.0-windows
```
But it's ok because `console` use a choice too, so we cannot create platform-specific TFM:
```
dotnet new console -f net7.0-windows
// displays an error
```
More details with screenshots: https://github.com/sayedihashimi/template-sample/issues/73
<details>
<summary>IDE screenshots</summary>
VS:
Rider:
</details>
fix …

Improve templates

---

build/common.props
templates/BenchmarkDotNet.Templates.csproj
templates/install-from-source.sh

Some automatization to reconcile BenchmarkDotNet version with default version in template
If it's good enough I will fix templates for VB and F# also. If not just close PR

adjust defaultBenchmarkDotNetVersion on build

---

src/BenchmarkDotNet/BenchmarkDotNet.csproj
tests/BenchmarkDotNet.IntegrationTests.ConfigPerAssembly/BenchmarkDotNet.IntegrationTests.ConfigPerAssembly.csproj
tests/BenchmarkDotNet.IntegrationTests.CustomPaths/BenchmarkDotNet.IntegrationTests.CustomPaths.csproj
tests/BenchmarkDotNet.IntegrationTests.DisabledOptimizations/BenchmarkDotNet.IntegrationTests.DisabledOptimizations.csproj
tests/BenchmarkDotNet.IntegrationTests.EnabledOptimizations/BenchmarkDotNet.IntegrationTests.EnabledOptimizations.csproj
tests/BenchmarkDotNet.IntegrationTests.Static/BenchmarkDotNet.IntegrationTests.Static.csproj
tests/BenchmarkDotNet.IntegrationTests/BenchmarkDotNet.IntegrationTests.csproj
tests/BenchmarkDotNet.Tests/BenchmarkDotNet.Tests.csproj

I got the wrong version of a nuget package in #2352.

Fix netcoreapp3.0 builds

---

src/BenchmarkDotNet/Parameters/ParameterComparer.cs
tests/BenchmarkDotNet.Tests/ParameterComparerTests.cs

Currently, I'm doing a specific check for the particular exception that occurs in the linked issue (there's no better way currently for the reasons discussed in the issue). We could also just catch any exception in `CompareTo` as an alternative.
Closes #2346

IComparable fallback for Tuple/ValueTuple

---

src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
tests/BenchmarkDotNet.Tests/ConfigParserTests.cs
tests/BenchmarkDotNet.Tests/TypeFilterTests.cs

Fix regression in parsing arguments with spaces Closes #2373

---

src/BenchmarkDotNet/Helpers/Reflection.Emit/MethodBuilderExtensions.cs
src/BenchmarkDotNet/Portability/CodeGen.cs
src/BenchmarkDotNet/Templates/BenchmarkType.txt
src/BenchmarkDotNet/Toolchains/InProcess/Emit/Implementation/Emitters/RunnableEmitter.cs
src/BenchmarkDotNet/Toolchains/InProcess/NoEmit/BenchmarkAction.cs
src/BenchmarkDotNet/Toolchains/InProcess/NoEmit/BenchmarkActionFactory_Implementations.cs
src/BenchmarkDotNet/Toolchains/InProcess/NoEmit/InProcessNoEmitRunner.cs
tests/BenchmarkDotNet.IntegrationTests/InProcessTest.cs

Follow-up to #1935, fixes #1934 for in-process toolchains.

`AggressiveOptimization` in `InProcess` toolchains

---

src/BenchmarkDotNet/Analysers/ZeroMeasurementHelper.cs
src/BenchmarkDotNet/Properties/AssemblyInfo.cs
tests/BenchmarkDotNet.IntegrationTests.ManualRunning/BenchmarkDotNet.IntegrationTests.ManualRunning.csproj
tests/BenchmarkDotNet.IntegrationTests.ManualRunning/ExpectedBenchmarkResultsTests.cs
tests/BenchmarkDotNet.IntegrationTests/BenchmarkTestExecutor.cs

Add expected results tests

---

src/BenchmarkDotNet/Toolchains/Toolchain.cs

Fixes #2378
Changed validation error message from:
```text 
"BenchmarkDotNet requires dotnet cli to be installed"
```
to
```text
"BenchmarkDotNet requires dotnet sdk to be installed"
```

[chore]: fix error message

---

src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Diagnosers/PerfCollectProfiler.cs
src/BenchmarkDotNet/Toolchains/CsProj/CsProjClassicNetToolchain.cs
tests/BenchmarkDotNet.Tests/ConfigParserTests.cs

For consistency with the validation error message when dotnet SDK is not installed in the default location.

Support `--cli` argument for `CsProjClassicNetToolchain`

---

src/BenchmarkDotNet/Reports/Measurement.cs

A recent change removed this import which is only used on debug builds, this PR adds the import back.

Fix missing import on Debug build

---

src/BenchmarkDotNet/Diagnosers/PerfCollectProfiler.cs

```cmd
sudo dotnet run -c Release -f net7.0 --filter '*perfcollect*' --corerun ~/projects/runtime/artifacts/bin/testhost/net8.0-linux-Release-x64/shared/Microsoft.NETCore.App/8.0.0/corerun
```
fixes #2382

perfcollect: don't restore symbols for local builds

---

samples/BenchmarkDotNet.Samples.Forms/BenchmarkDotNet.Samples.Forms.csproj
src/BenchmarkDotNet/Running/ConsoleTitler.cs

Previously on the Android platform, and possibly other platforms, the ConsoleTitler threw a PlatformNotSupportedException when checking if console output is redirected and prevented benchmarks from running. This is fixed by catching and ignoring the PlatformNotSupportedException. The try-catch around Console.Title is still used to determine if the platform supports console retitling. This seemed more appropriate in the event that the platform doesn't support checking if output is redirected but supports retitling, even though it is unlikely.
Additionally removes the Forms sample project's Immutable package reference. BenchmarkDotNet has a dependency on Immutable 5.0.0 and this reference was causing package downgrade warnings that were treated as errors:
```
error NU1605: Warning As Error: …
```

Fix PlatformNotSupportedException thrown on Android in ConsoleTitler

---

src/BenchmarkDotNet/Configs/ImmutableConfigBuilder.cs
tests/BenchmarkDotNet.Tests/Configs/ImmutableConfigTests.cs

Changed merging of exporters to check for duplicates by exporter.Name instead of the System.Type.
Added a test to verify that two MarkdownExporters with different named (GitHub and Atlassian) are accepted and both present in the final list (count is 2).
The original that removes duplicates still passes.
Fixes #2394

Issue2394 multiple markdown exporters not possible even with different names

---

src/BenchmarkDotNet/Loggers/StreamLogger.cs
src/BenchmarkDotNet/Loggers/TextLogger.cs
src/BenchmarkDotNet/Loggers/TextWriterLogger.cs

Refactor out base TextLogger from StreamLogger

---

src/BenchmarkDotNet/Disassemblers/Arm64Disassembler.cs
src/BenchmarkDotNet/Disassemblers/IntelDisassembler.cs

The call counting stub, stub precode and fixup precode were modified in .NET 8 to have larger size of the interleaved code / data blocks. The stub decoder in the intel and arm64 disassemblers need to be updated to take that into account.

Update stub decoding for .NET 8 for disassemblers

---

src/BenchmarkDotNet/Analysers/Conclusion.cs
src/BenchmarkDotNet/Analysers/ZeroMeasurementHelper.cs
src/BenchmarkDotNet/Attributes/Filters/AotFilterAttribute.cs
src/BenchmarkDotNet/Attributes/Jobs/SimpleJobAttribute.cs
src/BenchmarkDotNet/Characteristics/CharacteristicObject.cs
src/BenchmarkDotNet/Characteristics/CharacteristicObject`1.cs
src/BenchmarkDotNet/Characteristics/Characteristic`1.cs
src/BenchmarkDotNet/Code/ArrayParam.cs
src/BenchmarkDotNet/Code/CodeGenerator.cs
src/BenchmarkDotNet/Jobs/Job.cs
src/BenchmarkDotNet/Jobs/JobMode`1.cs

Fixed some more nullability warnings.
I am going to continue doing this small fixes in this brunch. Feel free to review and merge it at any time to avoid conflicts.

Nullability In BenchmarkDotNet project

---

src/BenchmarkDotNet/Toolchains/ToolchainExtensions.cs

Default to RoslynToolchain

---

src/BenchmarkDotNet/Configs/ConfigExtensions.cs
src/BenchmarkDotNet/Configs/ManualConfig.cs

Also add params support for `AddEventProcessor` to be consistent with other addable things.
This addresses additional feedback from @mawosoft on the previous PR: https://github.com/dotnet/BenchmarkDotNet/pull/2420#issuecomment-1729756976

Fix Event Processors not being copied in ManualConfig.Add

---

src/BenchmarkDotNet/Disassemblers/Arm64Disassembler.cs
src/BenchmarkDotNet/Disassemblers/ClrMdV2Disassembler.cs
src/BenchmarkDotNet/Disassemblers/DisassemblyDiagnoser.cs
src/BenchmarkDotNet/Disassemblers/IntelDisassembler.cs

https://github.com/dotnet/runtime/pull/90794
Fixes #2404

Fix linux crash from disassembler

---

tests/BenchmarkDotNet.IntegrationTests.ManualRunning.MultipleFrameworks/BenchmarkDotNet.IntegrationTests.ManualRunning.MultipleFrameworks.csproj

Treat warnings not as errors in manual test project

---

templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.CSharp/.template.config/template.json
templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.FSharp/.template.config/template.json
templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.VB/.template.config/template.json

use coalesce instead of join

---

src/BenchmarkDotNet/Toolchains/CsProj/CsProjGenerator.cs
tests/BenchmarkDotNet.Tests/CsProjGeneratorTests.cs

feat: set RuntimeHostConfigurationOption on generated project

---

NuGet.Config
src/BenchmarkDotNet.Annotations/Jobs/RuntimeMoniker.cs
src/BenchmarkDotNet.Diagnostics.dotTrace/DotTraceDiagnoser.cs
src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Environments/Runtimes/CoreRuntime.cs
src/BenchmarkDotNet/Environments/Runtimes/MonoRuntime.cs
src/BenchmarkDotNet/Environments/Runtimes/NativeAotRuntime.cs
src/BenchmarkDotNet/Extensions/RuntimeMonikerExtensions.cs
src/BenchmarkDotNet/Toolchains/CsProj/CsProjCoreToolchain.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/NetCoreAppSettings.cs
src/BenchmarkDotNet/Toolchains/Mono/MonoToolchain.cs
src/BenchmarkDotNet/Toolchains/NativeAot/NativeAotToolchain.cs
src/BenchmarkDotNet/Toolchains/ToolchainExtensions.cs
tests/BenchmarkDotNet.Tests/ConfigParserTests.cs

fixes #2455
```cmd
dotnet run -c Release -f net8.0 --filter *IntroBasic* --job dry --runtimes net8.0 net9.0 nativeaot8.0 nativeaot9.0 mono8.0 mono9.0
```
I've verified that all new monikers work and do what is expected (build as net9.0):
And that CoreRun Toolchain works as expected too:

implement full .NET 9 support

---

src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Toolchains/NativeAot/Generator.cs

Use "native" for .NET 8, don't use "serialize" for .NET 7.
fixes #2060
fixes #2463
cc @MichalStrehovsky

Use "native" for .NET 8, don't use "serialize" for .NET 7

---

.github/workflows/run-tests.yaml
build/BenchmarkDotNet.Build/BenchmarkDotNet.Build.csproj
build/BenchmarkDotNet.Build/BuildContext.cs
build/BenchmarkDotNet.Build/Program.cs
build/BenchmarkDotNet.Build/Runners/BuildRunner.cs
build/BenchmarkDotNet.Build/Runners/UnitTestRunner.cs
build/build.ps1
build/sdk/global.json
samples/BenchmarkDotNet.Samples.FSharp/BenchmarkDotNet.Samples.FSharp.fsproj
samples/BenchmarkDotNet.Samples/BenchmarkDotNet.Samples.csproj
tests/BenchmarkDotNet.IntegrationTests.ConfigPerAssembly/BenchmarkDotNet.IntegrationTests.ConfigPerAssembly.csproj
tests/BenchmarkDotNet.IntegrationTests.DisabledOptimizations/BenchmarkDotNet.IntegrationTests.DisabledOptimizations.csproj
tests/BenchmarkDotNet.IntegrationTests.EnabledOptimizations/BenchmarkDotNet.IntegrationTests.EnabledOptimizations.csproj
tests/BenchmarkDotNet.IntegrationTests.FSharp/BenchmarkDotNet.IntegrationTests.FSharp.fsproj
tests/BenchmarkDotNet.IntegrationTests.ManualRunning.MultipleFrameworks/BenchmarkDotNet.IntegrationTests.ManualRunning.MultipleFrameworks.csproj
tests/BenchmarkDotNet.IntegrationTests.ManualRunning/BenchmarkDotNet.IntegrationTests.ManualRunning.csproj
tests/BenchmarkDotNet.IntegrationTests.Static/BenchmarkDotNet.IntegrationTests.Static.csproj
tests/BenchmarkDotNet.IntegrationTests.VisualBasic/BenchmarkDotNet.IntegrationTests.VisualBasic.vbproj
tests/BenchmarkDotNet.IntegrationTests/BenchmarkDotNet.IntegrationTests.csproj
tests/BenchmarkDotNet.IntegrationTests/BuildTimeoutTests.cs
tests/BenchmarkDotNet.IntegrationTests/DisassemblyDiagnoserTests.cs
tests/BenchmarkDotNet.IntegrationTests/JitRuntimeValidationTest.cs
tests/BenchmarkDotNet.IntegrationTests/LargeAddressAwareTest.cs
tests/BenchmarkDotNet.IntegrationTests/MemoryDiagnoserTests.cs
tests/BenchmarkDotNet.IntegrationTests/MonoTests.cs
tests/BenchmarkDotNet.IntegrationTests/MultipleRuntimesTest.cs
tests/BenchmarkDotNet.Tests/BenchmarkDotNet.Tests.csproj
tests/BenchmarkDotNet.Tests/ConfigParserTests.cs

Currently it's just a draft. It would be nice to have for #2412, where we would not need to use reflection to figure out whether AVX512 is supported.

update SDK to .NET 8

---

docs/articles/configs/diagnosers.md
src/BenchmarkDotNet/Engines/GcStats.cs
tests/BenchmarkDotNet.IntegrationTests/MemoryDiagnoserTests.cs

This enables MemoryDiagnoser on Legacy Mono (since it provides `GetAllocatedBytesForCurrentThread`) and makes it more resilient to errors.

Enable MemoryDiagnoser on Legacy Mono

---

templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.CSharp/.template.config/template.json
templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.FSharp/.template.config/template.json
templates/templates/BenchmarkDotNet.BenchmarkProjectTemplate.VB/.template.config/template.json

This PR updates the default framework on the templates to net8.0 which is a LTS release (was net6.0).
Useful to bench newer C# features, like UTF-8 string literals.

Update the default framework on the templates to net8.0

---

src/BenchmarkDotNet/Characteristics/CharacteristicObject.cs
tests/BenchmarkDotNet.Tests/ConfigParserTests.cs
tests/BenchmarkDotNet.Tests/Configs/JobTests.cs

[Bug Fix] Custom SimpleJob Id ignored

---

src/BenchmarkDotNet.TestAdapter/BenchmarkCaseExtensions.cs

This bug is causing the test adapter to fail to load on the dotnet/performance repository as we have some benchmarks where the test and class name are identical but live in different namespaces. Adding the namespace to the test ID resolves the issue.

Fix benchmarks with same class but different namespace having same ID

---

docs/articles/configs/toolchains.md

Updated non-default dotnet cli path example.
I was receiving compiler warnings for `Add` and `With` when using the provided doc example. I have updated them to the newer `AddJob` and `WithToolchain` methods.

Update toolchain docs

---

src/BenchmarkDotNet/Validators/DotNetSdkVersionValidator.cs

These monikers were missed in the recent SDK Validation feature.

Add support for wasm and Mono AOT LLVM monikers to SDK Validator

---

src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
src/BenchmarkDotNet/Environments/Runtimes/MonoAotLLVMRuntime.cs
src/BenchmarkDotNet/Toolchains/Executor.cs
src/BenchmarkDotNet/Toolchains/MonoAotLLVM/MonoAotLLVMGenerator.cs

Similar to what broke with the WASM runs, it seems that Mono AOT LLVM also will always append the `publish` directory onto the end of the `OutDir` and `OutputPath` that we pass in, so we need to remove it from the end of those paths and then append it the executable path and working directory.
~~We are doing some more testing on this first before it can be ready to merge however, but this seems like the likely fix.~~
Testing is done, this PR is ready for a merge.

Fix Mono AOT LLVM

---

src/BenchmarkDotNet/Engines/Engine.cs

stackalloc in separate method

---

src/BenchmarkDotNet/Exporters/MarkdownExporter.cs
tests/BenchmarkDotNet.Tests/Exporters/MarkdownExporterVerifyTests.cs
tests/BenchmarkDotNet.Tests/Exporters/VerifiedFiles/MarkdownExporterVerifyTests.GroupExporterTest_HideColumns_TableMarkDown.verified.txt
tests/BenchmarkDotNet.Tests/Mocks/MockFactory.cs

Fix -  incorrect table markdown #2545

Fix -  incorrect table markdown #2545

---

README.md

Made simplicity verbiage more inclusive

Updated readme to make it clear that experienced performance engineers are also welcome

---

docs/articles/samples/IntroSummaryStyle.md
samples/BenchmarkDotNet.Samples/IntroSummaryStyle.cs

Docs for SummaryStyle

---

BenchmarkDotNet.sln
src/BenchmarkDotNet.Exporters.Plotting/BenchmarkDotNet.Exporters.Plotting.csproj
src/BenchmarkDotNet.Exporters.Plotting/ScottPlotExporter.cs
tests/BenchmarkDotNet.Exporters.Plotting.Tests/BenchmarkDotNet.Exporters.Plotting.Tests.csproj
tests/BenchmarkDotNet.Exporters.Plotting.Tests/ScottPlotExporterTests.cs

This adds a new project called BenchmarkDotNet.Exporters.Plotting.
Currently just supports Bar Plots with configurable options for Width, Height and whether to RotateLabels (for large bar labels defaults to true).
Example Bar Plot:
NOTE: Currently build gets an error about strong naming?

Initial ScottPlotExporter with just Bar Plot and Unit Tests

---

src/BenchmarkDotNet.Exporters.Plotting/ScottPlotExporter.cs

Fixes #2611 missing filtering for workload mode and iteration stage `Result` in ScottPlotExporter

Fix #2611 - Add Iteration mode and stage filtering to ScottPlotExporter

---

src/BenchmarkDotNet.Exporters.Plotting/ScottPlotExporter.cs
tests/BenchmarkDotNet.Exporters.Plotting.Tests/ScottPlotExporterTests.cs
tests/BenchmarkDotNet.Tests/Mocks/MockFactory.cs

This feature adds Box Plot support to the ScottPlotExporter.
This plot is enabled by default and can be disabled by setting `exporter.IncludeBoxPlot = false;`
Also improved readability by setting most font sizes to 14 by default, this is customisable via `exporter.FontSize = 20;` and `exporter.TitleFontSize = 40;`
A new set of mock report test data was needed to properly test box plots with biased distributions.
NOTE: This change includes the fix for #2611

Feature: Box Plot support for ScottPlotExporter

---

src/BenchmarkDotNet/Toolchains/NativeAot/Generator.cs

* `llcOptimizationPreference` was renamed to `OptimizationPreference` and became supported in .NET 8 (or maybe .NET 7, it doesn't matter)
* `IlcGenerateStackTraceData` is now `StackTraceSupport` and supported. (Also got renamed in .NET 8 or maybe in 7 already.)
I'm leaving the old names of properties for backcompat. We could also delete them. I don't know how much BDN cares about .NET versions that are out of support.
The last one, `IlcGenerateCompleteTypeMetadata` is unsupported, we don't test it, it's a mode for troubleshooting trimming issues for people who ignore trimming warnings. I don't think BDN should be setting this. You'll only find bugs (https://github.com/dotnet/runtime/issues/106439). So deleting that. Not deleting the API because it looks to be a public API.

Clean up unsupported native AOT flags

---

src/BenchmarkDotNet/BenchmarkDotNet.csproj
src/BenchmarkDotNet/Disassemblers/Arm64Disassembler.cs
src/BenchmarkDotNet/Disassemblers/ClrMdV3Disassembler.cs
src/BenchmarkDotNet/Disassemblers/IntelDisassembler.cs
src/BenchmarkDotNet/Disassemblers/SameArchitectureDisassembler.cs

Fixes #2383 
I left the x86/x64 disassemblers on v1, those can be updated separately.
Also, as discussed in #2383, this breaks netcoreapp3.0 and older, so we should probably release this in 0.14.0.

Update clrmd to 3.1

---

samples/BenchmarkDotNet.Samples/IntroEnvVars.cs
src/BenchmarkDotNet/Extensions/ProcessExtensions.cs
tests/BenchmarkDotNet.IntegrationTests/MemoryDiagnoserTests.cs

The configuration system in coreclr and mono started supporting `DOTNET_` prefix in net6.0. Using `DOTNET_` is preferred because [it has precedence](https://github.com/dotnet/runtime/blob/a3d1e1cdb61a65b64246dee45998f2701c8987b8/src/coreclr/inc/clrconfignocache.h#L81) over `COMPlus_`.

Add DOTNET_ environment vars

---

src/BenchmarkDotNet/Validators/DotNetSdkVersionValidator.cs

This is an alternative approach that was discussed in #2641 to account for backwards compatibility in the SDK (e.g. that you can target previous versions from a later version of the SDK). I have verified locally on my machine that with this BDN installed, that we can run the wasm benchmarks with `--runtimes wasmnet90` passed in while having a .NET 10 SDK installed via the changes in https://github.com/dotnet/runtime/pull/106599 so merging this and using it in the dotnet/performance repository should get everything unblocked.

Change .NET SDK Validator to account for backwards compatibility

---

src/BenchmarkDotNet/Environments/Runtimes/CoreRuntime.cs
src/BenchmarkDotNet/Validators/DotNetSdkVersionValidator.cs

Unfortunately there was a bug introduced in https://github.com/dotnet/BenchmarkDotNet/pull/2645 that I missed which this PR will fix. Essentially if you use `--runtimes monoaotllvm` or `--runtimes wasm`, it would actually return `new Version(9, 0, 0)` because it defers to `CoreRuntime.TryGetVersion()` to get the version. The code that parsed the output of `dotnet --list-sdks` was only looking at the major and minor versions, and so the comparison of `new Version(9, 0, 0) <= new Version(9, 0)` was returning false. With this change we will read the full version string including the feature band/patch version.
In the dotnet/runtime performance tests we don't use `--runtimes wasm` but we do use `--runtimes monoaotllvm` to run the Mono AOT benchmarks, so this will fix that one. I'm doing some …

Get full parsable version part in .NET SDK Validator

---

src/BenchmarkDotNet/Analysers/BaselineCustomAnalyzer.cs

Went through #2591 and tried to improve the warning message here - taking a look at what code paths can cause this warning, I see that in `BaseLineCustomColumn.ResultsAreInvalid` it checks for whether the baseline / benchmark (or the results of) was null, and a check for `!CanBeInverted` on the baseline which checks if it's too close to zero. 
```c#
internal static bool ResultsAreInvalid(Summary summary, BenchmarkCase benchmarkCase, BenchmarkCase? baseline)
{
return baseline == null ||
summary[baseline] == null ||
summary[baseline].ResultStatistics == null ||
!summary[baseline].ResultStatistics.CanBeInverted() ||
summary[benchmarkCase] == null ||
summary[benchmarkCase].ResultStatistics == null;
}
```
```c#
public bool CanBeInverted() => Min > 1e-9;
```
First issue here, let me know if …

improve BaselineCustomAnalyzer warning message, fixes #2591

---

samples/BenchmarkDotNet.Samples.FSharp/BenchmarkDotNet.Samples.FSharp.fsproj
src/BenchmarkDotNet.Annotations/BenchmarkDotNet.Annotations.csproj
src/BenchmarkDotNet.Diagnostics.dotMemory/BenchmarkDotNet.Diagnostics.dotMemory.csproj
src/BenchmarkDotNet.Diagnostics.dotTrace/BenchmarkDotNet.Diagnostics.dotTrace.csproj
tests/BenchmarkDotNet.Exporters.Plotting.Tests/BenchmarkDotNet.Exporters.Plotting.Tests.csproj
tests/BenchmarkDotNet.IntegrationTests.ManualRunning.MultipleFrameworks/BenchmarkDotNet.IntegrationTests.ManualRunning.MultipleFrameworks.csproj
tests/BenchmarkDotNet.IntegrationTests.ManualRunning/BenchmarkDotNet.IntegrationTests.ManualRunning.csproj
tests/BenchmarkDotNet.IntegrationTests/BenchmarkDotNet.IntegrationTests.csproj
tests/BenchmarkDotNet.Tests/BenchmarkDotNet.Tests.csproj
tests/BenchmarkDotNet.Tests/ConfigParserTests.cs

I've tried to build and run our samples today and got following errors:
```log
PS D:\projects\BenchmarkDotNet\samples\BenchmarkDotNet.Samples> dotnet run -c Release -f net8.0 --filter *Counters* --list flat
C:\Program Files\dotnet\sdk\9.0.100-preview.7.24402.8\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(187,5): warning NETSDK1215: Targeting .NET Standard prior to 2.0 is no longer recommended. See https://aka.ms/dotnet/dotnet-standard-guidance for more details.
D:\projects\BenchmarkDotNet\src\BenchmarkDotNet.Annotations\BenchmarkDotNet.Annotations.csproj : error NU1903: Warning As Error: Package 'System.Text.RegularExpressions' 4.3.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-cmhx-cq75-c4mj …
```

Fix known high severity vulnerabilities

---

src/BenchmarkDotNet.Diagnostics.Windows/EtwDiagnoser.cs
src/BenchmarkDotNet.Diagnostics.Windows/EtwProfiler.cs
src/BenchmarkDotNet.Diagnostics.Windows/Sessions.cs
src/BenchmarkDotNet/Helpers/DisposeAtProcessTermination.cs
src/BenchmarkDotNet/Helpers/TaskbarProgress.cs
src/BenchmarkDotNet/Running/ConsoleTitler.cs
src/BenchmarkDotNet/Running/PowerManagementApplier.cs

Set ConsoleCancelEventArgs.Cancel to true so that Benchmark process continues and PowerPlan is reverted at end of aborted Benchmark.
Note that at Ctrl-C (or Ctrl-Break) press, current benchmark fails (as all its processes are killed). The [main run loop](../blob/f8e0a5c23883fa6ea4a975cd08a0071c4648472c/src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs#L161) continues running remaining benchmarks.
As it would (imho) require some complicated code to set `stop` to true at Ctrl-C press, I decided to document current behavior.
(If you do like to have all benchmarks aborted at Ctrl-C press, let me know and I'll implement such behavior)

Prevent premature end of the Benchmark process at Ctrl-C, fixes #2483

---

src/BenchmarkDotNet/Toolchains/NativeAot/Generator.cs

See: https://github.com/dotnet/BenchmarkDotNet/issues/2428#issuecomment-2477793449
I'm happy to add tests here, but I didn't see any good examples of similar tests currently present. I ran some of the integration tests and checked the outputs and those matched expectations.
relates to #2428

Native AOT projects should also copy SettingsWeWantToCopy

---

docs/articles/configs/diagnosers.md
docs/articles/configs/jobs.md
docs/articles/configs/toolchains.md

Doc cleanup. Removing obsolete API usage in the articles.

Remove obsolete API usage in articles

---

src/BenchmarkDotNet/Toolchains/InProcess/Emit/Implementation/Emitters/RunnableEmitter.cs
tests/BenchmarkDotNet.IntegrationTests/InProcessEmitTest.cs

Fix async GlobalSetup/Cleanup with InProcessEmit toolchain

---

src/BenchmarkDotNet/Engines/HostSignal.cs
src/BenchmarkDotNet/Loggers/Broker.cs
src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliExecutor.cs
src/BenchmarkDotNet/Toolchains/Executor.cs

I got this feature request from the VS Profiler Team
The code sample I've used:
```csharp
using BenchmarkDotNet.Analysers;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Configs;
using BenchmarkDotNet.Diagnosers;
using BenchmarkDotNet.Engines;
using BenchmarkDotNet.Environments;
using BenchmarkDotNet.Exporters;
using BenchmarkDotNet.Jobs;
using BenchmarkDotNet.Loggers;
using BenchmarkDotNet.Reports;
using BenchmarkDotNet.Running;
using BenchmarkDotNet.Validators;
using System;
using System.Collections.Generic;
namespace BenchmarkDotNet.Samples
{
[Config(typeof(ConfigWithSuspendEnvVars))]
public class IntroProcessResume
{
// DOTNET_DefaultDiagnosticPortSuspend=1
private class ConfigWithSuspendEnvVars : ManualConfig
{
public ConfigWithSuspendEnvVars()
{ …
```

add HostSignal.AfterProcessStart to allow the users to obtain ID of a process that was started suspended

---

src/BenchmarkDotNet/Extensions/RuntimeMonikerExtensions.cs

Added support for `RuntimeMoniker.NativeAot90` in the `RuntimeMonikerExtensions.cs` file, which returns `NativeAotRuntime.Net90`.

Missing dotnet 9.0 support.

---

src/BenchmarkDotNet/Toolchains/InProcess/NoEmit/InProcessNoEmitRunner.cs

Supports benchmark methods with `void` or `Task` as return type.

Basic support of `InProcessNoEmitRunner` for NativeAOT.

---

src/BenchmarkDotNet.Exporters.Plotting/BenchmarkDotNet.Exporters.Plotting.csproj
src/BenchmarkDotNet.Exporters.Plotting/ScottPlotExporter.cs

Hey, I noticed that this project was using ScottPlot 5.0.25, which causes issues for me trying to benchmark ScottPlot (I'm a ScottPlot maintainer). Without csproj trickery with package aliases we're not able to reference two versions of a package in one project, it'll just pick the newer one, which is incompatible in some respects with 5.0.25.
There are some breaking changes, since despite my misgivings we don't use SemVer (I'm a ScottPlot maintainer). These are mostly all fairly trivial field renames. For these I believe they are just marked obsolete, not removed yet.
I don't know if you would consider it a breaking change to update ScottPlot versions, I think it only would be if the project under test was also using ScottPlot. In that case, I think for most of these issues you can …

Exporters.Plotting: Move to ScottPlot 5.0.54

---

src/BenchmarkDotNet.Annotations/Attributes/ParamsAttribute.cs

This PR change `ParamsAttribute::Values` setter accessibility to `protected`.
There is similar request about 5 years ago (#1415)
**Background**
I want to adjust benchmark parameters per benchmarks by using attribute that inherit `ParamsAttribute`.
But currently `ParamsAttribute` derived class can't set `Values` property.
And It can't set dynamic parameters via `base()` constructor parameter.
As a workaround, It can use [ParamsSourceAttribute] instead.
But in this case, it need to define source per benchmark class.

Allow to set ParamsAttribute's values from derived class

---

src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommandResult.cs

Always fail if dotnet command failed

---

src/BenchmarkDotNet/Configs/ConfigOptions.cs
src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs

This PR intended to fix #2721
1. Add `DisableParallelBuild` flag to `ConfigOptions`.
2. Modify `BenchmarkRunnerClean::Run`.
2.1. Add `BuildSequential` method that build project in sequentially.
2.2. Add logics to check `DisableParallelBuild` option.  If any of benchmarks contains `DisableParallelBuild` flag. Use sequential build path instead of parallel build path.
**Test** 
I've manually confirmed that `sequential build` path is called when specifying `WithOptions(ConfigOptions.DisableParallelBuild);` on benchmark config.

feat: Add option to disable parallel build

---

src/BenchmarkDotNet/Running/BuildPartition.cs
tests/BenchmarkDotNet.IntegrationTests/InProcessEmitTest.cs

Found while trying to run manual tests. Introduced in #2423

Fix Windows path too long

---

src/BenchmarkDotNet/Environments/HostEnvironmentInfo.cs

The nullability of HostEnvironmentInfo's Cpu property was mistakenly going unnoticed. This caused a null reference exception in the `ZeroMeasurementAnalyser`. I corrected this by making it nullable and checking for it in the analyser. Preventing it from breaking for all not-yet supported OS `CpuDetectors`

Fix #2740: Use CpuInfo.Unknown if CpuDetector.Detect() does not find supported OS

---

src/BenchmarkDotNet/Helpers/DisposeAtProcessTermination.cs

This is a simple issue in which a platform exclusive event is always being subscribed to regardless of platform. This first checks that it isn't one of the unsupported OS' defined for that event.
Also changed constructor's access modifier to protected because the class is abstract

Fix #2739: OS check for platform specific event

---

build/common.props
samples/BenchmarkDotNet.Samples.FSharp/BenchmarkDotNet.Samples.FSharp.fsproj
samples/BenchmarkDotNet.Samples/BenchmarkDotNet.Samples.csproj
samples/BenchmarkDotNet.Samples/IntroNativeMemory.cs
samples/BenchmarkDotNet.Samples/IntroNuGet.cs
src/BenchmarkDotNet.Diagnostics.Windows/BenchmarkDotNet.Diagnostics.Windows.csproj
src/BenchmarkDotNet.Diagnostics.dotMemory/BenchmarkDotNet.Diagnostics.dotMemory.csproj
src/BenchmarkDotNet.Diagnostics.dotTrace/BenchmarkDotNet.Diagnostics.dotTrace.csproj
src/BenchmarkDotNet.Disassembler.x64/BenchmarkDotNet.Disassembler.x64.csproj
src/BenchmarkDotNet.Disassembler.x86/BenchmarkDotNet.Disassembler.x86.csproj
src/BenchmarkDotNet.Exporters.Plotting/BenchmarkDotNet.Exporters.Plotting.csproj
src/BenchmarkDotNet.TestAdapter/BenchmarkDotNet.TestAdapter.csproj
src/BenchmarkDotNet/BenchmarkDotNet.csproj
tests/BenchmarkDotNet.Exporters.Plotting.Tests/BenchmarkDotNet.Exporters.Plotting.Tests.csproj
tests/BenchmarkDotNet.IntegrationTests.ConfigPerAssembly/BenchmarkDotNet.IntegrationTests.ConfigPerAssembly.csproj
tests/BenchmarkDotNet.IntegrationTests.CustomPaths/BenchmarkDotNet.IntegrationTests.CustomPaths.csproj
tests/BenchmarkDotNet.IntegrationTests.DisabledOptimizations/BenchmarkDotNet.IntegrationTests.DisabledOptimizations.csproj
tests/BenchmarkDotNet.IntegrationTests.EnabledOptimizations/BenchmarkDotNet.IntegrationTests.EnabledOptimizations.csproj
tests/BenchmarkDotNet.IntegrationTests.FSharp/BenchmarkDotNet.IntegrationTests.FSharp.fsproj
tests/BenchmarkDotNet.IntegrationTests.ManualRunning.MultipleFrameworks/BenchmarkDotNet.IntegrationTests.ManualRunning.MultipleFrameworks.csproj
tests/BenchmarkDotNet.IntegrationTests.ManualRunning/BenchmarkDotNet.IntegrationTests.ManualRunning.csproj
tests/BenchmarkDotNet.IntegrationTests.Static/BenchmarkDotNet.IntegrationTests.Static.csproj
tests/BenchmarkDotNet.IntegrationTests/BenchmarkDotNet.IntegrationTests.csproj
tests/BenchmarkDotNet.Tests/Attributes/ParamsAllValuesVerifyTests.cs
tests/BenchmarkDotNet.Tests/BenchmarkDotNet.Tests.csproj
tests/BenchmarkDotNet.Tests/Detectors/Cpu/CpuInfoFormatterTests.cs
tests/BenchmarkDotNet.Tests/Exporters/CommonExporterVerifyTests.cs
tests/BenchmarkDotNet.Tests/Exporters/MarkdownExporterVerifyTests.cs
tests/BenchmarkDotNet.Tests/Perfonar/PerfonarTests.cs

This PR update package dependencies to latest versions.
Run following command.
> dotnet package list --outdated --project BenchmarkDotNet.sln
| Name                                                             | From            | To              | Description |
|------------------------------------------------------------------|-----------------|-----------------|-------------|
|`FSharp.Core`                                                     | `4.6.0`         | `9.0.300`       |             |
|`Iced`                                                            | `1.17.0`        | `1.21.0`        |             |
|`JetBrains.Profiler.SelfApi`                                      | `2.5.11`        | `2.5.13`        |             |
|`Microsoft.CodeAnalysis.CSharp` …

deps: Update package dependencies

---

src/BenchmarkDotNet/Running/WakeLock.PInvoke.cs

Refactor `WakeLock.PInvoke` for compatibility with the ARM CPU #2745
Replaced `SimpleReasonString` field from `REASON_CONTEXT` with a union, `REASON_CONTEXT_UNION`.
The ARM CPU is more strict with unions.
Within unions, strings are not allowed, thus using a pointer to a string, with updated allocation within `PowerCreateRequest`.

Refactor WakeLock.PInvoke for compatibility with the ARM CPU #2745

---

src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliGenerator.cs

This pull request introduces enhancements to the `DotNetCliGenerator` class to improve support for solution file extensions. The changes primarily focus on making the code more extensible and maintainable by centralizing the handling of solution extensions.
Enhancements to solution file handling:
* [`src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliGenerator.cs`](diffhunk://#diff-97c0704ac349c26af0a61aaa9bbea631b13b7bbf0446141c76810cb01c4a9e6cR15-R16): Added a new static array `SolutionExtensions` to define supported solution file extensions (`.sln` and `.slnx`).
* [`src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliGenerator.cs`](diffhunk://#diff-97c0704ac349c26af0a61aaa9bbea631b13b7bbf0446141c76810cb01c4a9e6cL114-R116): Updated the `IsRootSolutionFolder` method to use the new …

Test for both .sln and .slnx when searching for solution file

---

build/sdk/global.json

This PR update .NET SDK 8 dependency to [latest released version](https://dotnet.microsoft.com/en-us/download/dotnet/8.0).

Bump .NET SDK: 8.0.401->8.0.410

---

samples/BenchmarkDotNet.Samples/BenchmarkDotNet.Samples.csproj
samples/BenchmarkDotNet.Samples/IntroNuGet.cs
src/BenchmarkDotNet.TestAdapter/BenchmarkEnumerator.cs
tests/BenchmarkDotNet.IntegrationTests.ManualRunning.MultipleFrameworks/BenchmarkDotNet.IntegrationTests.ManualRunning.MultipleFrameworks.csproj
tests/BenchmarkDotNet.IntegrationTests/BenchmarkDotNet.IntegrationTests.csproj
tests/BenchmarkDotNet.Tests/BenchmarkDotNet.Tests.csproj

This PR intended to fix `BenchmarkDotNet.TestAdapter` related issues.
1. Modify `System.Collections.Immutable` baseline version from `9.0.3` -> `9.0.0` and modify related benchmark.
2. Add `AppDomain.CurrentDomain.AssemblyResolver` for .NET 4.6.2 on TestAdapter project to fix assembly loading issue.
3. Remove explicit PackageReference to `System.Memory`  (Use transitively referenced package version instead)
**Background**
`System.Collections.Immutable` is transitively referenced by other packages.
And it cause version conflicts when using TestAdapter. So it need to adjust minimum version to other packages.
(Normally it's not cause issue Because newer version is loaded first. But when running with TestAdapter. It seems `9.0.0` version is loaded and cause …

chore: Fix benchmark TestAdapter related issues

---

src/BenchmarkDotNet/Engines/Engine.cs
src/BenchmarkDotNet/Engines/GcStats.cs
src/BenchmarkDotNet/Portability/RuntimeInformation.cs
tests/BenchmarkDotNet.IntegrationTests/BenchmarkDotNet.IntegrationTests.csproj
tests/BenchmarkDotNet.IntegrationTests/MemoryDiagnoserTests.cs

<s>This doesn't fix the zero-alloc measurement, but it does fix a bug from the threading diagnoser interfering with the results. The other changes give us the highest confidence that any errant measurements are not our fault. The rest is up to the runtime.</s>
Fixes #1542

Improve memory diagnoser accuracy

---

src/BenchmarkDotNet/Attributes/OrdererAttribute.cs
src/BenchmarkDotNet/Jobs/JobComparer.cs
src/BenchmarkDotNet/Order/DefaultOrderer.cs
src/BenchmarkDotNet/Order/JobOrderPolicy.cs
tests/BenchmarkDotNet.Tests/Order/JobOrderTests.cs

This PR intended to fix issue #2768.
1. Add `JobOrderPolicy` that similar to `SummaryOrderPolicy`/`MethodOrderPolicy`
2. Modify `DefaultOrderer`/`JobComparer`/`OrdererAttribute` to accept `JobOrderPolicy` parameter.
3. Add `NumericStringComparer` nested class to `JobComparer`. this class compare string with [numeric ordering](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-10/libraries#numeric-ordering-for-string-comparison).
4. Add unit tests to `JobOrderTests.cs`
Note: This PR don't change existing behaviors.  `Numeric job ordering` feature is enabled when explicitly enabled.
**List of Job characteristics** 
Job characteristics is compared by following priorities.
https://github.com/dotnet/BenchmarkDotNet/blob/c84de9a0d4af419309743c5f86e765de8 …

feat: Add JobOrderPolicy option to sort jobs by numeric order

---

.github/workflows/run-tests.yaml
build/BenchmarkDotNet.Build/Runners/UnitTestRunner.cs

This PR fix macos runner image issue that unintentionally changed image from x64 to ARM64. (#2738)
`macos15` using ARM64 architecture. It need to use `macos13` image to tests on x64. 
https://github.com/actions/runner-images?tab=readme-ov-file#available-images
1. Modify `test-macos` job to use both ARM64/x64 images with matrix.
2. Modify `BenchmarkDotNet.Build.csproj` to output trx log with unit file name.
~~Note:~~ 
~~Artifact zip archive name is outputted as following.~~
~~(It's because GitHub Action don't have build-in functions for toLowerCase)~~  
~~- `test-macos(ARM64)-trx-15629555566`~~
~~- `test-macos(X64)-trx-15629555566`~~

chore: Modify macos runner image for CI

---

tests/BenchmarkDotNet.IntegrationTests/ArgumentsTests.cs
tests/BenchmarkDotNet.IntegrationTests/DisassemblyDiagnoserTests.cs
tests/BenchmarkDotNet.IntegrationTests/MemoryDiagnoserTests.cs
tests/BenchmarkDotNet.IntegrationTests/ParamSourceTests.cs
tests/BenchmarkDotNet.IntegrationTests/TailCallDiagnoserTests.cs
tests/BenchmarkDotNet.IntegrationTests/ThreadingDiagnoserTests.cs
tests/BenchmarkDotNet.IntegrationTests/ValuesReturnedByBenchmarkTest.cs

This PR intended to fix issue that following xUnit warnings are recorded on test discovery.
> BenchmarkDotNet.IntegrationTests: Non-serializable data ('System.Object[]') found for 'BenchmarkDotNet.IntegrationTests.ValuesReturnedByBenchmarkTest.AnyValueCanBeReturned'; falling back to single test case.
This warning is occurred when Theory data contains non serialize/deserialize data by xunit (`IToolchain`, `Jit`, and `Runtime).
It's not needed to display individual test cases on TestExplorer.
So suppress these warnings by specifing `DisableDiscoveryEnumeration=true` parameter.
**Other changes**
~~Add **condition** to reference TestAdapter project when using `Release` configuration only.~~
~~It's required because it failed to load BenchmarkDotNet assembly when build project with `Debug` …

chore: Suppress xunit non-serializable data warnings

---

src/BenchmarkDotNet/Configs/DefaultConfig.cs
src/BenchmarkDotNet/Validators/RuntimeValidator.cs
tests/BenchmarkDotNet.Tests/Validators/RuntimeValidatorTests.cs

This PR add validator to handle issue that is reported #2609.
1. Add `RuntimeValidator.cs` for benchmarks that have multiple runtimes and contains null.
2. Add RuntimeValidator to DefaultConfig's validator
3. Add unit tests.
**Background**
When benchmark don't contains `Runtime` characteristic. (e.g. When specify `WithToolChain() only`)
[BenchmarkCase::GetRuntime](https://github.com/dotnet/BenchmarkDotNet/blob/c84de9a0d4af419309743c5f86e765de8d490a90/src/BenchmarkDotNet/Running/BenchmarkCase.cs#L31-L33) returns current runtime instead of actual runtime that used by benchmark.
Normally, `Runtime` column is hidden on table because all benchmarks have same runtime value.
So it's not a problem. But when mixed `WithRuntime` settings. it display wrong runtime.
So …

feat: Add validator for benchmarks that contains null runtime

---

tests/BenchmarkDotNet.IntegrationTests/MemoryDiagnoserTests.cs

This PR intended to fix #2779.
Currently `AllocationQuantumIsNotAnIssueForNetCore21Plus` test failed randomly.
And report unexpected memory allocations.
It's expected to be caused by JIT related behaviors.
So I've added warmup 3-times settings for this benchmark.
Currently this PR is draft.
I'll try several runs to see if the problem is resolved by this changes.

chore: Add warmups steps for flaky tests (AllocationQuantumIsNotAnIssueForNetCore21Plus)

---

src/BenchmarkDotNet/Validators/RuntimeValidator.cs

This PR fix review comment (https://github.com/dotnet/BenchmarkDotNet/pull/2771#issuecomment-2973529256)
When using InProcessToolchain `Runtime` shows correct value.
So there is no need to show runtime validation error for InProcessToolchain.

chore: Skip null runtime validation for InProcessToolchain

---

src/BenchmarkDotNet.TestAdapter/BenchmarkExecutor.cs
src/BenchmarkDotNet/Configs/ManualConfig.cs

This PR intended to fix issue that console and VS Output Window logs are outputted twice when running benchmarks with TestAdapter/ `dotnet test` command.
**What's Tested**
1. When running benchmark from Visual Studio TestExplorer.  
No duplicated logs outputted on Output Window's `Tests` pane. 
3. When running following command.   
No duplicated logs outputted. 
> dotnet test BenchmarkDotNet.sln -c Release --filter Category=Fast -tl:off --framework net8.0 --logger:"console;verbosity=normal"

fix: Console logs are outputted twice when using TestAdapter

---

.github/workflows/run-tests-selected.yaml

This PR add workflow file (`run-tests-selected.yaml`) that run selected tests on specific project/OS/framework.
**Expected workflow usage**
1. Run only selected tests on specific OS/framework (to reduce CI test workaround time)
2. Run flaky tests that need multiple iterations to reproduce problems.
3. Run `BenchmarkDotNet.IntegrationTests.ManualRunning` tests on CI (#2751)
4. To collect custom tests artifacts (e.g. `dotnet-gcdume` results)
**How to run this workflow**
1. Run workflow from GitHub Action's Web UI
2. Run workflow with `gh` command
```
gh workflow run run-tests-selected.yaml --repo dotnet/BenchmarkDotNet --ref master -f runs_on=windows-latest -f project=tests/BenchmarkDotNet.IntegrationTests -f filter=CanDisassembleAllMethodCalls -f framework=net462
```
> [!NOTE]
> To invoke …

chore: Add GitHub Actions workflow that run selected tests

---

src/BenchmarkDotNet/Environments/Runtimes/CoreRuntime.cs
src/BenchmarkDotNet/Portability/RuntimeInformation.cs

Fixes https://github.com/dotnet/BenchmarkDotNet/issues/2383#issuecomment-2904791572

Fix `IsNetCore` and `IsNativeAOT` for single-file apps without AOT

---

src/BenchmarkDotNet.TestAdapter/build/BenchmarkDotNet.TestAdapter.props

GenerateProgramFile is used by VSTest, not MSTest.

Fix comment in package props about GenerateProgramFile

---

samples/BenchmarkDotNet.Samples.FSharp/BenchmarkDotNet.Samples.FSharp.fsproj
samples/BenchmarkDotNet.Samples/BenchmarkDotNet.Samples.csproj
src/BenchmarkDotNet.TestAdapter/Utility/LoggerHelper.cs
src/BenchmarkDotNet.TestAdapter/Utility/TestCaseFilter.cs
src/BenchmarkDotNet.TestAdapter/VSTestAdapter.cs
src/BenchmarkDotNet.TestAdapter/build/BenchmarkDotNet.TestAdapter.props

This PR add `--filter` parameter support for `dotnet test`.
It intended to resolve #2767 issue (and some part of issue #2662)
**1. Add benchmark filter logics**
Add following files to support benchmark filtering. 
- `TestCaseFilter.cs`
- `LoggerHelper.cs`
Note: These files are based on [xUnit v2 TestAdapter Code](https://github.com/xunit/visualstudio.xunit/blob/main/src/xunit.runner.visualstudio/Utility/TestCaseFilter.cs) (License: Apache 2.0)
**2. Modify `VSTestAdapter.cs`**
Add benchmark filter logics to `DiscoverTests` and `RunTests`
~~**3. BenchmarkEnumerator.cs**~~
~~Remove code for `Debug` configuration.~~
~~(By #2774 changes. It can load DLLs that are build with `Debug` configurations)~~
**4. Disable `TestTfmsInParallel` MSBuild property**
It's enabled by default on .NET 9 or …

feat: Add filter support for TestAdapter

---

tests/BenchmarkDotNet.IntegrationTests/MemoryDiagnoserTests.cs

This PR intended to fix flaky test issue (#2779) that happens when running AllocationQuantumIsNotAnIssueForNetCore21Plus` on macos.
On previous PR (#2782)
I've setting `warmupCount: 2` and it reduced failed CI.
But it seems error still continues with low frequency.
So I've changed workupCount setting from `2` to `5`.
And this issue is not confirmed on OS other than macos (x64/arm64).
So I've revert setting to use `warmupcount:0` on other OS.

chore: Fix flaky AllocationQuantumIsNotAnIssueForNetCore21Plus tests on macos

---

src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommand.cs

Use `--nodeReuse:false`

---

src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs
tests/BenchmarkDotNet.IntegrationTests/EventProcessorTests.cs

This PR modify `EventProcessor::OnEndValidationStage` invoke timing to ensure `OnEndValidationStage` is called when validation failed.
**Background**
I want to handle validation errors on `EventProcessor::OnEndValidationStage` event to grouping errors per `BenchmarkCase`.
But on current implementation.
`EventProcessor::OnEndValidationStage` is not called when ValidationErrors contains **critical** error.

chore: Ensure `EventProcessor::OnEndValidationStage` is called when critical validation error contained

---

src/BenchmarkDotNet.TestAdapter/build/BenchmarkDotNet.TestAdapter.props

Condition needs double equals to be a comparison. As it is, it won't load in Visual Studio right now.

Fix condition for TestTfmsInParallel property

---

src/BenchmarkDotNet/Running/BenchmarkConverter.cs
tests/BenchmarkDotNet.IntegrationTests/ParamSourceTests.cs

Currently, when specifying abstract properties or methods with ParamsSource, an exception occurs with SingleOrDefault:
`System.InvalidOperationException: Sequence contains more than one matching element`
```csharp
BenchmarkRunner.Run<Bench>();
public abstract class BenchBase
{
public abstract int[] Levels { get; }
[ParamsSource(nameof(Levels))]
public int Level { get; set; }
[Benchmark]
public void Foo()
{
}
}
public class Bench : BenchBase
{
public override int[] Levels => [1, 2, 3];
[Benchmark]
public void Bar()
{
}
}
```
This is because `sourceType.GetAllMethods()` and `sourceType.GetAllProperties()` traverse up the parent class hierarchy, enumerating both the overridden property and abstract property with the same name.
And since `GetValidValuesForParamsSource` processes with …

Allow override method/property for ParamsSource

---

src/BenchmarkDotNet/BenchmarkDotNet.csproj
src/BenchmarkDotNet/BenchmarkDotNet.targets

This PR intended to resolve https://github.com/dotnet/BenchmarkDotNet/issues/2736
**1. Add custom MSBuild targets file to nupkg.**
This custom target is packed as `buildTransitive/BenchmarkDotNet.targets` file.
And it'sused by .NET SDK-Style projects. (It's ignored when referenced from .NET Framework non-SDK style project)
**2. Details of custom MSBuild target process.**
It try to set `BenchmarkDotNetTargetPlatform` property.
If target `runtime` is explicitly specified (e.g. `--runtime`) just use specified runtime.
Otherwise. try to use  **current build environment** platform.
Then `FilterBenchmarkDotNetPackageAssets` custom target try to remove following files.
1. `runtime/*` files that are copied from `Gee.External.Capstone` package
2. Satellite assemblies that are copied from …

feat: Add custom MsBuild targets to remove unnecessary files from bin directory
