BenchmarkDotNet/Tasks/TaskAttribute.cs, README.md
Just a minor fix: message for Obsolete warning which tells what to use now + updated README (I was confused after update so fixed this)
PS. This tool is just awesome!!
=> message for Obsolete warning + updated README

BenchmarkDotNet.Samples/BenchmarkDotNet.Samples.csproj, BenchmarkDotNet.Samples/Other/Array_AccessNormalRefUnsafe.cs
=> Add benchmarks to tests different ways of accessing arrays.

BenchmarkDotNet/BenchmarkDotNet.csproj, BenchmarkDotNet/Configs/DefaultConfig.cs, BenchmarkDotNet/Exporters/HtmlExporter.cs, BenchmarkDotNet/Exporters/MarkdownExporter.cs, BenchmarkDotNet/Reports/SummaryTableExtensions.cs, README.md
=> HtmlReporter

BenchmarkDotNet.Samples.FSharp/Program.fs
removed the reflection call to setup the switch
=> use benchmarkSwitcher and 0.9.0 api features

.gitignore, appveyor.yml, build/version.ps1
PR against develop branch as requested (see #199)
=> Added appveyor ci build fix #77

appveyor.yml, build/uploadtests.ps1
Appveyor build improvements:
- added nuget packages folder to cache to speedup build
- all unit tests are now showing up in the tests tab
=> Appveyor build improvements

src/BenchmarkDotNet.Core/Characteristics/CharacteristicPresenter.cs, src/BenchmarkDotNet.Core/Helpers/SourceCodeHelper.cs
Current presenter implementations do not pass culture to the formattable values. fixed :)
=> Presenters: IFormattable support

src/BenchmarkDotNet.Core/Characteristics/Characteristic.cs, src/BenchmarkDotNet.Core/Characteristics/CharacteristicHelper.cs, src/BenchmarkDotNet.Core/Characteristics/CharacteristicObject.cs, src/BenchmarkDotNet.Core/Characteristics/CharacteristicObject`1.cs, src/BenchmarkDotNet.Core/Characteristics/CharacteristicPresenter.cs, src/BenchmarkDotNet.Core/Characteristics/CharacteristicSet.cs, src/BenchmarkDotNet.Core/Characteristics/CharacteristicSetPresenter.cs, src/BenchmarkDotNet.Core/Characteristics/Characteristic`1.cs, src/BenchmarkDotNet.Core/Characteristics/CompositeResolver.cs, src/BenchmarkDotNet.Core/Characteristics/IResolver.cs, src/BenchmarkDotNet.Core/Characteristics/Resolver.cs, src/BenchmarkDotNet.Core/Columns/DefaultColumnProvider.cs, src/BenchmarkDotNet.Core/Columns/JobCharacteristicColumn.cs, src/BenchmarkDotNet.Core/Jobs/Job.cs, src/BenchmarkDotNet.Core/Jobs/JobMode`1.cs, tests/BenchmarkDotNet.IntegrationTests/JobTests.cs
As in #340. What's changed:
* JobMode renamed to CharacteristicObject
* CharacteristicColumn renamed to JobCharacteristicColumn
* New base type added, CharacteristicObject<T>
* CharacteristicHelper made public
As usual, tests [are green](https://ci.appveyor.com/project/ig-sinicyn/benchmarkdotnet), suggestions are welcome:)
=> Base types for characteristic objects:

src/BenchmarkDotNet.Core/Extensions/StatisticsExtensions.cs
=> Used ToStr to make statistics builder culture invariant (fixed #307)

src/BenchmarkDotNet/Running/BenchmarkSwitcher.cs, tests/BenchmarkDotNet.IntegrationTests/BenchmarkSwitcherTest.cs
=> Add an optional config to BenchmarkSwitcher.

src/BenchmarkDotNet.Core/Exporters/AsciiDocExporter.cs, src/BenchmarkDotNet.Core/Exporters/CompositeExporter.cs, src/BenchmarkDotNet.Core/Exporters/Csv/CsvExporter.cs, src/BenchmarkDotNet.Core/Exporters/Csv/CsvMeasurementsExporter.cs, src/BenchmarkDotNet.Core/Exporters/ExporterBase.cs, src/BenchmarkDotNet.Core/Exporters/HtmlExporter.cs, src/BenchmarkDotNet.Core/Exporters/IExporter.cs, src/BenchmarkDotNet.Core/Exporters/MarkdownExporter.cs, src/BenchmarkDotNet.Core/Exporters/RPlotExporter.cs, tests/BenchmarkDotNet.Tests/ExporterDependencyTests.cs
Coming back to approval tests and reporters refactoring. Started it a long long time ago, so my brаnch is very old. Decided to combine small refactoring in a new pull request just to be sure that it won't be lost again.
=> Small fixes before approval tests

src/BenchmarkDotNet.Core/Exporters/Csv/CsvExporter.cs, src/BenchmarkDotNet.Core/Exporters/Csv/CsvHelper.cs, src/BenchmarkDotNet.Core/Exporters/Csv/CsvMeasurementsExporter.cs, tests/BenchmarkDotNet.Tests/CsvHelperTests.cs
=>  CSVHelper.Escape() method should check for actual separator value

src/BenchmarkDotNet.Core/Portability/RuntimeInformation.cs
Mono returns PlatformID.Unix on Linux and macOS. It's not enough for detect OS version. I use native call uname from libc for fix it.
=> Fix unix OS detection.

src/BenchmarkDotNet.Uap/Templates/UapBenchmarkProject.notcsproj, src/BenchmarkDotNet.Uap/Toolchains/Uap/UapGenerator.cs, tests/runUapTests.cmd
This PR fixes integration building and running.
=> Fix build to align with refactoring

docs/guide/Configs/Filters.md
I was reading through the docs and noticed this small error.
=> Small correction in Filters.md

docs/guide/FAQ.md
Proposing some improvements to the FAQ.md documentation file.
=> Small improvements to FAQ.md

docs/guide/Configs/Filters.md, samples/BenchmarkDotNet.Samples/Intro/IntroFilters.cs
=> Corrected typos in Filters.md and IntroFilters.cs

docs/guide/Configs/Exporters.md
This PR provides docs for the feature #396
=> Adds ISummaryStyle information to the Exporters guide

docs/guide/Configs/Jobs.md
Fixed a type name and changed some wording on the Jobs doc page.
=> Update jobs docs

appveyor.yml
Temporary solution to address [connectivity issues to nuget.org](https://appveyor.statuspage.io/incidents/m2vdvw39kdk8 )
=> Add temporary solution to address connectivity issues to nuget.org

appveyor.yml
Removes a temporary solution related to connectivity issues to nuget.org https://appveyor.statuspage.io/incidents/m2vdvw39kdk8
=> Removes a temporary solution related to connectivity issues to nuget

docs/guide/Advanced/Baseline.md, docs/guide/Advanced/Percentiles.md, docs/guide/Configs/Analyzers.md, docs/guide/Configs/Columns.md, docs/guide/Configs/Diagnosers.md, docs/guide/Configs/Exporters.md, docs/guide/Configs/Jobs.md
I'm not native english speaker, so please shout if you have any doubts :)
=> Fixed some typos and grammar

src/BenchmarkDotNet.Core/Toolchains/InProcess/InProcessRunner.cs
=> Fix #513 - IterationSetup not run in Job.InProcess

src/BenchmarkDotNet.Core/Toolchains/DotNetCli/NetCoreAppSettings.cs
Fix #587 
@adamsitnik @AndreyAkinshin
=> Add support for netcoreapp2.1

build.cake, build.ps1, build.sh
Upgrade version to 2.0.3 and explicitly specify fx version to run tests against .netcoreapp2.0. Closes #588
=> Fix CI build 

tests/BenchmarkDotNet.Tests/Loggers/OutputLogger.cs
I removed a xunit workaround. An issue has been fixed already.
https://github.com/xunit/xunit/issues/876 and https://github.com/xunit/xunit/pull/1007
=> Removed a xunit workaround because an issue has been fixed

src/BenchmarkDotNet.Core/Exporters/HtmlExporter.cs, src/BenchmarkDotNet.Core/Extensions/StringAndTextExtensions.cs, tests/BenchmarkDotNet.Tests/StringExtensionsTests.cs
Fixes Issue #599 
Let me know of any changes.  Thanks.
=> Fix HTML Encoding for Html Exporter

src/BenchmarkDotNet.Core/Configs/ConfigParser.cs, src/BenchmarkDotNet.Core/Running/TypeParser.cs
=> Fixing --help display for options

docs/guide/FAQ.md
This way, the FAQ is properly rendered as a single `<ul>`, with consistent indentation.
=> List formatting for FAQ

docs/guide/Configs/Diagnosers.md
=> Fix typo (Perdictor -> Predictor)

docs/guide/Contributing/Building.md
In order to solve https://github.com/dotnet/BenchmarkDotNet/issues/726 .
=> Building guideline improvement 

src/BenchmarkDotNet/Exporters/BenchmarkReportExporter.cs, src/BenchmarkDotNet/Running/BenchmarkRunner.cs
I found the TODO in BenchmarkRunner.
`` // TODO: make exporter``
So I created new Exporter and moved logic into it.
Does it make sense?
=> BenchmarkReport Exporter

src/BenchmarkDotNet.Diagnostics.Windows/EtwDiagnoser.cs, src/BenchmarkDotNet.Diagnostics.Windows/NativeWindowsConsoleHelper.cs, src/BenchmarkDotNet/Loggers/ConsoleLogger.cs, src/BenchmarkDotNet/Running/TypeParser.cs, src/BenchmarkDotNet/Toolchains/ConsoleHandler.cs
/cc @jorive
PS. Testing this is a PITA
=> stop the ETW session on Ctrl+C + restore console colors ;), fixes #729

docs/_changelog/header/v0.11.0.md
=> Small Typo in changelog

src/BenchmarkDotNet/Order/DefaultOrderer.cs, src/BenchmarkDotNet/Parameters/ParameterInstances.cs, tests/BenchmarkDotNet.IntegrationTests/BaselineScaledColumnTest.cs
For issue https://github.com/dotnet/BenchmarkDotNet/issues/865
=> Fix behavior of Baseline property of Benchmark attribute in integration with Params Attribute

src/BenchmarkDotNet/Portability/Cpu/MosCpuInfoProvider.cs, src/BenchmarkDotNet/Portability/Cpu/WmicCpuInfoKeyNames.cs, src/BenchmarkDotNet/Portability/Cpu/WmicCpuInfoParser.cs, src/BenchmarkDotNet/Portability/Cpu/WmicCpuInfoProvider.cs, tests/BenchmarkDotNet.Tests/Portability/Cpu/WmicCpuInfoParserTests.cs
For https://github.com/dotnet/BenchmarkDotNet/issues/859
=> Fix strange CPU Frequency values

docs/articles/guides/console-args.md
Add information about `--list` option in console-args.md file.
I forgot about it ;)
=> Update console-args.md - add information about `--list` option

src/BenchmarkDotNet/Templates/BenchmarkType.txt
While working on another PR I noticed that this file could use some whitespace cleanup.
=> OCD Whitespace and tabs cleanup

src/BenchmarkDotNet/Code/DeclarationsProvider.cs, tests/BenchmarkDotNet.IntegrationTests/AllSetupAndCleanupTest.cs
This PR adds support for async GlobalCleanup to the `DeclarationsProvider` and that is the last step that needs to be done to complete #521.
=> Added support for async GlobalCleanup.

samples/BenchmarkDotNet.Samples/IntroDeferredExecution.cs, src/BenchmarkDotNet.Disassembler.x64/Program.cs, src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs, src/BenchmarkDotNet/Diagnosers/PreciseMachineCounter.cs, src/BenchmarkDotNet/Exporters/Json/SimpleJson.cs, src/BenchmarkDotNet/Toolchains/CoreRun/CoreRunPublisher.cs, src/BenchmarkDotNet/Toolchains/CoreRun/CoreRunToolchain.cs, src/BenchmarkDotNet/Toolchains/CustomCoreClr/CustomCoreClrToolchainBuilder.cs, src/BenchmarkDotNet/Toolchains/GeneratorBase.cs, src/BenchmarkDotNet/Toolchains/Roslyn/Builder.cs, tests/BenchmarkDotNet.IntegrationTests/BenchmarkSwitcherTest.cs, tests/BenchmarkDotNet.IntegrationTests/MemoryDiagnoserTests.cs, tests/BenchmarkDotNet.IntegrationTests/ParamsAttributeStaticTest.cs, tests/BenchmarkDotNet.IntegrationTests/PerformanceUnitTest.cs, tests/BenchmarkDotNet.Tests/ConfigParserTests.cs, tests/BenchmarkDotNet.Tests/GlobFilterTests.cs, tests/BenchmarkDotNet.Tests/JobTests.cs
Hello! I made small changes, related to typos or spelling issues. I hope it can be useful for the project.
=> Fix minor spelling issues and typos

.travis.yml
please ignore this PR for now, I am just trying my luck
=> update Travis Ubuntu image from 14.04 to 16.04

docs/articles/guides/console-args.md, src/BenchmarkDotNet/Configs/ConfigExtensions.cs, src/BenchmarkDotNet/Configs/ConfigOptions.cs, src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs, src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs, src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs, tests/BenchmarkDotNet.IntegrationTests/SetupAndCleanupTests.cs
Fixes #1074
@AndreyAkinshin PTAL, I added it as an optional setting and kept the default behavior
=> make it possible to Don't Overwrite Results, fixes #1074

src/BenchmarkDotNet.Diagnostics.Windows/ConcurrencyVisualizerProfiler.cs, src/BenchmarkDotNet.Diagnostics.Windows/EtwProfilerConfig.cs, src/BenchmarkDotNet/Exporters/Json/JsonExporterBase.cs, src/BenchmarkDotNet/Exporters/MarkdownExporter.cs, src/BenchmarkDotNet/Reports/SummaryTableExtensions.cs, tests/BenchmarkDotNet.IntegrationTests/ImmutableConfigTests.cs, tests/BenchmarkDotNet.Tests/ConfigParserTests.cs
=> Just spell check

src/BenchmarkDotNet.Diagnostics.Windows/EtwDiagnoser.cs
=> Fixed event wire-up before Session acquisition

src/BenchmarkDotNet/Attributes/ArtifactsPathAttribute.cs, src/BenchmarkDotNet/Attributes/DisassemblyDiagnoserAttribute.cs, src/BenchmarkDotNet/Attributes/GroupBenchmarksByAttribute.cs, src/BenchmarkDotNet/Attributes/KeepBenchmarkFilesAttribute.cs, src/BenchmarkDotNet/Attributes/MemoryDiagnoserAttribute.cs, src/BenchmarkDotNet/Attributes/StopOnFirstErrorAttribute.cs
For https://github.com/dotnet/BenchmarkDotNet/issues/1119
=> Restrict MemoryDiagnoserAttribute usage to class

docs/articles/contributing/running-tests.md
Instead of "@alert..." (which seems not to work as expected) use the DocFx flavor.
(Not sure what the actual change is in the last line - I just used the GitHub UI)
=> Styling in docfx fashion

src/BenchmarkDotNet/Helpers/SectionsHelper.cs, tests/BenchmarkDotNet.Tests/Portability/Cpu/WmicCpuInfoParserTests.cs
=> Added workaround to fix incorrect CPU info when using wmic

docs/docfx.json, docs/template/partials/head.tmpl.partial, docs/template/partials/navbar.tmpl.partial, docs/template/partials/scripts.tmpl.partial, docs/template/styles/search.css
Resolves and follow up from dotnet/BenchmarkDotNet#1137
cc @AndreyAkinshin 🚀
=> Improve search experience in the documentation

README.md
Hi team 👋 ,
I have just found a broken link in the `readme` and fixed it.
Hope this helps.
=> Fix: broken link in readme.md

src/BenchmarkDotNet.Annotations/Attributes/IterationCleanupAttribute.cs, src/BenchmarkDotNet.Annotations/Attributes/IterationSetupAttribute.cs
Try to make it a bit more explicit that the meaning of the attributes changed. It is often tripped on.
=> Update docstring for IterationSetup/IterationCleanup

.travis.yml
More information: 
https://docs.travis-ci.com/user/reference/osx/
=> Update Mac Os for Travis CI

docs/articles/samples/toc.yml
I this PR I sorted examples list and I added missing examples pages:
IntroEncoding
IntroGcMode
IntroInliningDiagnoser
IntroPowerPlan
=> Sorting examples list and adding missing pages

docs/articles/configs/diagnosers.md, docs/articles/samples/IntroNativeMemory.md, docs/articles/samples/toc.yml
In this PR I added documentation for `NativeMemoryDiagnoser`.
=> Add documentation to NativeMemoryDiagnoser

src/BenchmarkDotNet/Templates/BuildPlots.R
https://github.com/dotnet/BenchmarkDotNet/issues/1183
=> Plots with a double dash (--) in the names (#1183)

src/BenchmarkDotNet.Diagnostics.Windows/Tracing/NativeMemoryLogParser.cs
I am sorry that this is another PR is the same functionality. But I think it should have been done from the first one.
=> NativeMemoryProfiler -add count of allocated object

src/BenchmarkDotNet/Environments/BenchmarkEnvironmentInfo.cs, src/BenchmarkDotNet/Environments/Runtimes/CoreRuntime.cs, src/BenchmarkDotNet/Portability/RuntimeInformation.cs, tests/BenchmarkDotNet.Tests/RuntimeVersionDetectionTests.cs
=> try to read .NET Core version from all available information

src/BenchmarkDotNet/Exporters/RPlotExporter.cs, src/BenchmarkDotNet/Extensions/StringAndTextExtensions.cs, src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs
https://github.com/dotnet/BenchmarkDotNet/issues/1181
=> Log shows a wrong name for plot images #1181

src/BenchmarkDotNet/Exporters/ExporterBase.cs, src/BenchmarkDotNet/Exporters/InstructionPointerExporter.cs, src/BenchmarkDotNet/Exporters/PrettyGithubMarkdownDiffDisassemblyExporter.cs, src/BenchmarkDotNet/Helpers/FrameworkVersionHelper.cs, src/BenchmarkDotNet/Portability/Cpu/MosCpuInfoProvider.cs, src/BenchmarkDotNet/Portability/RuntimeInformation.cs, src/BenchmarkDotNet/Running/ClassicBenchmarkConverter.cs, src/BenchmarkDotNet/Toolchains/AppConfigGenerator.cs
In this PR I fix CA2000 - Dispose objects before losing scope.
https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2000-dispose-objects-before-losing-scope?view=vs-2019
PR for Hacktoberfest 😄
=> Fix CA2000 - Add missing using

src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs, src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs, tests/BenchmarkDotNet.Tests/ConfigParserTests.cs
Fixes #1312
/cc @egorbo @filipnavara
=> add possibility to specify env vars via console line arguments

build/common.props, samples/BenchmarkDotNet.Samples.FSharp/BenchmarkDotNet.Samples.FSharp.fsproj, src/BenchmarkDotNet.Disassembler.x64/BenchmarkDotNet.Disassembler.x64.csproj, src/BenchmarkDotNet.Disassembler.x86/BenchmarkDotNet.Disassembler.x86.csproj
=> Add package-refs to reference assemblies for linux build

src/BenchmarkDotNet/Running/BenchmarkSwitcher.cs
Resolves #1350 
Not sure if i should write tests for it, because I'll need something like IEnvironmentHelper to mock Environment.GetCommandLineArgs so it seems to much code for such small feature
=> Warn if command line arguments were not passed to the BenchmarkSwitcher

src/BenchmarkDotNet/Attributes/Jobs/SimpleJobAttribute.cs
=> add missing SimpleJobAttribute ctor

docs/articles/overview.md
This PR is fixing one small grammar mistake in the overview document.
=> Updating Document - Fixing a small grammar mistake

src/BenchmarkDotNet/Analysers/MinIterationTimeAnalyser.cs, src/BenchmarkDotNet/Analysers/MultimodalDistributionAnalyzer.cs
=> Improve warnings for small operations number

src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs
The old description is outdated.
=> Fix --profiler option description.

docs/articles/features/event-pipe-profiler.md, docs/articles/samples/IntroEventPipeProfilerAdvanced.md
=> Small fix in EventPipeProfiler documentation

src/BenchmarkDotNet/Analysers/MultimodalDistributionAnalyzer.cs, src/BenchmarkDotNet/Columns/BaselineScaledColumn.cs
=> Safe access to CultureInfo

src/BenchmarkDotNet.Disassembler.x64/BenchmarkDotNet.Disassembler.x64.csproj, src/BenchmarkDotNet.Disassembler.x86/BenchmarkDotNet.Disassembler.x86.csproj
=> Update to latest Iced 1.7.0

BenchmarkDotNet.sln.DotSettings, NuGet.Config, README.md, docs/articles/configs/toolchains.md, docs/articles/samples/IntroWasm.md, docs/articles/samples/toc.yml, samples/BenchmarkDotNet.Samples/IntroWasm.cs, src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs, src/BenchmarkDotNet/Environments/Runtimes/WasmRuntime.cs, src/BenchmarkDotNet/Portability/RuntimeInformation.cs, src/BenchmarkDotNet/Toolchains/Executor.cs
@AndreyAkinshin it turns out that I've introduced a bug in my #1498 refactor (I forgot to set WokringDirectory)
Could you please take a look at this PR?
BTW this time I've tested it properly and it works as expected
=> Wasm: samples, docs and a bug fix

src/BenchmarkDotNet.Diagnostics.Windows/EtwProfiler.cs, src/BenchmarkDotNet.Diagnostics.Windows/Tracing/TraceLogParser.cs, src/BenchmarkDotNet/Exporters/InstructionPointerExporter.cs
=> Bring instruction pointer exporter back to live

src/BenchmarkDotNet/Templates/CsProj.txt
=> ensure that the auto-generated project alwas has tfm in the output path

docs/articles/guides/console-args.md
It is my first contribution to an open-source project. I want to thanks @adamsitnik for his public speaking in which he presented the open-source world subtly and encouraged me to be a part of the community. Several years down the road, I will come back here to watch this moment.
=> Update Console Args doc #1559

src/BenchmarkDotNet/Jobs/JobExtensions.cs, src/BenchmarkDotNet/Jobs/NugetReference.cs, src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommand.cs
Added source and prerelease optional parameters at WithNuGet extension method
=> feat: Allowed to indicate the source of nuget package and whether it is a pre-release version.

src/BenchmarkDotNet.Disassembler.x64/SourceCodeProvider.cs
=> Fixed smart pointer for multiline source code

src/BenchmarkDotNet/Running/BuildPartition.cs, src/BenchmarkDotNet/Toolchains/CsProj/CsProjGenerator.cs
=> Resolve assembly location for SingleFile

docs/_changelog/header/v0.13.0.md
@AndreyAkinshin I've finally found some free time (long weekend). I am going to finish it tomorrow
=> 0.13.0 release notes

docs/articles/guides/getting-started.md
Update "View results" from "Getting started"
The current output is misleading. Copy/Past from https://github.com/dotnet/BenchmarkDotNet/blob/63e28c100a42a6492d09a0b93a8a4c141061bb0d/docs/articles/overview.md
=> Update "View results" from "Getting started"

src/BenchmarkDotNet/Environments/Platform.cs, src/BenchmarkDotNet/Extensions/ConfigurationExtensions.cs, src/BenchmarkDotNet/Portability/RuntimeInformation.cs
=> add S390x architecture support

build.ps1, build.sh, src/BenchmarkDotNet/Toolchains/CoreRt/Generator.cs
This is required to make CoreRT work on 5.0.3XX SDK
=> Add ValidateExecutableReferencesMatchSelfContained

src/BenchmarkDotNet/Toolchains/CsProj/CsProjGenerator.cs
Simple change to allow testing preview features in .NET 6+. Not sure if test should be added for it. Tested locally.
=> Preserve EnablePreviewFeatures csproj setting

docs/articles/configs/exporters.md
Added explanation on how to change the default output of the exporters in exporters.md
=> Added exporter custom path to docs #1819

src/BenchmarkDotNet/Jobs/EnvironmentMode.cs, src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs, src/BenchmarkDotNet/Running/PowerManagementApplier.cs, tests/BenchmarkDotNet.IntegrationTests/PowerManagementApplierTests.cs
Fixes #1506.
[Rewritten]
The commits are self-explanatory.
=> Comeback of power management

src/BenchmarkDotNet/Extensions/ProcessExtensions.cs, tests/BenchmarkDotNet.IntegrationTests/EnvironmentVariablesTests.cs
=> disable ReSharper's Dynamic Program Analysis by default

src/BenchmarkDotNet/Attributes/Filters/OperatingSystemsArchitectureFilterAttribute.cs, src/BenchmarkDotNet/Attributes/Filters/OperatingSystemsFilterAttribute.cs, src/BenchmarkDotNet/Environments/OsBrandStringHelper.cs, src/BenchmarkDotNet/Environments/Runtimes/WasmRuntime.cs, src/BenchmarkDotNet/Order/CategoryComparer.cs, src/BenchmarkDotNet/Running/BenchmarkRunnerDirty.cs, src/BenchmarkDotNet/Toolchains/CoreRt/CoreRtToolchain.cs, tests/BenchmarkDotNet.Tests/Order/DefaultOrdererTests.cs, tests/BenchmarkDotNet.Tests/ParamsSourceTests.cs
=> Fix warnings

tests/BenchmarkDotNet.IntegrationTests/MemoryDiagnoserTests.cs
=> disable AwaitingTasksShouldNotInterfereAllocationResults test

src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs, src/BenchmarkDotNet/Environments/Runtimes/MonoAotLLVMRuntime.cs, src/BenchmarkDotNet/Extensions/ProcessExtensions.cs, src/BenchmarkDotNet/Templates/MonoAOTLLVMCsProj.txt
Changes so that the AOT mode will correctly AOT. Also use full-aot mode to prevent any fall back to JIT.
=> Actually AOT things in AOT mode; prevent JIT fall back

src/BenchmarkDotNet/Helpers/ArtifactFileNameHelper.cs
Update error message to reflect the change introduced by https://github.com/dotnet/BenchmarkDotNet/pull/1545
=> Update ArtifactFileNameHelper error message

src/BenchmarkDotNet/Configs/ConfigOptions.cs, src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs, src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs, src/BenchmarkDotNet/Running/BuildPartition.cs, src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommand.cs, tests/BenchmarkDotNet.Tests/ConfigParserTests.cs
.. differentiated, like `{ProjectName}-restore.binlog`,
and `{ProjectName}-build.binlog`.
=> Add new `--generateBinLog` to generate msbuild binlogs, with names

build/Program.cs, tests/BenchmarkDotNet.IntegrationTests.ManualRunning/BenchmarkDotNet.IntegrationTests.ManualRunning.csproj, tests/BenchmarkDotNet.IntegrationTests/BenchmarkDotNet.IntegrationTests.csproj, tests/BenchmarkDotNet.IntegrationTests/MemoryDiagnoserTests.cs, tests/BenchmarkDotNet.IntegrationTests/ProcessPropertiesTests.cs, tests/BenchmarkDotNet.Tests/BenchmarkDotNet.Tests.csproj
fixing a bug that was introduced in #1978
=> the CI must run net6.0, not net5.0 tests

tests/BenchmarkDotNet.IntegrationTests/MemoryDiagnoserTests.cs
one of them takes 3 minutes and we hit the 1h limit
=> don't run NativeAOT tests on AppVeyor Windows

src/BenchmarkDotNet/Portability/Cpu/WmicCpuInfoProvider.cs
Fix documentation for wmic command used by WmicCpuInfoProvider
=> Fix WmicCpuInfoProvider documentation

src/BenchmarkDotNet/Toolchains/NativeAot/Generator.cs
https://github.com/dotnet/runtime/pull/72325
=> adopt to recent NativeAOT changes

src/BenchmarkDotNet/BenchmarkDotNet.csproj, src/BenchmarkDotNet/Portability/Cpu/HardwareIntrinsics.cs, src/BenchmarkDotNet/Toolchains/NativeAot/Generator.cs
=> Address code review feedback

src/BenchmarkDotNet/Templates/CsProj.txt, src/BenchmarkDotNet/Toolchains/CsProj/CsProjGenerator.cs, tests/BenchmarkDotNet.Tests/CsProjGeneratorTests.cs
=> Bugfix copied project settings

src/BenchmarkDotNet/Helpers/FrameworkVersionHelper.cs, tests/BenchmarkDotNet.Tests/FrameworkVersionHelperTests.cs
=> fix .NET 4.8.1 detection

src/BenchmarkDotNet/Disassemblers/DisassemblyDiagnoser.cs, src/BenchmarkDotNet/Jobs/EnvironmentMode.cs, src/BenchmarkDotNet/Jobs/JobExtensions.cs, src/BenchmarkDotNet/Running/BuildPartition.cs
=> print error when users try DisassemblyDiagnoser with NativeAOT

src/BenchmarkDotNet/Toolchains/CoreRun/CoreRunToolchain.cs
@kunalspathak has tried to run BDN benchmarks with a config where CoreRun is stored in a readonly folder (by the Helix, a system used by the .NET Team to run tests on multiple machines. That has failed with an exception.
As solution we can do the following:
- when creating the destination folder fails, try to store it in TEMP
- when storing in TEMP fails as well, don't perform the copy at all
This should be quite bulletproof.
=> add two fallbacks to CoreRun copying

docs/_changelog/header/v0.13.2.md
It took me a while to write it but having sooo many contributions made it time consuming ;)
=> Release notes for 0.13.2

azure-pipelines.macOS.yml
Details: https://github.com/actions/runner-images/issues/5583
=> Use latest AzDO macOS pool

src/BenchmarkDotNet/Loggers/AsyncProcessOutputReader.cs, src/BenchmarkDotNet/Loggers/CompositeLogger.cs
=> ensure CompositeLogger is synchronized

docs/articles/configs/diagnosers.md, docs/articles/samples/IntroExceptionDiagnoser.md, samples/BenchmarkDotNet.Samples/IntroExceptionDiagnoser.cs, src/BenchmarkDotNet/Attributes/ExceptionDiagnoserAttribute.cs, src/BenchmarkDotNet/Columns/Column.cs, src/BenchmarkDotNet/Configs/ImmutableConfig.cs, src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs, src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs, src/BenchmarkDotNet/Diagnosers/DiagnoserResults.cs, src/BenchmarkDotNet/Diagnosers/ExceptionDiagnoser.cs, src/BenchmarkDotNet/Engines/Engine.cs, src/BenchmarkDotNet/Engines/ExceptionsFrequencyStats.cs, src/BenchmarkDotNet/Engines/ExceptionsStats.cs, src/BenchmarkDotNet/Engines/RunResults.cs, src/BenchmarkDotNet/Toolchains/Results/ExecuteResult.cs, tests/BenchmarkDotNet.IntegrationTests/CustomEngineTests.cs, tests/BenchmarkDotNet.IntegrationTests/ExceptionDiagnoserTests.cs, tests/BenchmarkDotNet.Tests/Engine/EngineResultStageTests.cs, tests/BenchmarkDotNet.Tests/Mocks/MockFactory.cs, tests/BenchmarkDotNet.Tests/Reports/RatioPrecisionTests.cs, tests/BenchmarkDotNet.Tests/Reports/RatioStyleTests.cs
Fixes #1736
Please let me know if you want to add an exception type somehow or add a new changelog file for the next version including this new diagnoser.
=> Issue #1736: Add ExceptionDiagnoser

src/BenchmarkDotNet/Loggers/Broker.cs
fixes https://github.com/dotnet/performance/issues/2738
=> Fix resources leak

src/BenchmarkDotNet/Portability/RuntimeInformation.cs
@radical I won't be able to test it today (11 PM here), but since it's super low risk change, I can merge it without waiting for the CI here. Could you please test it and if it solves the problem update dotnet/performace?
https://github.com/dotnet/runtime/issues/78575
=> fix WASM support

src/BenchmarkDotNet/Loggers/Broker.cs, tests/BenchmarkDotNet.IntegrationTests/FailingProcessSpawnTests.cs
=> Avoid hangs when starting benchmark process fails

src/BenchmarkDotNet/Environments/Platform.cs, src/BenchmarkDotNet/Portability/RuntimeInformation.cs
=> add Armv6 and Ppc64le architectures support

tests/BenchmarkDotNet.IntegrationTests/BenchmarkDotNet.IntegrationTests.csproj
https://github.com/dotnet/BenchmarkDotNet/pull/2018#issuecomment-1337587320
Extra line was added when merging [here](https://github.com/dotnet/BenchmarkDotNet/pull/2018/commits/c4915adea95ec46866d9e68898f0c4b5ff5297b4)
=> Remove duplicate reference

src/BenchmarkDotNet/Disassemblers/Arm64Disassembler.cs, src/BenchmarkDotNet/Disassemblers/ClrMdV2Disassembler.cs, src/BenchmarkDotNet/Disassemblers/IntelDisassembler.cs, tests/BenchmarkDotNet.IntegrationTests/DisassemblyDiagnoserTests.cs
Fixes #2223 based on investigation done by @janvorli 
Adds a temporary workaround for #2070 (see the comments)
=> Disassembler realiability fixes

src/BenchmarkDotNet.Diagnostics.Windows/JitStatsDiagnoser.cs
based on feedback from @kouvel : https://github.com/dotnet/BenchmarkDotNet/pull/2243#issuecomment-1383206578
=> improve the numbers reported for Tiered JIT

src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs, tests/BenchmarkDotNet.Tests/ConfigParserTests.cs
=> Keep generated files when MSBuild bin log is requested

src/BenchmarkDotNet/Configs/ImmutableConfigBuilder.cs, tests/BenchmarkDotNet.Tests/Configs/ImmutableConfigTests.cs
=> Fix crash when using HardwareCounter.NotSet

src/BenchmarkDotNet/Environments/Runtimes/CoreRuntime.cs
A fix for bug reported offline by @jakobbotsch
=> Fix net8.0 tfm detection

src/BenchmarkDotNet/Extensions/ReflectionExtensions.cs, tests/BenchmarkDotNet.Tests/ReflectionTests.cs
=> Add support for nested generic types

src/BenchmarkDotNet/Toolchains/CsProj/CsProjGenerator.cs, tests/BenchmarkDotNet.Tests/CsProjGeneratorTests.cs
=> Don't copy `PackageReference` in csproj

src/BenchmarkDotNet/Diagnosers/DiagnosersLoader.cs
=> Enhance Diagnoser Loading Behavior for Non-Critical Assemblies

build/BenchmarkDotNet.Build/BenchmarkDotNet.Build.csproj
[10.0.0](https://www.nuget.org/packages/Octokit/10.0.0) contains some security fixes
cc @ericstj
=> Bump Octokit version

src/BenchmarkDotNet.TestAdapter/BenchmarkExecutor.cs
=> Fix BenchmarkDotNet test adapter not running tests with dotnet test

src/BenchmarkDotNet.TestAdapter/VSTestLogger.cs, src/BenchmarkDotNet/Analysers/ConclusionHelper.cs, src/BenchmarkDotNet/Loggers/ConsoleLogger.cs, src/BenchmarkDotNet/Loggers/LinqPadLogger.cs, src/BenchmarkDotNet/Loggers/LogKind.cs, src/BenchmarkDotNet/Loggers/LoggerExtensions.cs
This pull request adds support for warning logging and integrates this new functionality with the Visual Studio test logging framework.
=> Add Support for Warning Logging and Integrate with Visual Studio Test Logging

src/BenchmarkDotNet/Environments/Platform.cs, src/BenchmarkDotNet/Portability/RuntimeInformation.cs
=> add RiscV64 support

.github/workflows/publish-nightly.yaml
https://github.com/dotnet/BenchmarkDotNet/actions/runs/13068015479
=> Fix publish-nightly failures

src/BenchmarkDotNet/Diagnosers/DiagnoserResults.cs
Wish to do some calculations when making custom diagnosers
My needs are similar to what is described in #2617
=> Added Measurements to DiagnoserResults

src/BenchmarkDotNet.Diagnostics.Windows/Tracing/NativeMemoryLogParser.cs
=> Lowercase programName in NativeMemoryLogParser.cs
